export const wordBankPart10 = [
  {
    word: 'determine',
    definition: 'decide firmly',
    synonyms: ['decide', 'settle'],
    antonyms: ['hesitate', 'dither'],
  },
  {
    word: 'retiring',
    definition: 'shy and avoiding attention',
    synonyms: ['reserved', 'bashful'],
    antonyms: ['bold', 'outgoing'],
  },
  {
    word: 'relegate',
    definition: 'put into a lower rank',
    synonyms: ['downgrade', 'demote'],
    antonyms: ['promote', 'elevate'],
  },
  {
    word: 'extricate',
    definition: 'free from a difficulty',
    synonyms: ['free', 'release'],
    antonyms: ['trap', 'entangle'],
  },
  {
    word: 'suspend',
    definition: 'stop something for a time',
    synonyms: ['pause', 'hang'],
    antonyms: ['continue', 'resume'],
  },
  {
    word: 'compelling',
    definition: 'powerfully interesting or convincing',
    synonyms: ['captivating', 'persuasive'],
    antonyms: ['weak', 'dull'],
  },
  {
    word: 'droll',
    definition: 'oddly funny',
    synonyms: ['comical', 'whimsical'],
    antonyms: ['serious', 'grave'],
  },
  {
    word: 'plethora',
    definition: 'too large an amount',
    synonyms: ['excess', 'surplus'],
    antonyms: ['scarcity', 'lack'],
  },
  {
    word: 'nefarious',
    definition: 'extremely wicked',
    synonyms: ['evil', 'villainous'],
    antonyms: ['good', 'virtuous'],
  },
  {
    word: 'pigment',
    definition: 'substance that gives colour',
    synonyms: ['dye', 'colouring'],
    antonyms: ['bleach', 'whitener'],
  },

  {
    word: 'magnate',
    definition: 'very rich and powerful person',
    synonyms: ['tycoon', 'baron'],
    antonyms: ['pauper', 'nobody'],
  },
  {
    word: 'prodigious',
    definition: 'great in size or ability',
    synonyms: ['enormous', 'remarkable'],
    antonyms: ['small', 'ordinary'],
  },
  {
    word: 'universal',
    definition: 'happening everywhere',
    synonyms: ['global', 'all-round'],
    antonyms: ['local', 'limited'],
  },
  {
    word: 'opportunist',
    definition: 'someone who takes selfish chances',
    synonyms: ['exploiter', 'self-seeker'],
    antonyms: ['altruist', 'idealist'],
  },
  {
    word: 'mercenary',
    definition: 'working only for money',
    synonyms: ['money-minded', 'soldier-for-hire'],
    antonyms: ['charitable', 'selfless'],
  },
  {
    word: 'subdued',
    definition: 'quiet and under control',
    synonyms: ['muted', 'restrained'],
    antonyms: ['loud', 'vibrant'],
  },
  {
    word: 'obsessive',
    definition: 'thinking about one thing too much',
    synonyms: ['fixated', 'compulsive'],
    antonyms: ['casual', 'indifferent'],
  },
  {
    word: 'pioneer',
    definition: 'first person to do something',
    synonyms: ['trailblazer', 'innovator'],
    antonyms: ['follower', 'copycat'],
  },
  {
    word: 'digression',
    definition: 'going off the main topic',
    synonyms: ['sidetrack', 'aside'],
    antonyms: ['focus', 'continuation'],
  },
  {
    word: 'enormousness',
    definition: 'very great size',
    synonyms: ['vastness', 'immensity'],
    antonyms: ['smallness', 'petiteness'],
  },

  {
    word: 'infuse',
    definition: 'fill something with a quality',
    synonyms: ['imbue', 'soak'],
    antonyms: ['drain', 'empty'],
  },
  {
    word: 'devise',
    definition: 'think up and plan',
    synonyms: ['invent', 'design'],
    antonyms: ['destroy', 'ruin'],
  },
  {
    word: 'cease',
    definition: 'stop',
    synonyms: ['halt', 'end'],
    antonyms: ['start', 'begin'],
  },
  {
    word: 'conspire',
    definition: 'secretly plan together',
    synonyms: ['plot', 'scheme'],
    antonyms: ['co-operate', 'obey'],
  },
  {
    word: 'mercy',
    definition: 'kind forgiveness',
    synonyms: ['leniency', 'pity'],
    antonyms: ['cruelty', 'harshness'],
  },
  {
    word: 'content',
    definition: 'satisfied',
    synonyms: ['happy', 'pleased'],
    antonyms: ['restless', 'unhappy'],
  },
  {
    word: 'adore',
    definition: 'love deeply',
    synonyms: ['love', 'cherish'],
    antonyms: ['loathe', 'detest'],
  },
  {
    word: 'unfathomable',
    definition: 'too strange to understand',
    synonyms: ['mysterious', 'deep'],
    antonyms: ['obvious', 'clear'],
  },
  {
    word: 'appeal',
    definition: 'ask earnestly; to attract',
    synonyms: ['plead', 'attract'],
    antonyms: ['repel', 'refuse'],
  },
  {
    word: 'daunt',
    definition: 'make someone lose courage',
    synonyms: ['discourage', 'intimidate'],
    antonyms: ['encourage', 'heart'],
  },

  {
    word: 'placid',
    definition: 'calm and peaceful',
    synonyms: ['tranquil', 'gentle'],
    antonyms: ['agitated', 'stormy'],
  },
  {
    word: 'deny',
    definition: 'say something isn’t true',
    synonyms: ['refuse', 'reject'],
    antonyms: ['admit', 'confirm'],
  },
  {
    word: 'degrade',
    definition: 'treat with disrespect',
    synonyms: ['humiliate', 'demean'],
    antonyms: ['honour', 'exalt'],
  },
  {
    word: 'companion',
    definition: 'friend who keeps you company',
    synonyms: ['friend', 'partner'],
    antonyms: ['enemy', 'foe'],
  },
  {
    word: 'meticulous',
    definition: 'extremely careful',
    synonyms: ['precise', 'thorough'],
    antonyms: ['sloppy', 'careless'],
  },
  {
    word: 'squeak',
    definition: 'short, high-pitched sound',
    synonyms: ['peep', 'chirp'],
    antonyms: ['roar', 'boom'],
  },
  {
    word: 'concerted',
    definition: 'done together in agreement',
    synonyms: ['joint', 'combined'],
    antonyms: ['isolated', 'separate'],
  },
  {
    word: 'animosity',
    definition: 'strong dislike',
    synonyms: ['hatred', 'hostility'],
    antonyms: ['friendship', 'goodwill'],
  },
  {
    word: 'mundane',
    definition: 'ordinary and boring',
    synonyms: ['everyday', 'dull'],
    antonyms: ['exciting', 'remarkable'],
  },
  {
    word: 'amphibian',
    definition: 'animal that lives on land and water',
    synonyms: ['frog', 'newt'],
    antonyms: ['mammal', 'bird'],
  },

  {
    word: 'discordant',
    definition: 'sounding harsh or in conflict',
    synonyms: ['clashing', 'jarring'],
    antonyms: ['harmonious', 'melodic'],
  },
  {
    word: 'susceptible',
    definition: 'easily affected by',
    synonyms: ['prone', 'vulnerable'],
    antonyms: ['resistant', 'immune'],
  },
  {
    word: 'disastrous',
    definition: 'causing great harm',
    synonyms: ['catastrophic', 'ruinous'],
    antonyms: ['fortunate', 'successful'],
  },
  {
    word: 'quagmire',
    definition: 'difficult, messy situation',
    synonyms: ['mess', 'predicament'],
    antonyms: ['solution', 'ease'],
  },
  {
    word: 'irrelevant',
    definition: 'not related to the subject',
    synonyms: ['unrelated', 'off-topic'],
    antonyms: ['relevant', 'related'],
  },
  {
    word: 'restrain',
    definition: 'hold back',
    synonyms: ['control', 'limit'],
    antonyms: ['release', 'free'],
  },
  {
    word: 'inevitably',
    definition: 'certain to happen',
    synonyms: ['certainly', 'surely'],
    antonyms: ['possibly', 'doubtfully'],
  },
  {
    word: 'frugal',
    definition: 'careful about spending money',
    synonyms: ['thrifty', 'economical'],
    antonyms: ['wasteful', 'extravagant'],
  },
  {
    word: 'immediately',
    definition: 'right away',
    synonyms: ['instantly', 'promptly'],
    antonyms: ['later', 'eventually'],
  },
  {
    word: 'expertise',
    definition: 'special skill or knowledge',
    synonyms: ['skill', 'know-how'],
    antonyms: ['ignorance', 'inexperience'],
  },

  {
    word: 'arouse',
    definition: 'wake up or excite',
    synonyms: ['stimulate', 'provoke'],
    antonyms: ['calm', 'soothe'],
  },
  {
    word: 'ample',
    definition: 'more than enough',
    synonyms: ['plentiful', 'abundant'],
    antonyms: ['scant', 'meagre'],
  },
  {
    word: 'decadent',
    definition: 'morally or luxuriously over-the-top',
    synonyms: ['self-indulgent', 'lavish'],
    antonyms: ['austere', 'simple'],
  },
  {
    word: 'perceptive',
    definition: 'quick to notice things',
    synonyms: ['observant', 'insightful'],
    antonyms: ['oblivious', 'slow'],
  },
  {
    word: 'affectionate',
    definition: 'showing love',
    synonyms: ['loving', 'caring'],
    antonyms: ['cold', 'distant'],
  },
  {
    word: 'impecunious',
    definition: 'having little money',
    synonyms: ['poor', 'penniless'],
    antonyms: ['wealthy', 'affluent'],
  },
  {
    word: 'vice',
    definition: 'bad habit or moral fault',
    synonyms: ['sin', 'fault'],
    antonyms: ['virtue', 'goodness'],
  },
  {
    word: 'authentic',
    definition: 'genuine and real',
    synonyms: ['real', 'true'],
    antonyms: ['fake', 'false'],
  },
  {
    word: 'scowl',
    definition: 'angry frown',
    synonyms: ['glare', 'grimace'],
    antonyms: ['smile', 'grin'],
  },
  {
    word: 'hallowed',
    definition: 'holy and respected',
    synonyms: ['sacred', 'blessed'],
    antonyms: ['profane', 'unholy'],
  },

  {
    word: 'Britain',
    definition: 'the United Kingdom',
    synonyms: ['UK', 'Great Britain'],
    antonyms: ['—', '—'],
  },
  {
    word: 'plunder',
    definition: 'steal goods by force',
    synonyms: ['loot', 'rob'],
    antonyms: ['return', 'donate'],
  },
  {
    word: 'idiom',
    definition: 'phrase with special meaning',
    synonyms: ['expression', 'phrase'],
    antonyms: ['literal', '—'],
  },
  {
    word: 'depressing',
    definition: 'making you feel very sad',
    synonyms: ['sad', 'gloomy'],
    antonyms: ['cheerful', 'uplifting'],
  },
  {
    word: 'curtail',
    definition: 'cut short',
    synonyms: ['reduce', 'limit'],
    antonyms: ['extend', 'lengthen'],
  },
  {
    word: 'seize',
    definition: 'take suddenly by force',
    synonyms: ['grab', 'snatch'],
    antonyms: ['release', 'give'],
  },
  {
    word: 'retreat',
    definition: 'go back to safety',
    synonyms: ['withdraw', 'pull back'],
    antonyms: ['advance', 'attack'],
  },
  {
    word: 'imprudent',
    definition: 'not sensible or wise',
    synonyms: ['rash', 'reckless'],
    antonyms: ['prudent', 'careful'],
  },
  {
    word: 'pensive',
    definition: 'deeply thoughtful and often sad',
    synonyms: ['thoughtful', 'reflective'],
    antonyms: ['carefree', 'cheerful'],
  },
  {
    word: 'resign',
    definition: 'quit a job',
    synonyms: ['quit', 'leave'],
    antonyms: ['remain', 'accept'],
  },

  {
    word: 'sturdy',
    definition: 'strong and solid',
    synonyms: ['robust', 'tough'],
    antonyms: ['weak', 'fragile'],
  },
  {
    word: 'paragon',
    definition: 'perfect example',
    synonyms: ['model', 'ideal'],
    antonyms: ['flaw', 'fault'],
  },
  {
    word: 'weary',
    definition: 'very tired',
    synonyms: ['tired', 'exhausted'],
    antonyms: ['fresh', 'lively'],
  },
  {
    word: 'puncture',
    definition: 'small hole made by a sharp object',
    synonyms: ['hole', 'pierce'],
    antonyms: ['seal', 'plug'],
  },
  {
    word: 'deliberate',
    definition: 'done on purpose; think carefully',
    synonyms: ['intentional', 'consider'],
    antonyms: ['accidental', 'hasty'],
  },
  {
    word: 'deranged',
    definition: 'mentally disturbed',
    synonyms: ['crazy', 'insane'],
    antonyms: ['sane', 'balanced'],
  },
  {
    word: 'conferred',
    definition: 'given after discussion',
    synonyms: ['awarded', 'granted'],
    antonyms: ['withheld', 'denied'],
  },
  {
    word: 'yield',
    definition: 'give way or produce',
    synonyms: ['give', 'produce'],
    antonyms: ['resist', 'retain'],
  },
  {
    word: 'compliance',
    definition: 'doing what is asked',
    synonyms: ['obedience', 'submission'],
    antonyms: ['defiance', 'resistance'],
  },
  {
    word: 'submissive',
    definition: 'willing to obey others',
    synonyms: ['obedient', 'meek'],
    antonyms: ['assertive', 'defiant'],
  },

  {
    word: 'malignant',
    definition: 'dangerous and harmful',
    synonyms: ['deadly', 'cancerous'],
    antonyms: ['benign', 'harmless'],
  },
  {
    word: 'nemesis',
    definition: 'arch-enemy or downfall',
    synonyms: ['enemy', 'downfall'],
    antonyms: ['ally', 'helper'],
  },
  {
    word: 'expense',
    definition: 'cost',
    synonyms: ['cost', 'charge'],
    antonyms: ['income', 'gain'],
  },
  {
    word: 'vociferous',
    definition: 'loud and forceful',
    synonyms: ['noisy', 'clamorous'],
    antonyms: ['quiet', 'subdued'],
  },
  {
    word: 'serendipity',
    definition: 'lucky discovery',
    synonyms: ['chance', 'fluke'],
    antonyms: ['misfortune', 'bad luck'],
  },
  {
    word: 'turbulent',
    definition: 'full of disorder',
    synonyms: ['stormy', 'chaotic'],
    antonyms: ['calm', 'peaceful'],
  },
  {
    word: 'equip',
    definition: 'supply with what is needed',
    synonyms: ['arm', 'provide'],
    antonyms: ['strip', 'deprive'],
  },
  {
    word: 'coax',
    definition: 'gently persuade',
    synonyms: ['cajole', 'sweet-talk'],
    antonyms: ['deter', 'bully'],
  },
  {
    word: 'divergent',
    definition: 'moving in different directions',
    synonyms: ['different', 'separating'],
    antonyms: ['convergent', 'similar'],
  },
  {
    word: 'analogy',
    definition: 'comparison showing similarity',
    synonyms: ['comparison', 'parallel'],
    antonyms: ['difference', 'contrast'],
  },

  {
    word: 'servile',
    definition: 'too eager to serve',
    synonyms: ['subservient', 'slavish'],
    antonyms: ['assertive', 'domineering'],
  },
  {
    word: 'affliction',
    definition: 'something that causes pain',
    synonyms: ['illness', 'suffering'],
    antonyms: ['health', 'comfort'],
  },
  {
    word: 'regretful',
    definition: 'feeling sorry',
    synonyms: ['sorry', 'remorseful'],
    antonyms: ['proud', 'unrepentant'],
  },
  {
    word: 'disparate',
    definition: 'very different',
    synonyms: ['distinct', 'unequal'],
    antonyms: ['similar', 'alike'],
  },
  {
    word: 'discombobulated',
    definition: 'confused and upset',
    synonyms: ['confused', 'bewildered'],
    antonyms: ['clear', 'composed'],
  },
  {
    word: 'aggressor',
    definition: 'person who starts a fight',
    synonyms: ['attacker', 'instigator'],
    antonyms: ['defender', 'victim'],
  },
  {
    word: 'hospitable',
    definition: 'welcoming to guests',
    synonyms: ['welcoming', 'friendly'],
    antonyms: ['unfriendly', 'hostile'],
  },
  {
    word: 'stagnant',
    definition: 'not moving or growing',
    synonyms: ['still', 'stale'],
    antonyms: ['flowing', 'fresh'],
  },
  {
    word: 'obliterate',
    definition: 'destroy completely',
    synonyms: ['wipe out', 'erase'],
    antonyms: ['build', 'create'],
  },
  {
    word: 'severe',
    definition: 'very harsh',
    synonyms: ['harsh', 'strict'],
    antonyms: ['mild', 'gentle'],
  },

  {
    word: 'commotion',
    definition: 'noisy confusion',
    synonyms: ['uproar', 'ruckus'],
    antonyms: ['calm', 'silence'],
  },
  {
    word: 'friend',
    definition: 'person you like and trust',
    synonyms: ['pal', 'buddy'],
    antonyms: ['enemy', 'foe'],
  },
  {
    word: 'implausible',
    definition: 'hard to believe',
    synonyms: ['unlikely', 'improbable'],
    antonyms: ['likely', 'plausible'],
  },
  {
    word: 'opaque',
    definition: 'not letting light through',
    synonyms: ['cloudy', 'non-transparent'],
    antonyms: ['clear', 'transparent'],
  },
  {
    word: 'vague',
    definition: 'not clear or exact',
    synonyms: ['unclear', 'fuzzy'],
    antonyms: ['specific', 'definite'],
  },
  {
    word: 'poignant',
    definition: 'deeply moving',
    synonyms: ['touching', 'emotional'],
    antonyms: ['dull', 'unmoving'],
  },
  {
    word: 'favourite',
    definition: 'most liked',
    synonyms: ['preferred', 'best-loved'],
    antonyms: ['hated', 'disliked'],
  },
  {
    word: 'supposed',
    definition: 'thought to be true',
    synonyms: ['alleged', 'assumed'],
    antonyms: ['real', 'proven'],
  },
  {
    word: 'consent',
    definition: 'agree to something',
    synonyms: ['agree', 'permission'],
    antonyms: ['refusal', 'denial'],
  },
  {
    word: 'mogul',
    definition: 'powerful business person',
    synonyms: ['magnate', 'tycoon'],
    antonyms: ['nobody', 'underling'],
  },

  {
    word: 'attentive',
    definition: 'paying close attention',
    synonyms: ['alert', 'watchful'],
    antonyms: ['inattentive', 'distracted'],
  },
  {
    word: 'goaded',
    definition: 'pushed into action',
    synonyms: ['urged', 'provoked'],
    antonyms: ['deterred', 'calmed'],
  },
  {
    word: 'patronizing',
    definition: 'treating others as inferior',
    synonyms: ['condescending', 'snobbish'],
    antonyms: ['respectful', 'humble'],
  },
  {
    word: 'cultivate',
    definition: 'prepare and grow',
    synonyms: ['grow', 'develop'],
    antonyms: ['neglect', 'abandon'],
  },
  {
    word: 'sphere',
    definition: 'ball shape or area of activity',
    synonyms: ['globe', 'domain'],
    antonyms: ['cube', 'line'],
  },
  {
    word: 'nauseam',
    definition: 'endlessly to sickness (as in ad nauseam)',
    synonyms: ['excessively', 'endlessly'],
    antonyms: ['briefly', 'seldom'],
  },
  {
    word: 'belligerent',
    definition: 'angry and ready to fight',
    synonyms: ['aggressive', 'hostile'],
    antonyms: ['peaceful', 'friendly'],
  },
  {
    word: 'adequately',
    definition: 'well enough',
    synonyms: ['sufficiently', 'properly'],
    antonyms: ['poorly', 'inadequately'],
  },
  {
    word: 'irresolute',
    definition: 'unable to decide',
    synonyms: ['uncertain', 'indecisive'],
    antonyms: ['resolute', 'determined'],
  },
  {
    word: 'inundate',
    definition: 'flood with water or tasks',
    synonyms: ['flood', 'overwhelm'],
    antonyms: ['drain', 'ease'],
  },

  {
    word: 'fragment',
    definition: 'small broken piece',
    synonyms: ['piece', 'shard'],
    antonyms: ['whole', 'entirety'],
  },
  {
    word: 'accessible',
    definition: 'easy to reach or use',
    synonyms: ['available', 'reachable'],
    antonyms: ['inaccessible', 'remote'],
  },
  {
    word: 'impoverished',
    definition: 'made very poor',
    synonyms: ['poor', 'destitute'],
    antonyms: ['wealthy', 'rich'],
  },
  {
    word: 'hasty',
    definition: 'done too quickly',
    synonyms: ['rash', 'quick'],
    antonyms: ['slow', 'careful'],
  },
  {
    word: 'farcical',
    definition: 'ridiculously silly',
    synonyms: ['absurd', 'ludicrous'],
    antonyms: ['serious', 'sensible'],
  },
  {
    word: 'credulous',
    definition: 'too ready to believe',
    synonyms: ['gullible', 'trusting'],
    antonyms: ['sceptical', 'doubting'],
  },
  {
    word: 'benevolent',
    definition: 'kind and generous',
    synonyms: ['kind', 'charitable'],
    antonyms: ['malevolent', 'unkind'],
  },
  {
    word: 'virulent',
    definition: 'highly harmful or infectious',
    synonyms: ['deadly', 'toxic'],
    antonyms: ['harmless', 'benign'],
  },
  {
    word: 'proclivity',
    definition: 'natural tendency',
    synonyms: ['inclination', 'leaning'],
    antonyms: ['aversion', 'dislike'],
  },
  {
    word: 'notoriety',
    definition: 'bad fame',
    synonyms: ['infamy', 'disrepute'],
    antonyms: ['renown', 'esteem'],
  },

  {
    word: 'oblivion',
    definition: 'state of being forgotten',
    synonyms: ['forgetfulness', 'darkness'],
    antonyms: ['fame', 'memory'],
  },
  {
    word: 'discerning',
    definition: 'showing good judgement',
    synonyms: ['perceptive', 'astute'],
    antonyms: ['blind', 'unaware'],
  },
  {
    word: 'precedent',
    definition: 'earlier example to follow',
    synonyms: ['example', 'model'],
    antonyms: ['subsequent', 'follower'],
  },
  {
    word: 'employ',
    definition: 'give work to',
    synonyms: ['hire', 'use'],
    antonyms: ['dismiss', 'unemploy'],
  },
  {
    word: 'adversary',
    definition: 'opponent',
    synonyms: ['enemy', 'foe'],
    antonyms: ['ally', 'friend'],
  },
  {
    word: 'procure',
    definition: 'get with effort',
    synonyms: ['obtain', 'acquire'],
    antonyms: ['lose', 'forfeit'],
  },
  {
    word: 'ascent',
    definition: 'act of rising',
    synonyms: ['climb', 'rise'],
    antonyms: ['descent', 'fall'],
  },
  {
    word: 'intimidate',
    definition: 'frighten into doing something',
    synonyms: ['bully', 'scare'],
    antonyms: ['encourage', 'reassure'],
  },
  {
    word: 'vanadium',
    definition: 'a hard grey metal element',
    synonyms: ['metal', 'element'],
    antonyms: ['—', '—'],
  },
  {
    word: 'antonym',
    definition: 'word with opposite meaning',
    synonyms: ['opposite', 'contrast'],
    antonyms: ['synonym', 'equivalent'],
  },

  {
    word: 'pasture',
    definition: 'field where animals graze',
    synonyms: ['meadow', 'grassland'],
    antonyms: ['desert', 'wasteland'],
  },
  {
    word: 'pessimist',
    definition: 'person who expects bad outcomes',
    synonyms: ['doom-monger', 'gloom-ster'],
    antonyms: ['optimist', 'hopeful'],
  },
  {
    word: 'mediocrity',
    definition: 'state of being only average',
    synonyms: ['ordinariness', 'averageness'],
    antonyms: ['excellence', 'brilliance'],
  },
  {
    word: 'disseminate',
    definition: 'spread widely',
    synonyms: ['scatter', 'broadcast'],
    antonyms: ['gather', 'collect'],
  },
  {
    word: 'obstreperous',
    definition: 'noisy and difficult to control',
    synonyms: ['rowdy', 'unruly'],
    antonyms: ['quiet', 'obedient'],
  },
  {
    word: 'insatiable',
    definition: 'never satisfied',
    synonyms: ['greedy', 'voracious'],
    antonyms: ['satisfied', 'content'],
  },
  {
    word: 'handsome',
    definition: 'good-looking (usually male)',
    synonyms: ['attractive', 'good-looking'],
    antonyms: ['ugly', 'plain'],
  },
  {
    word: 'alacrity',
    definition: 'eager readiness',
    synonyms: ['eagerness', 'promptness'],
    antonyms: ['slowness', 'reluctance'],
  },
  {
    word: 'monotony',
    definition: 'lack of variety',
    synonyms: ['sameness', 'dullness'],
    antonyms: ['variety', 'excitement'],
  },
  {
    word: 'credit',
    definition: 'praise or trust; money lent',
    synonyms: ['praise', 'trust'],
    antonyms: ['blame', 'debt'],
  },

  {
    word: 'enduring',
    definition: 'lasting a long time',
    synonyms: ['lasting', 'durable'],
    antonyms: ['temporary', 'brief'],
  },
  {
    word: 'lavish',
    definition: 'spend or give generously',
    synonyms: ['extravagant', 'luxurious'],
    antonyms: ['stingy', 'meagre'],
  },
  {
    word: 'humane',
    definition: 'kind to people or animals',
    synonyms: ['kind', 'compassionate'],
    antonyms: ['cruel', 'inhumane'],
  },
  {
    word: 'arduous',
    definition: 'very difficult',
    synonyms: ['hard', 'tough'],
    antonyms: ['easy', 'simple'],
  },
  {
    word: 'unscrupulous',
    definition: 'without moral principles',
    synonyms: ['dishonest', 'unethical'],
    antonyms: ['honest', 'ethical'],
  },
  {
    word: 'vivid',
    definition: 'bright and full of life',
    synonyms: ['bright', 'lively'],
    antonyms: ['dull', 'pale'],
  },
  {
    word: 'virtue',
    definition: 'moral goodness',
    synonyms: ['goodness', 'morality'],
    antonyms: ['vice', 'sin'],
  },
  {
    word: 'sincere',
    definition: 'genuine and honest',
    synonyms: ['honest', 'truthful'],
    antonyms: ['insincere', 'false'],
  },
  {
    word: 'sequester',
    definition: 'keep separate and apart',
    synonyms: ['isolate', 'separate'],
    antonyms: ['unite', 'join'],
  },
  {
    word: 'noted',
    definition: 'famous and well known',
    synonyms: ['famous', 'renowned'],
    antonyms: ['unknown', 'obscure'],
  },

  {
    word: 'composition',
    definition: 'piece of writing or music',
    synonyms: ['work', 'piece'],
    antonyms: ['silence', 'chaos'],
  },
  {
    word: 'divinity',
    definition: 'study of God; being a god',
    synonyms: ['theology', 'godhood'],
    antonyms: ['mortality', 'humanity'],
  },
  {
    word: 'slothful',
    definition: 'lazy',
    synonyms: ['lazy', 'idle'],
    antonyms: ['hard-working', 'energetic'],
  },
  {
    word: 'sanitary',
    definition: 'clean and healthy',
    synonyms: ['hygienic', 'clean'],
    antonyms: ['dirty', 'unsanitary'],
  },
  {
    word: 'ramble',
    definition: 'walk or talk aimlessly',
    synonyms: ['wander', 'roam'],
    antonyms: ['march', 'focus'],
  },
  {
    word: 'charlatan',
    definition: 'person who pretends to know',
    synonyms: ['fraud', 'quack'],
    antonyms: ['expert', 'professional'],
  },
  {
    word: 'bequeath',
    definition: 'leave property in a will',
    synonyms: ['leave', 'hand down'],
    antonyms: ['inherit', 'take'],
  },
  {
    word: 'expedient',
    definition: 'useful but not always right',
    synonyms: ['convenient', 'practical'],
    antonyms: ['impractical', 'unwise'],
  },
  {
    word: 'famine',
    definition: 'extreme lack of food',
    synonyms: ['starvation', 'hunger'],
    antonyms: ['plenty', 'feast'],
  },
  {
    word: 'hamper',
    definition: 'hinder or laundry basket',
    synonyms: ['hinder', 'basket'],
    antonyms: ['help', 'aid'],
  },

  {
    word: 'surprise',
    definition: 'unexpected event',
    synonyms: ['shock', 'astonishment'],
    antonyms: ['expectation', 'routine'],
  },
  {
    word: 'contrition',
    definition: 'deep regret for wrongdoing',
    synonyms: ['remorse', 'repentance'],
    antonyms: ['shamelessness', 'pride'],
  },
  {
    word: 'pejorative',
    definition: 'word expressing disapproval',
    synonyms: ['insulting', 'derogatory'],
    antonyms: ['complimentary', 'praising'],
  },
  {
    word: 'hostile',
    definition: 'very unfriendly',
    synonyms: ['unfriendly', 'aggressive'],
    antonyms: ['friendly', 'kind'],
  },
  {
    word: 'company',
    definition: 'business; people together',
    synonyms: ['business', 'group'],
    antonyms: ['isolation', 'alone'],
  },
  {
    word: 'duration',
    definition: 'length of time',
    synonyms: ['length', 'period'],
    antonyms: ['instant', 'moment'],
  },
  {
    word: 'materialism',
    definition: 'love of possessions',
    synonyms: ['greed', 'consumerism'],
    antonyms: ['spirituality', 'simplicity'],
  },
  {
    word: 'adverse',
    definition: 'harmful or unfavourable',
    synonyms: ['unfavourable', 'bad'],
    antonyms: ['favourable', 'beneficial'],
  },
  {
    word: 'bittersweet',
    definition: 'both happy and sad',
    synonyms: ['mixed', 'touching'],
    antonyms: ['sweet', 'pleasant'],
  },
  {
    word: 'dwelling',
    definition: 'place where someone lives',
    synonyms: ['home', 'residence'],
    antonyms: ['office', 'street'],
  },

  {
    word: 'exacerbate',
    definition: 'make worse',
    synonyms: ['worsen', 'aggravate'],
    antonyms: ['improve', 'ease'],
  },
  {
    word: 'perilous',
    definition: 'very dangerous',
    synonyms: ['dangerous', 'hazardous'],
    antonyms: ['safe', 'secure'],
  },
  {
    word: 'ardour',
    definition: 'strong enthusiasm',
    synonyms: ['passion', 'zeal'],
    antonyms: ['apathy', 'indifference'],
  },
  {
    word: 'taciturn',
    definition: 'speaking very little',
    synonyms: ['silent', 'reserved'],
    antonyms: ['talkative', 'garrulous'],
  },
  {
    word: 'diligent',
    definition: 'hard-working',
    synonyms: ['industrious', 'hard-working'],
    antonyms: ['lazy', 'idle'],
  },
  {
    word: 'undermine',
    definition: 'weaken secretly',
    synonyms: ['weaken', 'sabotage'],
    antonyms: ['strengthen', 'support'],
  },
  {
    word: 'persuade',
    definition: 'make someone agree',
    synonyms: ['convince', 'influence'],
    antonyms: ['deter', 'discourage'],
  },
  {
    word: 'majestic',
    definition: 'grand and impressive',
    synonyms: ['grand', 'stately'],
    antonyms: ['ordinary', 'humble'],
  },
  {
    word: 'prudence',
    definition: 'careful good judgement',
    synonyms: ['wisdom', 'caution'],
    antonyms: ['recklessness', 'folly'],
  },
  {
    word: 'contribute',
    definition: 'give help or money',
    synonyms: ['give', 'donate'],
    antonyms: ['withhold', 'take'],
  },

  {
    word: 'idyllic',
    definition: 'peaceful and perfect',
    synonyms: ['perfect', 'picturesque'],
    antonyms: ['bleak', 'grim'],
  },
  {
    word: 'discretionary',
    definition: 'based on personal choice',
    synonyms: ['optional', 'voluntary'],
    antonyms: ['mandatory', 'compulsory'],
  },
  {
    word: 'deposit',
    definition: 'put money in bank or layer',
    synonyms: ['pay in', 'layer'],
    antonyms: ['withdraw', 'erode'],
  },
  {
    word: 'pithy',
    definition: 'short but full of meaning',
    synonyms: ['concise', 'brief'],
    antonyms: ['wordy', 'verbose'],
  },
  {
    word: 'sane',
    definition: 'mentally healthy',
    synonyms: ['rational', 'sound'],
    antonyms: ['insane', 'mad'],
  },
  {
    word: 'parry',
    definition: 'ward off a blow',
    synonyms: ['deflect', 'block'],
    antonyms: ['accept', 'allow'],
  },
  {
    word: 'Machiavellian',
    definition: 'cunning and sly in politics',
    synonyms: ['scheming', 'crafty'],
    antonyms: ['honest', 'naive'],
  },
  {
    word: 'deference',
    definition: 'respectful submission',
    synonyms: ['respect', 'regard'],
    antonyms: ['disrespect', 'defiance'],
  },
  {
    word: 'lenient',
    definition: 'not strict',
    synonyms: ['gentle', 'forgiving'],
    antonyms: ['strict', 'harsh'],
  },
  {
    word: 'candour',
    definition: 'open honesty',
    synonyms: ['frankness', 'openness'],
    antonyms: ['deceit', 'lying'],
  },

  {
    word: 'inexplicable',
    definition: 'cannot be explained',
    synonyms: ['unexplained', 'mysterious'],
    antonyms: ['clear', 'obvious'],
  },
  {
    word: 'antithesis',
    definition: 'the exact opposite',
    synonyms: ['opposite', 'contrast'],
    antonyms: ['same', 'equivalent'],
  },
  {
    word: 'pompous',
    definition: 'self-important and grand',
    synonyms: ['arrogant', 'grandiose'],
    antonyms: ['modest', 'humble'],
  },
  {
    word: 'definite',
    definition: 'clear and certain',
    synonyms: ['certain', 'exact'],
    antonyms: ['vague', 'indefinite'],
  },
  {
    word: 'perpetuate',
    definition: 'keep something going forever',
    synonyms: ['continue', 'maintain'],
    antonyms: ['end', 'halt'],
  },
  {
    word: 'scion',
    definition: 'young member of a rich family',
    synonyms: ['descendant', 'heir'],
    antonyms: ['ancestor', 'root'],
  },
  {
    word: 'overt',
    definition: 'open and obvious',
    synonyms: ['open', 'explicit'],
    antonyms: ['covert', 'hidden'],
  },
  {
    word: 'feeble',
    definition: 'very weak',
    synonyms: ['weak', 'frail'],
    antonyms: ['strong', 'robust'],
  },
  {
    word: 'saturate',
    definition: 'soak completely',
    synonyms: ['soak', 'drench'],
    antonyms: ['dry', 'drain'],
  },
  {
    word: 'superficial',
    definition: 'only on the surface',
    synonyms: ['shallow', 'surface'],
    antonyms: ['deep', 'thorough'],
  },

  {
    word: 'exhilarating',
    definition: 'making you feel very excited',
    synonyms: ['thrilling', 'exciting'],
    antonyms: ['boring', 'dull'],
  },
  {
    word: 'reserve',
    definition: 'save for later; quiet nature',
    synonyms: ['save', 'reticence'],
    antonyms: ['spend', 'openness'],
  },
  {
    word: 'allusion',
    definition: 'indirect reference',
    synonyms: ['hint', 'reference'],
    antonyms: ['statement', 'fact'],
  },
  {
    word: 'spiteful',
    definition: 'wanting to hurt',
    synonyms: ['malicious', 'vindictive'],
    antonyms: ['kind', 'benevolent'],
  },
  {
    word: 'errand',
    definition: 'short trip to do a task',
    synonyms: ['task', 'mission'],
    antonyms: ['vacation', '—'],
  },
  {
    word: 'insipid',
    definition: 'lacking flavour or interest',
    synonyms: ['bland', 'dull'],
    antonyms: ['tasty', 'interesting'],
  },
  {
    word: 'absurd',
    definition: 'ridiculously unreasonable',
    synonyms: ['ludicrous', 'ridiculous'],
    antonyms: ['sensible', 'reasonable'],
  },
  {
    word: 'apoplectic',
    definition: 'furious to the point of choking',
    synonyms: ['livid', 'enraged'],
    antonyms: ['calm', 'placid'],
  },
  {
    word: 'malapropism',
    definition: 'comic misuse of a word',
    synonyms: ['word mix-up', 'blunder'],
    antonyms: ['accuracy', 'precision'],
  },
  {
    word: 'explanation',
    definition: 'something that makes things clear',
    synonyms: ['clarification', 'account'],
    antonyms: ['mystery', 'confusion'],
  },

  {
    word: 'profane',
    definition: 'disrespectful to holy things',
    synonyms: ['irreverent', 'blasphemous'],
    antonyms: ['sacred', 'reverent'],
  },
  {
    word: 'incidental',
    definition: 'happening by chance',
    synonyms: ['secondary', 'accidental'],
    antonyms: ['main', 'deliberate'],
  },
  {
    word: 'gratitude',
    definition: 'thankfulness',
    synonyms: ['thanks', 'appreciation'],
    antonyms: ['ingratitude', 'resentment'],
  },
  {
    word: 'diffuse',
    definition: 'spread out widely',
    synonyms: ['scatter', 'spread'],
    antonyms: ['concentrate', 'focus'],
  },
  {
    word: 'self-deprecating',
    definition: 'criticising yourself in a funny way',
    synonyms: ['modest', 'humble'],
    antonyms: ['boastful', 'proud'],
  },
  {
    word: 'keel',
    definition: 'main beam of a boat; to capsize',
    synonyms: ['boat-base', 'capsize'],
    antonyms: ['upright', 'steady'],
  },
  {
    word: 'precipitous',
    definition: 'very steep or sudden',
    synonyms: ['steep', 'sudden'],
    antonyms: ['gentle', 'gradual'],
  },
  {
    word: 'incoherent',
    definition: 'not clear or logical',
    synonyms: ['confused', 'jumbled'],
    antonyms: ['coherent', 'clear'],
  },
  {
    word: 'colour',
    definition: 'hue seen by the eye',
    synonyms: ['hue', 'shade'],
    antonyms: ['colourless', '—'],
  },
  {
    word: 'misnomer',
    definition: 'wrong or unsuitable name',
    synonyms: ['wrong name', 'mislabel'],
    antonyms: ['accurate term', '—'],
  },

  {
    word: 'inadequate',
    definition: 'not enough or not good enough',
    synonyms: ['insufficient', 'lacking'],
    antonyms: ['adequate', 'sufficient'],
  },
  {
    word: 'grudging',
    definition: 'done unwillingly',
    synonyms: ['reluctant', 'unwilling'],
    antonyms: ['eager', 'willing'],
  },
  {
    word: 'merry',
    definition: 'cheerful and lively',
    synonyms: ['cheerful', 'jolly'],
    antonyms: ['sad', 'miserable'],
  },
  {
    word: 'ironic',
    definition: 'opposite of what is expected',
    synonyms: ['sarcastic', 'wry'],
    antonyms: ['sincere', 'straight'],
  },
  {
    word: 'gravity',
    definition: 'force pulling things down; seriousness',
    synonyms: ['weight', 'seriousness'],
    antonyms: ['levity', 'triviality'],
  },
  {
    word: 'hygienic',
    definition: 'clean and healthy',
    synonyms: ['sanitary', 'clean'],
    antonyms: ['dirty', 'unsanitary'],
  },
  {
    word: 'economical',
    definition: 'using resources carefully',
    synonyms: ['thrifty', 'frugal'],
    antonyms: ['wasteful', 'extravagant'],
  },
  {
    word: 'conciliatory',
    definition: 'aimed at making peace',
    synonyms: ['appeasing', 'soothing'],
    antonyms: ['provoking', 'hostile'],
  },
  {
    word: 'reactionary',
    definition: 'strongly against change',
    synonyms: ['conservative', 'backward'],
    antonyms: ['progressive', 'radical'],
  },
  {
    word: 'deceive',
    definition: 'make someone believe a lie',
    synonyms: ['trick', 'mislead'],
    antonyms: ['inform', 'enlighten'],
  },

  {
    word: 'meddle',
    definition: 'interfere in others’ business',
    synonyms: ['interfere', 'tamper'],
    antonyms: ['ignore', 'respect'],
  },
  {
    word: 'immerse',
    definition: 'put fully into liquid or activity',
    synonyms: ['dip', 'engage'],
    antonyms: ['withdraw', 'surface'],
  },
  {
    word: 'burden',
    definition: 'heavy load or worry',
    synonyms: ['load', 'weight'],
    antonyms: ['relief', 'lightness'],
  },
  {
    word: 'depravity',
    definition: 'moral corruption',
    synonyms: ['wickedness', 'corruption'],
    antonyms: ['virtue', 'goodness'],
  },
  {
    word: 'dazzling',
    definition: 'shining brightly; amazing',
    synonyms: ['sparkling', 'brilliant'],
    antonyms: ['dull', 'drab'],
  },
  {
    word: 'autonomous',
    definition: 'self-governing',
    synonyms: ['independent', 'self-ruling'],
    antonyms: ['dependent', 'controlled'],
  },
  {
    word: 'depot',
    definition: 'place for storage or transport hub',
    synonyms: ['warehouse', 'station'],
    antonyms: ['—', '—'],
  },
  {
    word: 'polarity',
    definition: 'state of having two opposite parts',
    synonyms: ['duality', 'opposition'],
    antonyms: ['unity', 'sameness'],
  },
  {
    word: 'foundation',
    definition: 'base on which something rests',
    synonyms: ['base', 'groundwork'],
    antonyms: ['top', 'superstructure'],
  },
  {
    word: 'limb',
    definition: 'arm or leg of a person or tree branch',
    synonyms: ['branch', 'arm'],
    antonyms: ['trunk', 'body'],
  },

  {
    word: 'enmity',
    definition: 'deep hatred',
    synonyms: ['hostility', 'antagonism'],
    antonyms: ['friendship', 'amity'],
  },
  {
    word: 'believe',
    definition: 'accept as true',
    synonyms: ['trust', 'accept'],
    antonyms: ['doubt', 'disbelieve'],
  },
  {
    word: 'docile',
    definition: 'easy to teach or control',
    synonyms: ['obedient', 'compliant'],
    antonyms: ['rebellious', 'stubborn'],
  },
  {
    word: 'omit',
    definition: 'leave out',
    synonyms: ['leave out', 'exclude'],
    antonyms: ['include', 'add'],
  },
  {
    word: 'profusion',
    definition: 'large quantity',
    synonyms: ['abundance', 'plenty'],
    antonyms: ['scarcity', 'lack'],
  },
  {
    word: 'aberrant',
    definition: 'not normal',
    synonyms: ['abnormal', 'deviant'],
    antonyms: ['normal', 'typical'],
  },
  {
    word: 'committee',
    definition: 'group chosen to do a task',
    synonyms: ['panel', 'board'],
    antonyms: ['individual', 'one'],
  },
  {
    word: 'candidate',
    definition: 'person applying for something',
    synonyms: ['applicant', 'nominee'],
    antonyms: ['incumbent', 'employer'],
  },
  {
    word: 'revile',
    definition: 'speak abusively about',
    synonyms: ['insult', 'vilify'],
    antonyms: ['praise', 'commend'],
  },
  {
    word: 'despise',
    definition: 'feel deep dislike for',
    synonyms: ['hate', 'detest'],
    antonyms: ['admire', 'love'],
  },

  {
    word: 'address',
    definition: 'speak to; location of a place',
    synonyms: ['speak', 'location'],
    antonyms: ['ignore', 'silence'],
  },
  {
    word: 'peril',
    definition: 'serious danger',
    synonyms: ['danger', 'risk'],
    antonyms: ['safety', 'security'],
  },
  {
    word: 'surly',
    definition: 'bad-tempered and rude',
    synonyms: ['grumpy', 'ill-humoured'],
    antonyms: ['cheerful', 'pleasant'],
  },
  {
    word: 'mitigate',
    definition: 'make less bad',
    synonyms: ['ease', 'soften'],
    antonyms: ['worsen', 'aggravate'],
  },
  {
    word: 'minimum',
    definition: 'smallest amount',
    synonyms: ['least', 'lowest'],
    antonyms: ['maximum', 'most'],
  },
  {
    word: 'union',
    definition: 'joining together',
    synonyms: ['joining', 'merger'],
    antonyms: ['separation', 'split'],
  },
  {
    word: 'monotonous',
    definition: 'boringly repetitive',
    synonyms: ['dull', 'repetitive'],
    antonyms: ['lively', 'varied'],
  },
  {
    word: 'equivocate',
    definition: 'speak unclearly on purpose',
    synonyms: ['prevaricate', 'vagueness'],
    antonyms: ['clarify', 'state'],
  },
  {
    word: 'amateur',
    definition: 'not a professional',
    synonyms: ['non-pro', 'beginner'],
    antonyms: ['professional', 'expert'],
  },
  {
    word: 'termination',
    definition: 'end of something',
    synonyms: ['end', 'conclusion'],
    antonyms: ['start', 'beginning'],
  },
];
