export const wordBankPart2 = [
  {
    word: 'denounce',
    definition: 'to speak out against something',
    synonyms: ['condemn', 'criticise'],
    antonyms: ['praise', 'approve'],
  },
  {
    word: 'pillage',
    definition: 'to steal things by force during war',
    synonyms: ['plunder', 'loot'],
    antonyms: ['guard', 'protect'],
  },
  {
    word: 'euphoria',
    definition: 'a feeling of extreme happiness',
    synonyms: ['joy', 'elation'],
    antonyms: ['sadness', 'despair'],
  },
  {
    word: 'substantiate',
    definition: 'to show something is true with proof',
    synonyms: ['prove', 'confirm'],
    antonyms: ['disprove', 'deny'],
  },
  {
    word: 'reverence',
    definition: 'deep respect',
    synonyms: ['respect', 'awe'],
    antonyms: ['disrespect', 'scorn'],
  },
  {
    word: 'despicable',
    definition: 'very bad and nasty',
    synonyms: ['vile', 'hateful'],
    antonyms: ['admirable', 'noble'],
  },
  {
    word: 'noteworthy',
    definition: 'worth noticing or important',
    synonyms: ['remarkable', 'notable'],
    antonyms: ['ordinary', 'trivial'],
  },
  {
    word: 'thrilled',
    definition: 'very excited and happy',
    synonyms: ['excited', 'delighted'],
    antonyms: ['bored', 'uninterested'],
  },
  {
    word: 'adopt',
    definition: 'to take something as your own',
    synonyms: ['take', 'embrace'],
    antonyms: ['reject', 'abandon'],
  },
  {
    word: 'anarchist',
    definition: 'someone who thinks we should have no government',
    synonyms: ['rebel', 'radical'],
    antonyms: ['loyalist', 'conformist'],
  },
  {
    word: 'inaugurate',
    definition: 'to officially start or open',
    synonyms: ['launch', 'commence'],
    antonyms: ['end', 'conclude'],
  },
  {
    word: 'aversion',
    definition: 'a strong dislike',
    synonyms: ['dislike', 'hatred'],
    antonyms: ['liking', 'affection'],
  },
  {
    word: 'quarantine',
    definition: 'keeping someone apart to stop disease spreading',
    synonyms: ['isolate', 'seclude'],
    antonyms: ['integrate', 'mingle'],
  },
  {
    word: 'languish',
    definition: 'to get weak and fail to improve',
    synonyms: ['weaken', 'wilt'],
    antonyms: ['flourish', 'thrive'],
  },
  {
    word: 'glib',
    definition: 'speaking smoothly but without real thought',
    synonyms: ['slick', 'smooth'],
    antonyms: ['sincere', 'thoughtful'],
  },
  {
    word: 'imperious',
    definition: 'bossy and expecting to be obeyed',
    synonyms: ['bossy', 'overbearing'],
    antonyms: ['meek', 'humble'],
  },
  {
    word: 'persona',
    definition: 'the image a person shows to others',
    synonyms: ['image', 'character'],
    antonyms: ['self', 'reality'],
  },
  {
    word: 'conclusive',
    definition: 'proving a point so no doubt is left',
    synonyms: ['decisive', 'final'],
    antonyms: ['inconclusive', 'uncertain'],
  },
  {
    word: 'proliferation',
    definition: 'fast increase in number',
    synonyms: ['growth', 'spread'],
    antonyms: ['decline', 'decrease'],
  },
  {
    word: 'blissful',
    definition: 'full of joy',
    synonyms: ['joyful', 'happy'],
    antonyms: ['miserable', 'unhappy'],
  },
  {
    word: 'paradox',
    definition: 'a statement that seems impossible but may be true',
    synonyms: ['puzzle', 'contradiction'],
    antonyms: ['certainty', 'clarity'],
  },
  {
    word: 'detached',
    definition: 'not joined or not emotionally involved',
    synonyms: ['separate', 'aloof'],
    antonyms: ['attached', 'involved'],
  },
  {
    word: 'accusatory',
    definition: 'saying someone is to blame',
    synonyms: ['blaming', 'critical'],
    antonyms: ['praising', 'absolving'],
  },
  {
    word: 'endeavour',
    definition: 'a serious attempt',
    synonyms: ['attempt', 'strive'],
    antonyms: ['quit', 'neglect'],
  },
  {
    word: 'bewildered',
    definition: 'very confused',
    synonyms: ['confused', 'puzzled'],
    antonyms: ['clear', 'certain'],
  },
  {
    word: 'divulge',
    definition: 'to tell something that was secret',
    synonyms: ['reveal', 'disclose'],
    antonyms: ['conceal', 'hide'],
  },
  {
    word: 'habitat',
    definition: 'the natural home of an animal or plant',
    synonyms: ['home', 'environment'],
    antonyms: ['foreign', 'displacement'],
  },
  {
    word: 'mitigating',
    definition: 'making something less bad',
    synonyms: ['easing', 'lessening'],
    antonyms: ['worsening', 'aggravating'],
  },
  {
    word: 'introvert',
    definition: 'a shy person who likes being alone',
    synonyms: ['shy', 'reserved'],
    antonyms: ['extrovert', 'outgoing'],
  },
  {
    word: 'wilful',
    definition: 'doing something on purpose, often stubbornly',
    synonyms: ['stubborn', 'intentional'],
    antonyms: ['accidental', 'obedient'],
  },
  {
    word: 'facile',
    definition: 'too easy and lacking depth',
    synonyms: ['simple', 'easy'],
    antonyms: ['difficult', 'hard'],
  },
  {
    word: 'usurp',
    definition: 'to take power without right',
    synonyms: ['seize', 'take over'],
    antonyms: ['surrender', 'relinquish'],
  },
  {
    word: 'medley',
    definition: 'a mixture of different things',
    synonyms: ['mixture', 'blend'],
    antonyms: ['single', 'uniform'],
  },
  {
    word: 'assented',
    definition: 'agreed to something',
    synonyms: ['agreed', 'consented'],
    antonyms: ['disagreed', 'opposed'],
  },
  {
    word: 'deterrent',
    definition: 'something that stops people doing a thing',
    synonyms: ['obstacle', 'discouragement'],
    antonyms: ['incentive', 'encouragement'],
  },
  {
    word: 'convict',
    definition: 'to find someone guilty of a crime',
    synonyms: ['prisoner', 'felon'],
    antonyms: ['acquit', 'free'],
  },
  {
    word: 'expel',
    definition: 'to force someone to leave',
    synonyms: ['eject', 'banish'],
    antonyms: ['admit', 'welcome'],
  },
  {
    word: 'plenary',
    definition: 'complete and attended by everyone',
    synonyms: ['complete', 'full'],
    antonyms: ['partial', 'limited'],
  },
  {
    word: 'prophetic',
    definition: 'telling what will happen in the future',
    synonyms: ['predictive', 'visionary'],
    antonyms: ['unseeing', 'oblivious'],
  },
  {
    word: 'formidable',
    definition: 'very strong and hard to defeat',
    synonyms: ['intimidating', 'powerful'],
    antonyms: ['weak', 'feeble'],
  },
  {
    word: 'plagiarise',
    definition: "to copy someone else's work and pretend it's yours",
    synonyms: ['copy', 'steal'],
    antonyms: ['originate', 'create'],
  },
  {
    word: 'disdain',
    definition: 'a feeling that something is not worthy',
    synonyms: ['scorn', 'contempt'],
    antonyms: ['respect', 'admiration'],
  },
  {
    word: 'separate',
    definition: 'to split apart',
    synonyms: ['divide', 'split'],
    antonyms: ['join', 'connect'],
  },
  {
    word: 'inhale',
    definition: 'to breathe in',
    synonyms: ['breathe in', 'suck'],
    antonyms: ['exhale', 'breathe out'],
  },
  {
    word: 'earnest',
    definition: 'serious and sincere',
    synonyms: ['serious', 'sincere'],
    antonyms: ['frivolous', 'playful'],
  },
  {
    word: 'scarcity',
    definition: 'not enough of something',
    synonyms: ['shortage', 'lack'],
    antonyms: ['abundance', 'plenty'],
  },
  {
    word: 'atrocious',
    definition: 'extremely bad',
    synonyms: ['awful', 'terrible'],
    antonyms: ['excellent', 'wonderful'],
  },
  {
    word: 'betray',
    definition: 'to be disloyal',
    synonyms: ['deceive', 'double-cross'],
    antonyms: ['support', 'defend'],
  },
  {
    word: 'disturbing',
    definition: 'upsetting or worrying',
    synonyms: ['upsetting', 'troubling'],
    antonyms: ['calming', 'reassuring'],
  },
  {
    word: 'necessary',
    definition: 'needed',
    synonyms: ['essential', 'required'],
    antonyms: ['unnecessary', 'optional'],
  },
  {
    word: 'loneliness',
    definition: 'the state of feeling alone',
    synonyms: ['isolation', 'solitude'],
    antonyms: ['companionship', 'togetherness'],
  },
  {
    word: 'charismatic',
    definition: 'able to attract and charm people easily',
    synonyms: ['charming', 'magnetic'],
    antonyms: ['dull', 'unimpressive'],
  },
  {
    word: 'forge',
    definition: 'to shape metal or create something strong',
    synonyms: ['shape', 'create'],
    antonyms: ['dismantle', 'destroy'],
  },
  {
    word: 'antiquity',
    definition: 'ancient times',
    synonyms: ['ancientness', 'oldness'],
    antonyms: ['modernity', 'newness'],
  },
  {
    word: 'absolution',
    definition: 'forgiveness of wrongdoing',
    synonyms: ['forgiveness', 'pardon'],
    antonyms: ['blame', 'punishment'],
  },
  {
    word: 'prattle',
    definition: 'to talk on and on about silly things',
    synonyms: ['babble', 'chatter'],
    antonyms: ['silence', 'hush'],
  },
  {
    word: 'discontent',
    definition: 'unhappiness with a situation',
    synonyms: ['unhappiness', 'dissatisfaction'],
    antonyms: ['contentment', 'satisfaction'],
  },
  {
    word: 'unnecessary',
    definition: 'not needed',
    synonyms: ['needless', 'extra'],
    antonyms: ['necessary', 'essential'],
  },
  {
    word: 'tyrant',
    definition: 'a cruel ruler',
    synonyms: ['dictator', 'oppressor'],
    antonyms: ['liberator', 'democrat'],
  },
  {
    word: 'pitfall',
    definition: 'a hidden danger',
    synonyms: ['trap', 'danger'],
    antonyms: ['advantage', 'safety'],
  },
  {
    word: 'pacifying',
    definition: 'calming people down',
    synonyms: ['calming', 'soothing'],
    antonyms: ['provoking', 'agitating'],
  },
  {
    word: 'diligence',
    definition: 'working hard and carefully',
    synonyms: ['hard work', 'effort'],
    antonyms: ['laziness', 'idleness'],
  },
  {
    word: 'distasteful',
    definition: 'unpleasant',
    synonyms: ['unpleasant', 'nasty'],
    antonyms: ['pleasant', 'agreeable'],
  },
  {
    word: 'acclaim',
    definition: 'loud praise or applause',
    synonyms: ['praise', 'applause'],
    antonyms: ['criticism', 'booing'],
  },
  {
    word: 'quaint',
    definition: 'charmingly old-fashioned',
    synonyms: ['charming', 'old-fashioned'],
    antonyms: ['modern', 'common'],
  },
  {
    word: 'transient',
    definition: 'lasting a short time',
    synonyms: ['temporary', 'fleeting'],
    antonyms: ['permanent', 'lasting'],
  },
  {
    word: 'bray',
    definition: 'the loud cry of a donkey',
    synonyms: ['bellow', 'honk'],
    antonyms: ['whisper', 'murmur'],
  },
  {
    word: 'phalanx',
    definition: 'a tight group moving together',
    synonyms: ['formation', 'squad'],
    antonyms: ['individual', 'scattering'],
  },
  {
    word: 'unite',
    definition: 'to come together',
    synonyms: ['join', 'combine'],
    antonyms: ['separate', 'divide'],
  },
  {
    word: 'delirious',
    definition: 'being confused due to illness or excitement',
    synonyms: ['crazed', 'incoherent'],
    antonyms: ['rational', 'lucid'],
  },
  {
    word: 'hilarious',
    definition: 'very funny',
    synonyms: ['funny', 'amusing'],
    antonyms: ['boring', 'serious'],
  },
  {
    word: 'chameleon',
    definition: 'a lizard that changes colour; someone who easily changes',
    synonyms: ['adapter', 'shape-shifter'],
    antonyms: ['constant', 'steady'],
  },
  {
    word: 'predilection',
    definition: 'a liking for something',
    synonyms: ['liking', 'preference'],
    antonyms: ['dislike', 'aversion'],
  },
  {
    word: 'discredit',
    definition: "to harm someone's reputation",
    synonyms: ['disgrace', 'disprove'],
    antonyms: ['honour', 'validate'],
  },
  {
    word: 'latter',
    definition: 'the second of two',
    synonyms: ['second', 'last'],
    antonyms: ['former', 'first'],
  },
  {
    word: 'remnants',
    definition: 'small parts left over',
    synonyms: ['leftovers', 'remains'],
    antonyms: ['whole', 'entirety'],
  },
  {
    word: 'moral',
    definition: 'about what is right and wrong',
    synonyms: ['ethical', 'virtuous'],
    antonyms: ['immoral', 'wicked'],
  },
  {
    word: 'laconic',
    definition: 'using very few words',
    synonyms: ['brief', 'terse'],
    antonyms: ['talkative', 'wordy'],
  },
  {
    word: 'tentative',
    definition: 'not certain or fixed',
    synonyms: ['uncertain', 'provisional'],
    antonyms: ['definite', 'certain'],
  },
  {
    word: 'interrupt',
    definition: 'to stop someone speaking or doing something',
    synonyms: ['break', 'stop'],
    antonyms: ['continue', 'resume'],
  },
  {
    word: 'misspent',
    definition: 'used wastefully',
    synonyms: ['wasted', 'squandered'],
    antonyms: ['invested', 'used'],
  },
  {
    word: 'buttress',
    definition: 'a support for a wall or idea',
    synonyms: ['support', 'reinforce'],
    antonyms: ['weaken', 'undermine'],
  },
  {
    word: 'competition',
    definition: 'a contest to see who is best',
    synonyms: ['contest', 'rivalry'],
    antonyms: ['co-operation', 'partnership'],
  },
  {
    word: 'satin',
    definition: 'a smooth, shiny fabric',
    synonyms: ['silk', 'glossy fabric'],
    antonyms: ['rough', 'coarse'],
  },
  {
    word: 'brawn',
    definition: 'physical strength',
    synonyms: ['muscle', 'strength'],
    antonyms: ['weakness', 'frailty'],
  },
  {
    word: 'fastidious',
    definition: 'hard to please',
    synonyms: ['fussy', 'picky'],
    antonyms: ['easy-going', 'careless'],
  },
  {
    word: 'subterranean',
    definition: 'under the ground',
    synonyms: ['underground', 'buried'],
    antonyms: ['surface', 'open'],
  },
  {
    word: 'uncaring',
    definition: 'not showing concern',
    synonyms: ['indifferent', 'cold'],
    antonyms: ['caring', 'compassionate'],
  },
  {
    word: 'erroneous',
    definition: 'wrong',
    synonyms: ['wrong', 'mistaken'],
    antonyms: ['correct', 'accurate'],
  },
  {
    word: 'amorphous',
    definition: 'having no clear shape',
    synonyms: ['shapeless', 'formless'],
    antonyms: ['shaped', 'defined'],
  },
  {
    word: 'equanimity',
    definition: 'calmness under stress',
    synonyms: ['calm', 'composure'],
    antonyms: ['panic', 'anxiety'],
  },
  {
    word: 'tyranny',
    definition: 'cruel rule with absolute power',
    synonyms: ['oppression', 'despotism'],
    antonyms: ['freedom', 'liberty'],
  },
  {
    word: 'resplendent',
    definition: 'bright and beautiful',
    synonyms: ['dazzling', 'splendid'],
    antonyms: ['dull', 'drab'],
  },
  {
    word: 'depraved',
    definition: 'morally bad',
    synonyms: ['wicked', 'corrupt'],
    antonyms: ['moral', 'virtuous'],
  },
  {
    word: 'sanctimonious',
    definition: 'acting morally superior',
    synonyms: ['self-righteous', 'pious'],
    antonyms: ['humble', 'sincere'],
  },
  {
    word: 'conclusion',
    definition: 'the end',
    synonyms: ['ending', 'finish'],
    antonyms: ['beginning', 'start'],
  },
  {
    word: 'isolation',
    definition: 'being apart from others',
    synonyms: ['solitude', 'separation'],
    antonyms: ['company', 'connection'],
  },
  {
    word: 'decree',
    definition: 'an official order',
    synonyms: ['order', 'mandate'],
    antonyms: ['request', 'suggestion'],
  },
  {
    word: 'secular',
    definition: 'not religious',
    synonyms: ['non-religious', 'worldly'],
    antonyms: ['religious', 'sacred'],
  },
  {
    word: 'rectify',
    definition: 'to fix',
    synonyms: ['correct', 'fix'],
    antonyms: ['spoil', 'ruin'],
  },
];
