export const wordBankPart5 = [
  {
    word: 'immaculate',
    definition: 'perfectly clean and without fault',
    synonyms: ['spotless', 'flawless'],
    antonyms: ['dirty', 'imperfect'],
  },
  {
    word: 'compile',
    definition: 'collect things into a list or book',
    synonyms: ['collect', 'gather'],
    antonyms: ['scatter', 'separate'],
  },
  {
    word: 'proportion',
    definition: 'part of a whole compared to the rest',
    synonyms: ['ratio', 'share'],
    antonyms: ['disproportion', 'imbalance'],
  },
  {
    word: 'brief',
    definition: 'lasting only a short time',
    synonyms: ['short', 'concise'],
    antonyms: ['long', 'lengthy'],
  },
  {
    word: 'fatuous',
    definition: 'silly and pointless',
    synonyms: ['silly', 'foolish'],
    antonyms: ['wise', 'sensible'],
  },
  {
    word: 'labyrinth',
    definition: 'a maze of winding paths',
    synonyms: ['maze', 'puzzle'],
    antonyms: ['straightway', 'path'],
  },
  {
    word: 'rationale',
    definition: 'the basic reason for something',
    synonyms: ['reason', 'logic'],
    antonyms: ['irrationality', 'nonsense'],
  },
  {
    word: 'defiance',
    definition: 'open resistance to authority',
    synonyms: ['resistance', 'rebellion'],
    antonyms: ['obedience', 'submission'],
  },
  {
    word: 'vigorously',
    definition: 'with a lot of energy and force',
    synonyms: ['energetically', 'forcefully'],
    antonyms: ['weakly', 'lazily'],
  },
  {
    word: 'impetuous',
    definition: 'acting quickly without thinking',
    synonyms: ['rash', 'hasty'],
    antonyms: ['cautious', 'careful'],
  },
  {
    word: 'vapid',
    definition: 'boring and lifeless',
    synonyms: ['dull', 'boring'],
    antonyms: ['lively', 'exciting'],
  },
  {
    word: 'slang',
    definition: 'informal words used in casual speech',
    synonyms: ['jargon', 'colloquialism'],
    antonyms: ['formal', 'standard'],
  },
  {
    word: 'promote',
    definition: 'help something grow or move forward',
    synonyms: ['encourage', 'advance'],
    antonyms: ['hinder', 'demote'],
  },
  {
    word: 'impassive',
    definition: 'not showing feelings',
    synonyms: ['emotionless', 'calm'],
    antonyms: ['emotional', 'expressive'],
  },
  {
    word: 'insidious',
    definition: 'harmful in a secret way',
    synonyms: ['sneaky', 'treacherous'],
    antonyms: ['open', 'honest'],
  },
  {
    word: 'mute',
    definition: 'unable or unwilling to speak',
    synonyms: ['silent', 'speechless'],
    antonyms: ['talkative', 'vocal'],
  },
  {
    word: 'palpable',
    definition: 'can be touched or easily noticed',
    synonyms: ['tangible', 'obvious'],
    antonyms: ['invisible', 'unclear'],
  },
  {
    word: 'resort',
    definition: 'place people go for rest; or to turn to something',
    synonyms: ['retreat', 'refuge'],
    antonyms: ['avoid', 'shun'],
  },
  {
    word: 'stupidity',
    definition: 'lack of intelligence',
    synonyms: ['foolishness', 'ignorance'],
    antonyms: ['intelligence', 'wisdom'],
  },
  {
    word: 'melancholy',
    definition: 'a deep, gentle sadness',
    synonyms: ['sadness', 'gloom'],
    antonyms: ['joy', 'cheerfulness'],
  },
  {
    word: 'vanished',
    definition: 'disappeared suddenly',
    synonyms: ['disappeared', 'gone'],
    antonyms: ['present', 'existing'],
  },
  {
    word: 'hyperbole',
    definition: 'wild exaggeration',
    synonyms: ['exaggeration', 'overstatement'],
    antonyms: ['understatement', 'reality'],
  },
  {
    word: 'balk',
    definition: 'to stop and refuse to go on',
    synonyms: ['hesitate', 'refuse'],
    antonyms: ['proceed', 'accept'],
  },
  {
    word: 'predecessor',
    definition: 'someone who had the role before',
    synonyms: ['forerunner', 'ancestor'],
    antonyms: ['successor', 'descendant'],
  },
  {
    word: 'inferior',
    definition: 'lower in quality or rank',
    synonyms: ['lower', 'poorer'],
    antonyms: ['superior', 'better'],
  },
  {
    word: 'embroiled',
    definition: 'deeply involved in trouble',
    synonyms: ['involved', 'entangled'],
    antonyms: ['detached', 'free'],
  },
  {
    word: 'disband',
    definition: 'break up and stop existing',
    synonyms: ['dissolve', 'break up'],
    antonyms: ['unite', 'assemble'],
  },
  {
    word: 'pious',
    definition: 'very religious',
    synonyms: ['religious', 'devout'],
    antonyms: ['irreverent', 'impious'],
  },
  {
    word: 'innuendo',
    definition: 'an indirect suggestion, often rude',
    synonyms: ['hint', 'insinuation'],
    antonyms: ['statement', 'declaration'],
  },
  {
    word: 'loathe',
    definition: 'to hate very much',
    synonyms: ['hate', 'detest'],
    antonyms: ['love', 'adore'],
  },
  {
    word: 'brazen',
    definition: 'shamelessly bold',
    synonyms: ['bold', 'shameless'],
    antonyms: ['shy', 'modest'],
  },
  {
    word: 'avoid',
    definition: 'keep away from something',
    synonyms: ['dodge', 'evade'],
    antonyms: ['face', 'confront'],
  },
  {
    word: 'plausible',
    definition: 'believable enough to be true',
    synonyms: ['believable', 'likely'],
    antonyms: ['implausible', 'unlikely'],
  },
  {
    word: 'ambling',
    definition: 'walking in a slow, relaxed way',
    synonyms: ['strolling', 'sauntering'],
    antonyms: ['rushing', 'hurrying'],
  },
  {
    word: 'oppress',
    definition: 'treat people in a cruel way',
    synonyms: ['persecute', 'crush'],
    antonyms: ['liberate', 'free'],
  },
  {
    word: 'quandary',
    definition: 'state of confusion about what to do',
    synonyms: ['dilemma', 'confusion'],
    antonyms: ['certainty', 'solution'],
  },
  {
    word: 'baleful',
    definition: 'threatening harm',
    synonyms: ['harmful', 'threatening'],
    antonyms: ['harmless', 'benevolent'],
  },
  {
    word: 'synonym',
    definition: 'a word with the same meaning',
    synonyms: ['same-meaning', 'equivalent'],
    antonyms: ['antonym', 'opposite'],
  },
  {
    word: 'constraint',
    definition: 'limit that controls what you do',
    synonyms: ['limitation', 'restriction'],
    antonyms: ['freedom', 'liberty'],
  },
  {
    word: 'insane',
    definition: 'seriously mentally ill; crazy',
    synonyms: ['crazy', 'mad'],
    antonyms: ['sane', 'rational'],
  },
  {
    word: 'doubtful',
    definition: 'not sure or certain',
    synonyms: ['uncertain', 'unsure'],
    antonyms: ['certain', 'confident'],
  },
  {
    word: 'veil',
    definition: 'cover that hides something',
    synonyms: ['cover', 'hide'],
    antonyms: ['reveal', 'uncover'],
  },
  {
    word: 'insistent',
    definition: 'demanding something firmly',
    synonyms: ['persistent', 'determined'],
    antonyms: ['yielding', 'hesitant'],
  },
  {
    word: 'conceal',
    definition: 'keep something secret',
    synonyms: ['hide', 'cover'],
    antonyms: ['reveal', 'expose'],
  },
  {
    word: 'approve',
    definition: 'think something is good',
    synonyms: ['accept', 'agree'],
    antonyms: ['reject', 'disapprove'],
  },
  {
    word: 'viable',
    definition: 'able to work or succeed',
    synonyms: ['workable', 'possible'],
    antonyms: ['impossible', 'impractical'],
  },
  {
    word: 'prudent',
    definition: 'showing good judgment and care',
    synonyms: ['wise', 'sensible'],
    antonyms: ['foolish', 'reckless'],
  },
  {
    word: 'vanguard',
    definition: 'people leading the way forward',
    synonyms: ['forefront', 'lead'],
    antonyms: ['rear', 'followers'],
  },
  {
    word: 'imperative',
    definition: 'absolutely necessary',
    synonyms: ['essential', 'urgent'],
    antonyms: ['optional', 'trivial'],
  },
  {
    word: 'digest',
    definition: 'break down food; or a short summary',
    synonyms: ['break down', 'absorb'],
    antonyms: ['reject', 'discard'],
  },
  {
    word: 'nimble',
    definition: 'quick and light in movement',
    synonyms: ['agile', 'quick'],
    antonyms: ['clumsy', 'slow'],
  },
  {
    word: 'respite',
    definition: 'short period of rest',
    synonyms: ['break', 'pause'],
    antonyms: ['continuation', 'burden'],
  },
  {
    word: 'terminate',
    definition: 'bring to an end',
    synonyms: ['end', 'finish'],
    antonyms: ['start', 'begin'],
  },
  {
    word: 'customary',
    definition: 'usual and expected',
    synonyms: ['usual', 'traditional'],
    antonyms: ['unusual', 'rare'],
  },
  {
    word: 'moderate',
    definition: 'not extreme; average',
    synonyms: ['average', 'temperate'],
    antonyms: ['extreme', 'excessive'],
  },
  {
    word: 'astute',
    definition: 'clever and able to understand quickly',
    synonyms: ['clever', 'shrewd'],
    antonyms: ['stupid', 'naive'],
  },
  {
    word: 'inclusive',
    definition: 'including everyone',
    synonyms: ['comprehensive', 'all-encompassing'],
    antonyms: ['exclusive', 'limited'],
  },
  {
    word: 'poignancy',
    definition: 'deep emotional feeling',
    synonyms: ['emotion', 'pathos'],
    antonyms: ['dullness', 'indifference'],
  },
  {
    word: 'pleasing',
    definition: 'giving enjoyment',
    synonyms: ['agreeable', 'enjoyable'],
    antonyms: ['unpleasant', 'annoying'],
  },
  {
    word: 'benefit',
    definition: 'something good you get',
    synonyms: ['advantage', 'gain'],
    antonyms: ['drawback', 'harm'],
  },
  {
    word: 'dissipate',
    definition: 'scatter until gone',
    synonyms: ['scatter', 'disperse'],
    antonyms: ['gather', 'concentrate'],
  },
  {
    word: 'delineate',
    definition: 'describe or draw in detail',
    synonyms: ['describe', 'outline'],
    antonyms: ['confuse', 'distort'],
  },
  {
    word: 'repelled',
    definition: 'pushed away strongly',
    synonyms: ['deterred', 'pushed'],
    antonyms: ['attracted', 'welcomed'],
  },
  {
    word: 'debate',
    definition: 'formal discussion with opposite views',
    synonyms: ['argue', 'discuss'],
    antonyms: ['agree', 'concur'],
  },
  {
    word: 'prejudiced',
    definition: 'having an unfair dislike',
    synonyms: ['biased', 'intolerant'],
    antonyms: ['fair', 'unbiased'],
  },
  {
    word: 'inedible',
    definition: 'not safe to eat',
    synonyms: ['uneatable', 'poisonous'],
    antonyms: ['edible', 'tasty'],
  },
  {
    word: 'erasable',
    definition: 'able to be rubbed out',
    synonyms: ['removable', 'wipeable'],
    antonyms: ['permanent', 'indelible'],
  },
  {
    word: 'proverb',
    definition: 'short wise saying',
    synonyms: ['saying', 'maxim'],
    antonyms: ['nonsense', 'novelty'],
  },
  {
    word: 'impudence',
    definition: 'rude bold behavior',
    synonyms: ['rudeness', 'cheek'],
    antonyms: ['respect', 'politeness'],
  },
  {
    word: 'prodigal',
    definition: 'spending money wastefully',
    synonyms: ['wasteful', 'extravagant'],
    antonyms: ['thrifty', 'frugal'],
  },
  {
    word: 'ravenous',
    definition: 'extremely hungry',
    synonyms: ['starving', 'hungry'],
    antonyms: ['full', 'satisfied'],
  },
  {
    word: 'interrogate',
    definition: 'ask many questions',
    synonyms: ['question', 'grill'],
    antonyms: ['answer', 'reply'],
  },
  {
    word: 'elusive',
    definition: 'hard to catch or pin down',
    synonyms: ['slippery', 'hard-to-find'],
    antonyms: ['obvious', 'clear'],
  },
  {
    word: 'garment',
    definition: 'piece of clothing',
    synonyms: ['clothing', 'attire'],
    antonyms: ['undress', 'nakedness'],
  },
  {
    word: 'labour',
    definition: 'hard physical work',
    synonyms: ['work', 'toil'],
    antonyms: ['rest', 'leisure'],
  },
  {
    word: 'philosophical',
    definition: 'thinking deeply about life',
    synonyms: ['thoughtful', 'reflective'],
    antonyms: ['shallow', 'thoughtless'],
  },
  {
    word: 'extrovert',
    definition: 'person who enjoys being with others',
    synonyms: ['outgoing', 'sociable'],
    antonyms: ['introvert', 'shy'],
  },
  {
    word: 'ineffectual',
    definition: 'not producing the result',
    synonyms: ['useless', 'weak'],
    antonyms: ['effective', 'strong'],
  },
  {
    word: 'luminous',
    definition: 'giving off light',
    synonyms: ['glowing', 'bright'],
    antonyms: ['dark', 'dull'],
  },
  {
    word: 'chronicle',
    definition: 'record of events in order',
    synonyms: ['record', 'history'],
    antonyms: ['forget', 'erase'],
  },
  {
    word: 'intuition',
    definition: 'knowing without reasoning',
    synonyms: ['instinct', 'insight'],
    antonyms: ['logic', 'reason'],
  },
  {
    word: 'attribute',
    definition: 'a quality someone has',
    synonyms: ['quality', 'trait'],
    antonyms: ['fault', 'separate'],
  },
  {
    word: 'femininity',
    definition: 'qualities of being female',
    synonyms: ['womanliness', 'grace'],
    antonyms: ['masculinity', 'manliness'],
  },
  {
    word: 'cavorting',
    definition: 'jumping or dancing around playfully',
    synonyms: ['frolicking', 'capering'],
    antonyms: ['still', 'resting'],
  },
  {
    word: 'scripture',
    definition: 'holy writings',
    synonyms: ['holy text', 'bible'],
    antonyms: ['secular text', 'non-religion'],
  },
  {
    word: 'delectable',
    definition: 'very delicious',
    synonyms: ['delicious', 'tasty'],
    antonyms: ['disgusting', 'awful'],
  },
  {
    word: 'dull',
    definition: 'not interesting or not sharp',
    synonyms: ['boring', 'blunt'],
    antonyms: ['exciting', 'sharp'],
  },
  {
    word: 'nuance',
    definition: 'small difference in meaning',
    synonyms: ['subtlety', 'shade'],
    antonyms: ['bluntness', 'obviousness'],
  },
  {
    word: 'austere',
    definition: 'simple and without decoration',
    synonyms: ['plain', 'strict'],
    antonyms: ['lavish', 'ornate'],
  },
  {
    word: 'haughtiness',
    definition: 'arrogant pride',
    synonyms: ['arrogance', 'pride'],
    antonyms: ['humility', 'modesty'],
  },
  {
    word: 'degenerate',
    definition: 'become worse in quality',
    synonyms: ['deteriorate', 'worsen'],
    antonyms: ['improve', 'develop'],
  },
  {
    word: 'boon',
    definition: 'something helpful',
    synonyms: ['blessing', 'benefit'],
    antonyms: ['curse', 'bane'],
  },
  {
    word: 'conserve',
    definition: 'protect from being wasted',
    synonyms: ['preserve', 'save'],
    antonyms: ['waste', 'squander'],
  },
  {
    word: 'flagrant',
    definition: 'very obvious and bad',
    synonyms: ['blatant', 'obvious'],
    antonyms: ['hidden', 'subtle'],
  },
  {
    word: 'heinous',
    definition: 'extremely wicked',
    synonyms: ['wicked', 'evil'],
    antonyms: ['good', 'noble'],
  },
  {
    word: 'ominous',
    definition: 'giving a feeling that something bad will happen',
    synonyms: ['threatening', 'foreboding'],
    antonyms: ['promising', 'hopeful'],
  },
  {
    word: 'bereft',
    definition: 'sadly lacking something',
    synonyms: ['deprived', 'lacking'],
    antonyms: ['full', 'endowed'],
  },
  {
    word: 'altercation',
    definition: 'noisy argument',
    synonyms: ['quarrel', 'argument'],
    antonyms: ['agreement', 'harmony'],
  },
  {
    word: 'gloomy',
    definition: 'dark or sadly serious',
    synonyms: ['dark', 'sad'],
    antonyms: ['bright', 'cheerful'],
  },
  {
    word: 'kindle',
    definition: 'start a fire or feeling',
    synonyms: ['ignite', 'light'],
    antonyms: ['extinguish', 'douse'],
  },
  {
    word: 'guttural',
    definition: 'harsh and throaty',
    synonyms: ['throaty', 'harsh'],
    antonyms: ['clear', 'melodic'],
  },
  {
    word: 'shrink',
    definition: 'become smaller',
    synonyms: ['contract', 'reduce'],
    antonyms: ['grow', 'expand'],
  },
  {
    word: 'dutiful',
    definition: 'doing what you should',
    synonyms: ['obedient', 'responsible'],
    antonyms: ['negligent', 'disobedient'],
  },
  {
    word: 'surmount',
    definition: 'overcome a problem',
    synonyms: ['overcome', 'conquer'],
    antonyms: ['fail', 'succumb'],
  },
  {
    word: 'quench',
    definition: 'stop thirst or fire',
    synonyms: ['extinguish', 'satisfy'],
    antonyms: ['ignite', 'thirst'],
  },
  {
    word: 'phenomena',
    definition: 'remarkable events or facts',
    synonyms: ['events', 'occurrences'],
    antonyms: ['normality', 'ordinary'],
  },
  {
    word: 'covet',
    definition: 'strongly wish for',
    synonyms: ['desire', 'crave'],
    antonyms: ['spurn', 'dislike'],
  },
  {
    word: 'rant',
    definition: 'talk loudly and angrily',
    synonyms: ['rave', 'tirade'],
    antonyms: ['praise', 'calm'],
  },
  {
    word: 'sombre',
    definition: 'serious and dark',
    synonyms: ['gloomy', 'dark'],
    antonyms: ['bright', 'cheerful'],
  },
  {
    word: 'disarray',
    definition: 'state of untidiness',
    synonyms: ['mess', 'disorder'],
    antonyms: ['order', 'tidiness'],
  },
  {
    word: 'conclude',
    definition: 'finish or decide',
    synonyms: ['finish', 'decide'],
    antonyms: ['begin', 'start'],
  },
  {
    word: 'grievance',
    definition: 'a reason to complain',
    synonyms: ['complaint', 'injustice'],
    antonyms: ['praise', 'contentment'],
  },
  {
    word: 'apathetic',
    definition: 'showing no interest',
    synonyms: ['indifferent', 'uncaring'],
    antonyms: ['passionate', 'interested'],
  },
  {
    word: 'measly',
    definition: 'very small or poor',
    synonyms: ['tiny', 'paltry'],
    antonyms: ['large', 'generous'],
  },
  {
    word: 'ignorant',
    definition: 'lacking knowledge',
    synonyms: ['unaware', 'uneducated'],
    antonyms: ['knowledgeable', 'informed'],
  },
  {
    word: 'subordinate',
    definition: 'lower in rank',
    synonyms: ['lower', 'secondary'],
    antonyms: ['superior', 'chief'],
  },
  {
    word: 'demure',
    definition: 'quiet and modest',
    synonyms: ['shy', 'modest'],
    antonyms: ['bold', 'brazen'],
  },
  {
    word: 'distinct',
    definition: 'clearly different',
    synonyms: ['clear', 'separate'],
    antonyms: ['vague', 'similar'],
  },
  {
    word: 'condone',
    definition: 'accept or allow bad behavior',
    synonyms: ['allow', 'overlook'],
    antonyms: ['condemn', 'forbid'],
  },
  {
    word: 'receive',
    definition: 'get something',
    synonyms: ['get', 'accept'],
    antonyms: ['give', 'send'],
  },
  {
    word: 'jovial',
    definition: 'full of fun and happiness',
    synonyms: ['cheerful', 'jolly'],
    antonyms: ['gloomy', 'miserable'],
  },
  {
    word: 'extraordinary',
    definition: 'very unusual or amazing',
    synonyms: ['remarkable', 'amazing'],
    antonyms: ['ordinary', 'common'],
  },
  {
    word: 'commence',
    definition: 'begin',
    synonyms: ['begin', 'start'],
    antonyms: ['end', 'finish'],
  },
  {
    word: 'ineffable',
    definition: 'too great to describe',
    synonyms: ['indescribable', 'inexpressible'],
    antonyms: ['describable', 'expressible'],
  },
  {
    word: 'foremost',
    definition: 'most important',
    synonyms: ['leading', 'top'],
    antonyms: ['last', 'minor'],
  },
  {
    word: 'irreverent',
    definition: 'showing lack of respect',
    synonyms: ['disrespectful', 'rude'],
    antonyms: ['respectful', 'reverent'],
  },
  {
    word: 'aghast',
    definition: 'shocked and upset',
    synonyms: ['horrified', 'shocked'],
    antonyms: ['calm', 'unperturbed'],
  },
  {
    word: 'duress',
    definition: 'threats that force someone to act',
    synonyms: ['pressure', 'coercion'],
    antonyms: ['freedom', 'ease'],
  },
  {
    word: 'despair',
    definition: 'total loss of hope',
    synonyms: ['hopelessness', 'misery'],
    antonyms: ['hope', 'optimism'],
  },
  {
    word: 'stingy',
    definition: 'unwilling to share or spend',
    synonyms: ['mean', 'miserly'],
    antonyms: ['generous', 'lavish'],
  },
  {
    word: 'affluent',
    definition: 'having plenty of money',
    synonyms: ['wealthy', 'rich'],
    antonyms: ['poor', 'needy'],
  },
  {
    word: 'comical',
    definition: 'funny in a silly way',
    synonyms: ['funny', 'amusing'],
    antonyms: ['serious', 'grave'],
  },
  {
    word: 'perchance',
    definition: 'perhaps; maybe',
    synonyms: ['perhaps', 'maybe'],
    antonyms: ['definitely', 'surely'],
  },
  {
    word: 'charming',
    definition: 'very pleasing and attractive',
    synonyms: ['delightful', 'pleasant'],
    antonyms: ['unpleasant', 'boring'],
  },
  {
    word: 'scholastic',
    definition: 'relating to education or schools',
    synonyms: ['academic', 'educational'],
    antonyms: ['nonacademic', 'practical'],
  },
  {
    word: 'limit',
    definition: 'the point beyond which you cannot go',
    synonyms: ['boundary', 'maximum'],
    antonyms: ['freedom', 'infinity'],
  },
  {
    word: 'worthy',
    definition: 'deserving respect',
    synonyms: ['deserving', 'admirable'],
    antonyms: ['unworthy', 'undeserving'],
  },
  {
    word: 'subtropical',
    definition: 'relating to warm regions just outside the tropics',
    synonyms: ['warm', 'semi-tropical'],
    antonyms: ['arctic', 'frigid'],
  },
  {
    word: 'epoch',
    definition: 'long period of time in history',
    synonyms: ['era', 'age'],
    antonyms: ['moment', 'instant'],
  },
  {
    word: 'insolent',
    definition: 'rude and disrespectful',
    synonyms: ['rude', 'disrespectful'],
    antonyms: ['polite', 'respectful'],
  },
  {
    word: 'intermittent',
    definition: 'starting and stopping again',
    synonyms: ['sporadic', 'occasional'],
    antonyms: ['constant', 'continuous'],
  },
  {
    word: 'curate',
    definition: 'select and organise items',
    synonyms: ['organise', 'arrange'],
    antonyms: ['scatter', 'neglect'],
  },
  {
    word: 'covert',
    definition: 'hidden and secret',
    synonyms: ['secret', 'hidden'],
    antonyms: ['overt', 'open'],
  },
  {
    word: 'melodious',
    definition: 'having a pleasant tune',
    synonyms: ['tuneful', 'musical'],
    antonyms: ['discordant', 'harsh'],
  },
  {
    word: 'eclipse',
    definition: 'darken or block light; outshine',
    synonyms: ['overshadow', 'darken'],
    antonyms: ['reveal', 'illuminate'],
  },
  {
    word: 'coy',
    definition: 'shy in a playful way',
    synonyms: ['shy', 'bashful'],
    antonyms: ['bold', 'forward'],
  },
  {
    word: 'palaeontologist',
    definition: 'scientist who studies fossils',
    synonyms: ['fossil expert', 'dinosaur scientist'],
    antonyms: ['amateur', 'novice'],
  },
  {
    word: 'scanty',
    definition: 'too small in amount',
    synonyms: ['scarce', 'meagre'],
    antonyms: ['plentiful', 'abundant'],
  },
  {
    word: 'solicit',
    definition: 'ask for politely',
    synonyms: ['ask', 'request'],
    antonyms: ['refuse', 'reject'],
  },
  {
    word: 'dismal',
    definition: 'very gloomy and sad',
    synonyms: ['gloomy', 'miserable'],
    antonyms: ['cheerful', 'bright'],
  },
  {
    word: 'intact',
    definition: 'whole and not damaged',
    synonyms: ['whole', 'undamaged'],
    antonyms: ['broken', 'damaged'],
  },
  {
    word: 'disappear',
    definition: 'cease to be seen',
    synonyms: ['vanish', 'fade'],
    antonyms: ['appear', 'emerge'],
  },
  {
    word: 'derivative',
    definition: 'not original; copied',
    synonyms: ['copied', 'unoriginal'],
    antonyms: ['original', 'inventive'],
  },
  {
    word: 'assuage',
    definition: 'make something less painful',
    synonyms: ['ease', 'soothe'],
    antonyms: ['worsen', 'aggravate'],
  },
  {
    word: 'irrational',
    definition: 'not logical or reasonable',
    synonyms: ['illogical', 'unreasonable'],
    antonyms: ['rational', 'logical'],
  },
  {
    word: 'crass',
    definition: 'showing no sensitivity',
    synonyms: ['crude', 'insensitive'],
    antonyms: ['refined', 'polite'],
  },
  {
    word: 'tardy',
    definition: 'late',
    synonyms: ['late', 'slow'],
    antonyms: ['early', 'punctual'],
  },
  {
    word: 'tangible',
    definition: 'can be touched',
    synonyms: ['touchable', 'concrete'],
    antonyms: ['intangible', 'abstract'],
  },
  {
    word: 'burgeon',
    definition: 'grow rapidly',
    synonyms: ['grow', 'expand'],
    antonyms: ['shrink', 'decline'],
  },
  {
    word: 'strident',
    definition: 'loud and harsh',
    synonyms: ['harsh', 'loud'],
    antonyms: ['soft', 'gentle'],
  },
  {
    word: 'sober',
    definition: 'serious or not drunk',
    synonyms: ['serious', 'not drunk'],
    antonyms: ['drunk', 'giddy'],
  },
  {
    word: 'humble',
    definition: 'not proud; modest',
    synonyms: ['modest', 'meek'],
    antonyms: ['proud', 'arrogant'],
  },
  {
    word: 'torment',
    definition: 'severe mental or physical pain',
    synonyms: ['torture', 'pain'],
    antonyms: ['comfort', 'soothe'],
  },
  {
    word: 'trivia',
    definition: 'little unimportant facts',
    synonyms: ['minutiae', 'facts'],
    antonyms: ['essentials', 'fundamentals'],
  },
  {
    word: 'plunge',
    definition: 'fall or jump quickly',
    synonyms: ['dive', 'drop'],
    antonyms: ['rise', 'ascend'],
  },
  {
    word: 'enigma',
    definition: 'something that is a mystery',
    synonyms: ['mystery', 'puzzle'],
    antonyms: ['clarity', 'solution'],
  },
  {
    word: 'tenuous',
    definition: 'weak and thin',
    synonyms: ['weak', 'flimsy'],
    antonyms: ['strong', 'sturdy'],
  },
  {
    word: 'insular',
    definition: 'narrow-minded or isolated',
    synonyms: ['isolated', 'narrow'],
    antonyms: ['open', 'cosmopolitan'],
  },
  {
    word: 'joyous',
    definition: 'full of joy',
    synonyms: ['happy', 'joyful'],
    antonyms: ['sad', 'sorrowful'],
  },
  {
    word: 'juxtapose',
    definition: 'place side by side',
    synonyms: ['place beside', 'compare'],
    antonyms: ['separate', 'distance'],
  },
  {
    word: 'contemptible',
    definition: 'deserving dislike',
    synonyms: ['despicable', 'shameful'],
    antonyms: ['admirable', 'respectable'],
  },
  {
    word: 'double',
    definition: 'two of something',
    synonyms: ['twofold', 'twin'],
    antonyms: ['single', 'half'],
  },
  {
    word: 'novelty',
    definition: 'newness or originality',
    synonyms: ['newness', 'innovation'],
    antonyms: ['tradition', 'oldness'],
  },
  {
    word: 'feral',
    definition: 'wild and not tamed',
    synonyms: ['wild', 'untamed'],
    antonyms: ['tame', 'domesticated'],
  },
  {
    word: 'insightful',
    definition: 'showing deep understanding',
    synonyms: ['perceptive', 'shrewd'],
    antonyms: ['shallow', 'dull'],
  },
  {
    word: 'optional',
    definition: 'not required',
    synonyms: ['voluntary', 'elective'],
    antonyms: ['mandatory', 'compulsory'],
  },
  {
    word: 'ordeal',
    definition: 'difficult or painful test',
    synonyms: ['trial', 'hardship'],
    antonyms: ['delight', 'pleasure'],
  },
  {
    word: 'wither',
    definition: 'dry up and shrink',
    synonyms: ['wilt', 'dry'],
    antonyms: ['flourish', 'thrive'],
  },
  {
    word: 'intervene',
    definition: 'come between to help',
    synonyms: ['intercede', 'step in'],
    antonyms: ['ignore', 'withdraw'],
  },
  {
    word: 'parody',
    definition: 'funny copy of something',
    synonyms: ['spoof', 'imitation'],
    antonyms: ['original', 'tribute'],
  },
  {
    word: 'incline',
    definition: 'lean or slope',
    synonyms: ['lean', 'slope'],
    antonyms: ['straighten', 'decline'],
  },
  {
    word: 'transcendent',
    definition: 'far above normal limits',
    synonyms: ['supreme', 'extraordinary'],
    antonyms: ['ordinary', 'mediocre'],
  },
  {
    word: 'woeful',
    definition: 'full of sorrow',
    synonyms: ['sad', 'miserable'],
    antonyms: ['cheerful', 'happy'],
  },
  {
    word: 'obligatory',
    definition: 'must be done',
    synonyms: ['mandatory', 'required'],
    antonyms: ['optional', 'voluntary'],
  },
  {
    word: 'idle',
    definition: 'not active or working',
    synonyms: ['inactive', 'lazy'],
    antonyms: ['busy', 'active'],
  },
  {
    word: 'pining',
    definition: 'longing sadly for',
    synonyms: ['yearning', 'longing'],
    antonyms: ['satisfied', 'content'],
  },
  {
    word: 'residue',
    definition: 'small amount left behind',
    synonyms: ['remainder', 'leftover'],
    antonyms: ['whole', 'entirety'],
  },
  {
    word: 'diffident',
    definition: 'shy and lacking confidence',
    synonyms: ['shy', 'timid'],
    antonyms: ['confident', 'bold'],
  },
  {
    word: 'alienate',
    definition: 'make someone feel left out',
    synonyms: ['isolate', 'estrange'],
    antonyms: ['befriend', 'unite'],
  },
  {
    word: 'epic',
    definition: 'long heroic story',
    synonyms: ['saga', 'heroic tale'],
    antonyms: ['short story', 'skit'],
  },
  {
    word: 'sacred',
    definition: 'holy and greatly respected',
    synonyms: ['holy', 'blessed'],
    antonyms: ['profane', 'secular'],
  },
  {
    word: 'engender',
    definition: 'cause something to happen',
    synonyms: ['create', 'cause'],
    antonyms: ['destroy', 'prevent'],
  },
  {
    word: 'awkward',
    definition: 'clumsy or uncomfortable',
    synonyms: ['clumsy', 'uncomfortable'],
    antonyms: ['graceful', 'easy'],
  },
  {
    word: 'guarantee',
    definition: 'promise something will happen',
    synonyms: ['promise', 'assure'],
    antonyms: ['deny', 'break'],
  },
  {
    word: 'spurious',
    definition: 'not genuine; fake',
    synonyms: ['fake', 'false'],
    antonyms: ['genuine', 'authentic'],
  },
  {
    word: 'intense',
    definition: 'very strong',
    synonyms: ['strong', 'extreme'],
    antonyms: ['mild', 'weak'],
  },
  {
    word: 'feasible',
    definition: 'possible to do',
    synonyms: ['possible', 'doable'],
    antonyms: ['impossible', 'impractical'],
  },
  {
    word: 'comprehend',
    definition: 'understand fully',
    synonyms: ['understand', 'grasp'],
    antonyms: ['misunderstand', 'confuse'],
  },
  {
    word: 'bleats',
    definition: 'cries of a sheep or goat',
    synonyms: ['baas', 'cries'],
    antonyms: ['silence', 'quiet'],
  },
  {
    word: 'chortle',
    definition: 'laugh in a happy way',
    synonyms: ['chuckle', 'laugh'],
    antonyms: ['cry', 'weep'],
  },
];
