export const wordBankPart3 = [
  {
    word: 'serenity',
    definition: 'peace and quiet',
    synonyms: ['peace', 'calm'],
    antonyms: ['chaos', 'turmoil'],
  },
  {
    word: 'artful',
    definition: 'clever or skilful',
    synonyms: ['skilful', 'crafty'],
    antonyms: ['clumsy', 'honest'],
  },
  {
    word: 'tranquillity',
    definition: 'a state of calm',
    synonyms: ['stillness', 'peace'],
    antonyms: ['noise', 'restlessness'],
  },
  {
    word: 'aloof',
    definition: 'distant and not friendly',
    synonyms: ['detached', 'reserved'],
    antonyms: ['friendly', 'warm'],
  },
  {
    word: 'inspiring',
    definition: 'makes you feel eager to do something',
    synonyms: ['motivating', 'encouraging'],
    antonyms: ['dull', 'discouraging'],
  },
  {
    word: 'oxymoron',
    definition: 'two opposite words used together',
    synonyms: ['paradox', 'contradiction'],
    antonyms: ['clarity', 'consistency'],
  },
  {
    word: 'clamour',
    definition: 'loud continuous noise',
    synonyms: ['uproar', 'din'],
    antonyms: ['silence', 'hush'],
  },
  {
    word: 'summit',
    definition: 'the very top of a mountain',
    synonyms: ['peak', 'crest'],
    antonyms: ['base', 'bottom'],
  },
  {
    word: 'protagonist',
    definition: 'the main character in a story',
    synonyms: ['hero', 'lead'],
    antonyms: ['antagonist', 'villain'],
  },
  {
    word: 'contagious',
    definition: 'able to spread from person to person',
    synonyms: ['infectious', 'catching'],
    antonyms: ['non-infectious', 'safe'],
  },

  {
    word: 'exemplary',
    definition: 'very good and worth copying',
    synonyms: ['model', 'admirable'],
    antonyms: ['poor', 'bad'],
  },
  {
    word: 'propriety',
    definition: 'correct social behaviour',
    synonyms: ['decency', 'respectability'],
    antonyms: ['rudeness', 'impropriety'],
  },
  {
    word: 'innovation',
    definition: 'a new idea or invention',
    synonyms: ['invention', 'creation'],
    antonyms: ['tradition', 'imitation'],
  },
  {
    word: 'barren',
    definition: 'not able to produce plants',
    synonyms: ['infertile', 'empty'],
    antonyms: ['fertile', 'lush'],
  },
  {
    word: 'picturesque',
    definition: 'pretty like a picture',
    synonyms: ['scenic', 'beautiful'],
    antonyms: ['ugly', 'drab'],
  },
  {
    word: 'impromptu',
    definition: 'done without planning',
    synonyms: ['unplanned', 'spontaneous'],
    antonyms: ['rehearsed', 'prepared'],
  },
  {
    word: 'category',
    definition: 'a group of similar things',
    synonyms: ['class', 'type'],
    antonyms: ['mix', 'variety'],
  },
  {
    word: 'impermeable',
    definition: 'does not let liquid through',
    synonyms: ['watertight', 'sealed'],
    antonyms: ['porous', 'leaky'],
  },
  {
    word: 'unwitting',
    definition: 'not realising what is happening',
    synonyms: ['unaware', 'accidental'],
    antonyms: ['aware', 'intentional'],
  },
  {
    word: 'ponderous',
    definition: 'slow and heavy',
    synonyms: ['clumsy', 'weighty'],
    antonyms: ['light', 'graceful'],
  },

  {
    word: 'wretched',
    definition: 'extremely unhappy',
    synonyms: ['miserable', 'sad'],
    antonyms: ['happy', 'joyful'],
  },
  {
    word: 'distinguished',
    definition: 'famous and respected',
    synonyms: ['notable', 'eminent'],
    antonyms: ['unknown', 'ordinary'],
  },
  {
    word: 'equipment',
    definition: 'the things you need for a job',
    synonyms: ['gear', 'tools'],
    antonyms: ['lack', 'absence'],
  },
  {
    word: 'effigy',
    definition: 'a model of a person',
    synonyms: ['statue', 'figure'],
    antonyms: ['being', 'person'],
  },
  {
    word: 'wound',
    definition: 'an injury to the body',
    synonyms: ['injury', 'cut'],
    antonyms: ['healing', 'health'],
  },
  {
    word: 'indomitable',
    definition: 'impossible to defeat',
    synonyms: ['unbeatable', 'resilient'],
    antonyms: ['weak', 'vulnerable'],
  },
  {
    word: 'fraudulent',
    definition: 'dishonest and illegal',
    synonyms: ['deceitful', 'fake'],
    antonyms: ['honest', 'genuine'],
  },
  {
    word: 'crestfallen',
    definition: 'sad and disappointed',
    synonyms: ['downcast', 'dejected'],
    antonyms: ['cheerful', 'elated'],
  },
  {
    word: 'peripheral',
    definition: 'at the edge',
    synonyms: ['outer', 'border'],
    antonyms: ['central', 'main'],
  },
  {
    word: 'adulation',
    definition: 'excessive praise',
    synonyms: ['flattery', 'worship'],
    antonyms: ['criticism', 'scorn'],
  },

  {
    word: 'conceivable',
    definition: 'possible to imagine',
    synonyms: ['possible', 'thinkable'],
    antonyms: ['impossible', 'unthinkable'],
  },
  {
    word: 'halt',
    definition: 'to stop',
    synonyms: ['stop', 'pause'],
    antonyms: ['continue', 'proceed'],
  },
  {
    word: 'relish',
    definition: 'to enjoy greatly',
    synonyms: ['enjoy', 'savour'],
    antonyms: ['dislike', 'loathe'],
  },
  {
    word: 'equipped',
    definition: 'having what is needed',
    synonyms: ['supplied', 'armed'],
    antonyms: ['unprepared', 'unequipped'],
  },
  {
    word: 'slovenly',
    definition: 'messy and untidy',
    synonyms: ['untidy', 'scruffy'],
    antonyms: ['neat', 'tidy'],
  },
  {
    word: 'erratic',
    definition: 'not regular or steady',
    synonyms: ['unpredictable', 'uneven'],
    antonyms: ['steady', 'consistent'],
  },
  {
    word: 'seldom',
    definition: 'rarely',
    synonyms: ['rarely', 'hardly'],
    antonyms: ['often', 'frequently'],
  },
  {
    word: 'vilify',
    definition: 'to speak badly of',
    synonyms: ['slander', 'criticise'],
    antonyms: ['praise', 'commend'],
  },
  {
    word: 'repel',
    definition: 'drive something away',
    synonyms: ['drive off', 'push back'],
    antonyms: ['attract', 'welcome'],
  },
  {
    word: 'vulgar',
    definition: 'rude and bad-mannered',
    synonyms: ['rude', 'crude'],
    antonyms: ['polite', 'refined'],
  },

  {
    word: 'frightful',
    definition: 'very scary',
    synonyms: ['terrifying', 'horrible'],
    antonyms: ['pleasant', 'delightful'],
  },
  {
    word: 'duplicity',
    definition: 'double-dealing or trickery',
    synonyms: ['deceit', 'trickery'],
    antonyms: ['honesty', 'truthfulness'],
  },
  {
    word: 'detain',
    definition: 'keep someone from leaving',
    synonyms: ['hold', 'confine'],
    antonyms: ['release', 'free'],
  },
  {
    word: 'trite',
    definition: 'over-used and dull',
    synonyms: ['stale', 'hackneyed'],
    antonyms: ['fresh', 'original'],
  },
  {
    word: 'exuberance',
    definition: 'lively happiness',
    synonyms: ['enthusiasm', 'joy'],
    antonyms: ['gloom', 'sadness'],
  },
  {
    word: 'bargain',
    definition: 'a good deal for little money',
    synonyms: ['deal', 'discount'],
    antonyms: ['rip-off', 'overcharge'],
  },
  {
    word: 'diluted',
    definition: 'made weaker with water',
    synonyms: ['weakened', 'watered-down'],
    antonyms: ['concentrated', 'strong'],
  },
  {
    word: 'agnostic',
    definition: 'unsure if God exists',
    synonyms: ['doubter', 'questioner'],
    antonyms: ['believer', 'certain'],
  },
  {
    word: 'linger',
    definition: 'stay longer than expected',
    synonyms: ['loiter', 'dawdle'],
    antonyms: ['leave', 'depart'],
  },
  {
    word: 'amusing',
    definition: 'funny and entertaining',
    synonyms: ['funny', 'entertaining'],
    antonyms: ['boring', 'dull'],
  },

  {
    word: 'oath',
    definition: 'a formal promise',
    synonyms: ['promise', 'pledge'],
    antonyms: ['lie', 'denial'],
  },
  {
    word: 'emphatic',
    definition: 'said with force',
    synonyms: ['forceful', 'insistent'],
    antonyms: ['weak', 'uncertain'],
  },
  {
    word: 'nonentity',
    definition: 'an unimportant person',
    synonyms: ['nobody', 'unknown'],
    antonyms: ['star', 'celebrity'],
  },
  {
    word: 'busk',
    definition: 'play music in streets for money',
    synonyms: ['street-perform', 'serenade'],
    antonyms: ['ignore', 'silence'],
  },
  {
    word: 'peculiar',
    definition: 'strange',
    synonyms: ['odd', 'weird'],
    antonyms: ['normal', 'usual'],
  },
  {
    word: 'predominantly',
    definition: 'mostly',
    synonyms: ['mainly', 'largely'],
    antonyms: ['barely', 'rarely'],
  },
  {
    word: 'sundry',
    definition: 'various and different',
    synonyms: ['various', 'assorted'],
    antonyms: ['uniform', 'similar'],
  },
  {
    word: 'reticent',
    definition: 'quiet about thoughts',
    synonyms: ['reserved', 'silent'],
    antonyms: ['talkative', 'open'],
  },
  {
    word: 'enigmatic',
    definition: 'mysterious',
    synonyms: ['mysterious', 'puzzling'],
    antonyms: ['clear', 'obvious'],
  },
  {
    word: 'impartial',
    definition: 'fair and not taking sides',
    synonyms: ['fair', 'neutral'],
    antonyms: ['biased', 'partial'],
  },

  {
    word: 'curb',
    definition: 'to control or limit',
    synonyms: ['limit', 'restrain'],
    antonyms: ['encourage', 'boost'],
  },
  {
    word: 'presumptuous',
    definition: 'too bold without permission',
    synonyms: ['arrogant', 'bold'],
    antonyms: ['modest', 'humble'],
  },
  {
    word: 'compel',
    definition: 'force someone to do something',
    synonyms: ['force', 'oblige'],
    antonyms: ['deter', 'prevent'],
  },
  {
    word: 'quiver',
    definition: 'to shake slightly',
    synonyms: ['tremble', 'shiver'],
    antonyms: ['steady', 'still'],
  },
  {
    word: 'estimate',
    definition: 'roughly guess a number',
    synonyms: ['guess', 'approximate'],
    antonyms: ['measure', 'calculate'],
  },
  {
    word: 'exalt',
    definition: 'praise highly',
    synonyms: ['praise', 'glorify'],
    antonyms: ['criticise', 'blame'],
  },
  {
    word: 'officious',
    definition: 'bossy with unwanted help',
    synonyms: ['meddlesome', 'pushy'],
    antonyms: ['hands-off', 'modest'],
  },
  {
    word: 'superfluous',
    definition: 'more than needed',
    synonyms: ['extra', 'unnecessary'],
    antonyms: ['necessary', 'essential'],
  },
  {
    word: 'fortuitous',
    definition: 'happening by chance',
    synonyms: ['lucky', 'accidental'],
    antonyms: ['planned', 'intentional'],
  },
  {
    word: 'stoop',
    definition: 'bend your body forward',
    synonyms: ['bend', 'crouch'],
    antonyms: ['stand', 'straighten'],
  },

  {
    word: 'indifferent',
    definition: 'not caring',
    synonyms: ['uncaring', 'unconcerned'],
    antonyms: ['interested', 'concerned'],
  },
  {
    word: 'complaisant',
    definition: 'willing to please others',
    synonyms: ['accommodating', 'agreeable'],
    antonyms: ['stubborn', 'unco-operative'],
  },
  {
    word: 'tenant',
    definition: 'a person who rents a place',
    synonyms: ['renter', 'occupant'],
    antonyms: ['landlord', 'owner'],
  },
  {
    word: 'homogeneous',
    definition: 'all the same kind',
    synonyms: ['uniform', 'similar'],
    antonyms: ['mixed', 'varied'],
  },
  {
    word: 'forestall',
    definition: 'stop something before it happens',
    synonyms: ['prevent', 'pre-empt'],
    antonyms: ['allow', 'permit'],
  },
  {
    word: 'confound',
    definition: 'confuse and surprise',
    synonyms: ['confuse', 'bewilder'],
    antonyms: ['clarify', 'explain'],
  },
  {
    word: 'turmoil',
    definition: 'great disorder',
    synonyms: ['chaos', 'upheaval'],
    antonyms: ['order', 'calm'],
  },
  {
    word: 'enchanting',
    definition: 'delightfully charming',
    synonyms: ['charming', 'captivating'],
    antonyms: ['repelling', 'boring'],
  },
  {
    word: 'drought',
    definition: 'a long time with no rain',
    synonyms: ['dry spell', 'aridity'],
    antonyms: ['flood', 'deluge'],
  },
  {
    word: 'exhort',
    definition: 'strongly urge',
    synonyms: ['urge', 'encourage'],
    antonyms: ['discourage', 'deter'],
  },

  {
    word: 'mortal',
    definition: 'certain to die',
    synonyms: ['human', 'fatal'],
    antonyms: ['immortal', 'eternal'],
  },
  {
    word: 'desperately',
    definition: 'in a hopeless way',
    synonyms: ['urgently', 'frantically'],
    antonyms: ['calmly', 'casually'],
  },
  {
    word: 'furtively',
    definition: 'secretly and quietly',
    synonyms: ['secretly', 'slyly'],
    antonyms: ['openly', 'open'],
  },
  {
    word: 'inopportune',
    definition: 'happening at a bad time',
    synonyms: ['untimely', 'ill-timed'],
    antonyms: ['timely', 'convenient'],
  },
  {
    word: 'forsake',
    definition: 'leave someone or something',
    synonyms: ['abandon', 'desert'],
    antonyms: ['keep', 'support'],
  },
  {
    word: 'provoke',
    definition: 'cause anger or reaction',
    synonyms: ['anger', 'incite'],
    antonyms: ['calm', 'soothe'],
  },
  {
    word: 'incision',
    definition: 'a cut made by a surgeon',
    synonyms: ['cut', 'slice'],
    antonyms: ['closure', 'seal'],
  },
  {
    word: 'convoluted',
    definition: 'very complicated',
    synonyms: ['complex', 'twisted'],
    antonyms: ['simple', 'straightforward'],
  },
  {
    word: 'tormenting',
    definition: 'causing great pain',
    synonyms: ['torturing', 'harassing'],
    antonyms: ['comforting', 'soothing'],
  },
  {
    word: 'instructive',
    definition: 'giving useful information',
    synonyms: ['educational', 'helpful'],
    antonyms: ['unhelpful', 'misleading'],
  },

  {
    word: 'vacillate',
    definition: 'keep changing your mind',
    synonyms: ['waver', 'hesitate'],
    antonyms: ['decide', 'choose'],
  },
  {
    word: 'ethereal',
    definition: 'delicate and light',
    synonyms: ['airy', 'heavenly'],
    antonyms: ['solid', 'earthly'],
  },
  {
    word: 'unwarranted',
    definition: 'not justified',
    synonyms: ['unjustified', 'unfounded'],
    antonyms: ['justified', 'reasonable'],
  },
  {
    word: 'pedantic',
    definition: 'showing off book-learning',
    synonyms: ['bookish', 'fussy'],
    antonyms: ['casual', 'informal'],
  },
  {
    word: 'concise',
    definition: 'short and clear',
    synonyms: ['brief', 'succinct'],
    antonyms: ['wordy', 'rambling'],
  },
  {
    word: 'credibility',
    definition: 'believability',
    synonyms: ['trustworthiness', 'reliability'],
    antonyms: ['doubt', 'unreliability'],
  },
  {
    word: 'temptation',
    definition: 'desire to do something bad',
    synonyms: ['urge', 'lure'],
    antonyms: ['disinterest', 'repulsion'],
  },
  {
    word: 'coherent',
    definition: 'makes sense',
    synonyms: ['logical', 'clear'],
    antonyms: ['confused', 'illogical'],
  },
  {
    word: 'sarcastic',
    definition: 'using sharp irony',
    synonyms: ['mocking', 'ironic'],
    antonyms: ['sincere', 'earnest'],
  },
  {
    word: 'homophone',
    definition: 'words that sound the same',
    synonyms: ['sound-alike', 'same-sound'],
    antonyms: ['homograph', 'different sound'],
  },

  {
    word: 'comforting',
    definition: 'making someone feel better',
    synonyms: ['soothing', 'reassuring'],
    antonyms: ['upsetting', 'disturbing'],
  },
  {
    word: 'opportunity',
    definition: 'a good chance to do something',
    synonyms: ['chance', 'opening'],
    antonyms: ['obstacle', 'blockage'],
  },
  {
    word: 'vitriolic',
    definition: 'filled with bitter anger',
    synonyms: ['bitter', 'spiteful'],
    antonyms: ['kind', 'pleasant'],
  },
  {
    word: 'liable',
    definition: 'likely to do something',
    synonyms: ['likely', 'prone'],
    antonyms: ['unlikely', 'immune'],
  },
  {
    word: 'eccentric',
    definition: 'odd in an interesting way',
    synonyms: ['quirky', 'odd'],
    antonyms: ['ordinary', 'normal'],
  },
  {
    word: 'inference',
    definition: 'a conclusion from evidence',
    synonyms: ['deduction', 'conclusion'],
    antonyms: ['guess', 'speculation'],
  },
  {
    word: 'spontaneity',
    definition: 'doing things without planning',
    synonyms: ['impulsiveness', 'improvisation'],
    antonyms: ['planning', 'preparation'],
  },
  {
    word: 'auspicious',
    definition: 'showing future success',
    synonyms: ['favourable', 'promising'],
    antonyms: ['unlucky', 'unfavourable'],
  },
  {
    word: 'camaraderie',
    definition: 'friendly team spirit',
    synonyms: ['friendship', 'fellowship'],
    antonyms: ['hostility', 'enmity'],
  },
  {
    word: 'gratuitous',
    definition: 'given without good reason',
    synonyms: ['unnecessary', 'unwanted'],
    antonyms: ['necessary', 'warranted'],
  },

  {
    word: 'desist',
    definition: 'stop doing something',
    synonyms: ['stop', 'cease'],
    antonyms: ['continue', 'persist'],
  },
  {
    word: 'expedite',
    definition: 'speed up a process',
    synonyms: ['speed', 'hurry'],
    antonyms: ['delay', 'slow'],
  },
  {
    word: 'culpable',
    definition: 'guilty of wrongdoing',
    synonyms: ['guilty', 'blameworthy'],
    antonyms: ['innocent', 'blameless'],
  },
  {
    word: 'punitive',
    definition: 'intended to punish',
    synonyms: ['punishing', 'penal'],
    antonyms: ['rewarding', 'lenient'],
  },
  {
    word: 'altruistic',
    definition: 'putting others first',
    synonyms: ['selfless', 'kind'],
    antonyms: ['selfish', 'greedy'],
  },
  {
    word: 'novice',
    definition: 'a beginner',
    synonyms: ['beginner', 'learner'],
    antonyms: ['expert', 'master'],
  },
  {
    word: 'spoonerism',
    definition: 'mixing first sounds of words',
    synonyms: ['slip-tongue', 'word swap'],
    antonyms: ['clear speech', 'articulation'],
  },
  {
    word: 'dissuade',
    definition: 'persuade not to do something',
    synonyms: ['discourage', 'talk out of'],
    antonyms: ['encourage', 'persuade'],
  },
  {
    word: 'ornate',
    definition: 'highly decorated',
    synonyms: ['decorative', 'fancy'],
    antonyms: ['plain', 'simple'],
  },
  {
    word: 'savoury',
    definition: 'salty or spicy (not sweet)',
    synonyms: ['flavoursome', 'tasty'],
    antonyms: ['sweet', 'bland'],
  },

  {
    word: 'doctrine',
    definition: 'set of beliefs',
    synonyms: ['teaching', 'creed'],
    antonyms: ['heresy', 'doubt'],
  },
  {
    word: 'demeanour',
    definition: 'way someone behaves',
    synonyms: ['behaviour', 'manner'],
    antonyms: ['rudeness', 'misconduct'],
  },
  {
    word: 'gung-ho',
    definition: 'very eager and enthusiastic',
    synonyms: ['enthusiastic', 'keen'],
    antonyms: ['cautious', 'careful'],
  },
  {
    word: 'pessimism',
    definition: 'expecting bad things',
    synonyms: ['negativity', 'gloom'],
    antonyms: ['optimism', 'hope'],
  },
  {
    word: 'volatile',
    definition: 'likely to change suddenly',
    synonyms: ['unstable', 'explosive'],
    antonyms: ['stable', 'steady'],
  },
  {
    word: 'naivete',
    definition: 'lack of experience',
    synonyms: ['innocence', 'simplicity'],
    antonyms: ['wisdom', 'scepticism'],
  },
  {
    word: 'desecration',
    definition: 'damaging something sacred',
    synonyms: ['violation', 'defilement'],
    antonyms: ['respect', 'sanctification'],
  },
  {
    word: 'sacrifice',
    definition: 'giving up something for others',
    synonyms: ['offering', 'loss'],
    antonyms: ['gain', 'keep'],
  },
  {
    word: 'cliché',
    definition: 'over-used phrase',
    synonyms: ['platitude', 'banality'],
    antonyms: ['originality', 'freshness'],
  },
  {
    word: 'renegade',
    definition: 'person who deserts a group',
    synonyms: ['rebel', 'traitor'],
    antonyms: ['loyalist', 'supporter'],
  },

  {
    word: 'derelict',
    definition: 'abandoned and run-down',
    synonyms: ['abandoned', 'ramshackle'],
    antonyms: ['cared-for', 'maintained'],
  },
  {
    word: 'ventriloquist',
    definition: 'person who throws their voice',
    synonyms: ['voice-thrower', 'puppeteer'],
    antonyms: ['listener', 'audience'],
  },
  {
    word: 'quarry',
    definition: 'place where stone is dug',
    synonyms: ['pit', 'mine'],
    antonyms: ['mountain', 'hill'],
  },
  {
    word: 'deride',
    definition: 'make fun of',
    synonyms: ['mock', 'ridicule'],
    antonyms: ['praise', 'admire'],
  },
  {
    word: 'indigent',
    definition: 'very poor',
    synonyms: ['poor', 'needy'],
    antonyms: ['rich', 'wealthy'],
  },
  {
    word: 'infernal',
    definition: 'relating to hell',
    synonyms: ['hellish', 'fiendish'],
    antonyms: ['heavenly', 'divine'],
  },
  {
    word: 'subtlety',
    definition: 'fine detail or hint',
    synonyms: ['nuance', 'delicacy'],
    antonyms: ['obviousness', 'bluntness'],
  },
  {
    word: 'resigned',
    definition: 'accepting something unwanted',
    synonyms: ['accepting', 'yielding'],
    antonyms: ['resistant', 'defiant'],
  },
  {
    word: 'malign',
    definition: 'to speak evil of',
    synonyms: ['slander', 'defame'],
    antonyms: ['praise', 'commend'],
  },
  {
    word: 'malady',
    definition: 'illness',
    synonyms: ['illness', 'disease'],
    antonyms: ['health', 'wellness'],
  },

  {
    word: 'precarious',
    definition: 'unsafe and likely to fall',
    synonyms: ['unstable', 'dangerous'],
    antonyms: ['safe', 'secure'],
  },
  {
    word: 'ingrate',
    definition: 'ungrateful person',
    synonyms: ['thankless', 'ungrateful'],
    antonyms: ['appreciator', 'thankful'],
  },
  {
    word: 'quintessential',
    definition: 'perfect example',
    synonyms: ['classic', 'typical'],
    antonyms: ['atypical', 'unusual'],
  },
  {
    word: 'frantic',
    definition: 'wild with fear or worry',
    synonyms: ['panicked', 'wild'],
    antonyms: ['calm', 'relaxed'],
  },
  {
    word: 'consenting',
    definition: 'agreeing to something',
    synonyms: ['agreeing', 'approving'],
    antonyms: ['refusing', 'opposing'],
  },
  {
    word: 'indolent',
    definition: 'lazy',
    synonyms: ['lazy', 'slothful'],
    antonyms: ['hard-working', 'active'],
  },
  {
    word: 'acquire',
    definition: 'get or obtain',
    synonyms: ['get', 'gain'],
    antonyms: ['lose', 'give'],
  },
  {
    word: 'aspire',
    definition: 'hope to achieve',
    synonyms: ['aim', 'strive'],
    antonyms: ['doubt', 'despair'],
  },
  {
    word: 'strut',
    definition: 'walk proudly',
    synonyms: ['swagger', 'parade'],
    antonyms: ['shuffle', 'slouch'],
  },
  {
    word: 'combination',
    definition: 'joining of things',
    synonyms: ['mix', 'blend'],
    antonyms: ['separation', 'division'],
  },

  {
    word: 'artisan',
    definition: 'skilled craft worker',
    synonyms: ['craftsperson', 'maker'],
    antonyms: ['amateur', 'novice'],
  },
  {
    word: 'raiment',
    definition: 'clothing (formal)',
    synonyms: ['clothes', 'garments'],
    antonyms: ['nakedness', 'rags'],
  },
  {
    word: 'wistful',
    definition: 'sadly thoughtful',
    synonyms: ['yearning', 'melancholy'],
    antonyms: ['cheerful', 'content'],
  },
  {
    word: 'invalid',
    definition: 'person too ill to work',
    synonyms: ['patient', 'sufferer'],
    antonyms: ['healthy person', 'athlete'],
  },
  {
    word: 'debunk',
    definition: 'prove something wrong',
    synonyms: ['expose', 'disprove'],
    antonyms: ['confirm', 'prove'],
  },
  {
    word: 'recede',
    definition: 'move back or away',
    synonyms: ['retreat', 'withdraw'],
    antonyms: ['advance', 'approach'],
  },
  {
    word: 'onomatopoeia',
    definition: 'word that sounds like its meaning',
    synonyms: ['sound-word', 'echoic word'],
    antonyms: ['symbol', 'abstract'],
  },
  {
    word: 'develop',
    definition: 'grow or improve',
    synonyms: ['grow', 'evolve'],
    antonyms: ['shrink', 'decline'],
  },
  {
    word: 'perfunctory',
    definition: 'done with little care',
    synonyms: ['careless', 'routine'],
    antonyms: ['careful', 'thorough'],
  },
  {
    word: 'dour',
    definition: 'severe and unfriendly',
    synonyms: ['stern', 'grim'],
    antonyms: ['cheerful', 'friendly'],
  },

  {
    word: 'repercussions',
    definition: 'bad results of an action',
    synonyms: ['consequences', 'results'],
    antonyms: ['benefits', 'rewards'],
  },
  {
    word: 'yearning',
    definition: 'deep longing',
    synonyms: ['longing', 'desire'],
    antonyms: ['satisfaction', 'contentment'],
  },
  {
    word: 'inconspicuous',
    definition: 'not easily seen',
    synonyms: ['hidden', 'unnoticeable'],
    antonyms: ['obvious', 'noticeable'],
  },
  {
    word: 'derision',
    definition: 'mocking laughter',
    synonyms: ['ridicule', 'mockery'],
    antonyms: ['respect', 'approval'],
  },
  {
    word: 'synecdoche',
    definition: 'figure of speech using part for whole',
    synonyms: ['metonymy', 'figure'],
    antonyms: ['literal', 'exact'],
  },
  {
    word: 'hearth',
    definition: 'floor of a fireplace',
    synonyms: ['fireplace', 'fireside'],
    antonyms: ['threshold', 'doorstep'],
  },
  {
    word: 'edible',
    definition: 'safe to eat',
    synonyms: ['eatable', 'safe'],
    antonyms: ['poisonous', 'inedible'],
  },
  {
    word: 'aspiration',
    definition: 'strong desire to achieve',
    synonyms: ['ambition', 'goal'],
    antonyms: ['apathy', 'disinterest'],
  },
  {
    word: 'besieged',
    definition: 'surrounded and attacked',
    synonyms: ['surrounded', 'under attack'],
    antonyms: ['free', 'untroubled'],
  },
  {
    word: 'infatuate',
    definition: 'fill with foolish love',
    synonyms: ['obsess', 'enamor'],
    antonyms: ['repel', 'disenchant'],
  },

  {
    word: 'spurn',
    definition: 'reject with scorn',
    synonyms: ['reject', 'snub'],
    antonyms: ['accept', 'welcome'],
  },
  {
    word: 'platitude',
    definition: 'a dull, over-used remark',
    synonyms: ['cliché', 'truism'],
    antonyms: ['originality', 'insight'],
  },
  {
    word: 'anxious',
    definition: 'worried',
    synonyms: ['worried', 'nervous'],
    antonyms: ['calm', 'relaxed'],
  },
  {
    word: 'garbled',
    definition: 'mixed up and unclear',
    synonyms: ['jumbled', 'confused'],
    antonyms: ['clear', 'coherent'],
  },
  {
    word: 'static',
    definition: 'not moving',
    synonyms: ['still', 'stationary'],
    antonyms: ['moving', 'dynamic'],
  },
  {
    word: 'pledge',
    definition: 'serious promise',
    synonyms: ['promise', 'oath'],
    antonyms: ['break', 'betrayal'],
  },
  {
    word: 'handkerchief',
    definition: 'cloth for wiping face',
    synonyms: ['hanky', 'tissue'],
    antonyms: ['—', '—'],
  },
  {
    word: 'passive',
    definition: 'not acting, only receiving',
    synonyms: ['inactive', 'submissive'],
    antonyms: ['active', 'assertive'],
  },
  {
    word: 'axiom',
    definition: 'statement accepted as true',
    synonyms: ['principle', 'rule'],
    antonyms: ['paradox', 'falsehood'],
  },
  {
    word: 'imbalance',
    definition: 'lack of balance',
    synonyms: ['unevenness', 'disparity'],
    antonyms: ['balance', 'equality'],
  },

  {
    word: 'receptacle',
    definition: 'container for holding things',
    synonyms: ['container', 'holder'],
    antonyms: ['spillage', 'void'],
  },
  {
    word: 'tranquil',
    definition: 'calm and peaceful',
    synonyms: ['peaceful', 'serene'],
    antonyms: ['noisy', 'agitated'],
  },
  {
    word: 'extract',
    definition: 'pull something out',
    synonyms: ['remove', 'pull'],
    antonyms: ['insert', 'embed'],
  },
  {
    word: 'hindrance',
    definition: 'something that blocks progress',
    synonyms: ['obstacle', 'barrier'],
    antonyms: ['help', 'aid'],
  },
  {
    word: 'revere',
    definition: 'deeply respect',
    synonyms: ['respect', 'honour'],
    antonyms: ['despise', 'scorn'],
  },
  {
    word: 'foal',
    definition: 'young horse',
    synonyms: ['colt', 'filly'],
    antonyms: ['horse', 'stallion'],
  },
  {
    word: 'impair',
    definition: 'make something weaker',
    synonyms: ['damage', 'harm'],
    antonyms: ['improve', 'enhance'],
  },
  {
    word: 'mollify',
    definition: 'calm someone down',
    synonyms: ['soothe', 'pacify'],
    antonyms: ['anger', 'enrage'],
  },
  {
    word: 'explicit',
    definition: 'very clear and detailed',
    synonyms: ['clear', 'obvious'],
    antonyms: ['vague', 'implicit'],
  },
  {
    word: 'caricature',
    definition: 'funny exaggerated drawing',
    synonyms: ['cartoon', 'parody'],
    antonyms: ['portrait', 'likeness'],
  },

  {
    word: 'solemnity',
    definition: 'seriousness',
    synonyms: ['seriousness', 'gravity'],
    antonyms: ['levity', 'fun'],
  },
  {
    word: 'derail',
    definition: 'cause a plan to fail',
    synonyms: ['upset', 'ruin'],
    antonyms: ['support', 'advance'],
  },
  {
    word: 'hierarchical',
    definition: 'arranged in levels of rank',
    synonyms: ['ranked', 'graded'],
    antonyms: ['equal', 'flat'],
  },
  {
    word: 'inspire',
    definition: 'fill someone with ideas',
    synonyms: ['motivate', 'encourage'],
    antonyms: ['discourage', 'deter'],
  },
  {
    word: 'debilitate',
    definition: 'make very weak',
    synonyms: ['weaken', 'sap'],
    antonyms: ['strengthen', 'energise'],
  },
  {
    word: 'elated',
    definition: 'extremely happy',
    synonyms: ['overjoyed', 'thrilled'],
    antonyms: ['sad', 'miserable'],
  },
  {
    word: 'outrageous',
    definition: 'shockingly bad or bold',
    synonyms: ['shocking', 'scandalous'],
    antonyms: ['acceptable', 'normal'],
  },
  {
    word: 'residence',
    definition: 'place where someone lives',
    synonyms: ['home', 'dwelling'],
    antonyms: ['office', 'workplace'],
  },
  {
    word: 'lodge',
    definition: 'small house or cabin',
    synonyms: ['cabin', 'hut'],
    antonyms: ['mansion', 'palace'],
  },
  {
    word: 'recount',
    definition: 'tell a story or event',
    synonyms: ['tell', 'describe'],
    antonyms: ['hide', 'conceal'],
  },
];
