export const wordBankPart7 = [
  {
    word: 'diverse',
    definition: 'all different from one another',
    synonyms: ['varied', 'mixed'],
    antonyms: ['similar', 'uniform'],
  },
  {
    word: 'blasphemy',
    definition: 'disrespectful talk about holy things',
    synonyms: ['sacrilege', 'profanity'],
    antonyms: ['reverence', 'praise'],
  },
  {
    word: 'article',
    definition: 'a piece of writing in a newspaper',
    synonyms: ['story', 'report'],
    antonyms: ['silence', 'blank'],
  },
  {
    word: 'interpret',
    definition: 'explain the meaning of something',
    synonyms: ['explain', 'translate'],
    antonyms: ['misunderstand', 'confuse'],
  },
  {
    word: 'declare',
    definition: 'say something firmly and clearly',
    synonyms: ['announce', 'state'],
    antonyms: ['deny', 'hide'],
  },
  {
    word: 'punctual',
    definition: 'on time',
    synonyms: ['prompt', 'timely'],
    antonyms: ['late', 'tardy'],
  },
  {
    word: 'garrulous',
    definition: 'talking too much',
    synonyms: ['chatty', 'talkative'],
    antonyms: ['quiet', 'taciturn'],
  },
  {
    word: 'reprehensible',
    definition: 'deserving blame',
    synonyms: ['shameful', 'bad'],
    antonyms: ['praiseworthy', 'good'],
  },
  {
    word: 'segue',
    definition: 'smooth move from one thing to another',
    synonyms: ['transition', 'link'],
    antonyms: ['halt', 'break'],
  },
  {
    word: 'pugnacious',
    definition: 'ready to fight',
    synonyms: ['aggressive', 'combative'],
    antonyms: ['peaceful', 'gentle'],
  },
  {
    word: 'lair',
    definition: 'an animal’s hiding place',
    synonyms: ['den', 'nest'],
    antonyms: ['open', 'exposure'],
  },
  {
    word: 'fateful',
    definition: 'having a big, often bad, effect',
    synonyms: ['crucial', 'momentous'],
    antonyms: ['trivial', 'minor'],
  },
  {
    word: 'pragmatic',
    definition: 'dealing with things sensibly',
    synonyms: ['practical', 'realistic'],
    antonyms: ['idealistic', 'impractical'],
  },
  {
    word: 'sonnet',
    definition: 'a 14-line poem',
    synonyms: ['poem', 'verse'],
    antonyms: ['prose', 'story'],
  },
  {
    word: 'temper',
    definition: 'state of anger; to make less strong',
    synonyms: ['mood', 'soften'],
    antonyms: ['calm', 'inflame'],
  },
  {
    word: 'justice',
    definition: 'fair treatment',
    synonyms: ['fairness', 'law'],
    antonyms: ['injustice', 'bias'],
  },
  {
    word: 'quite',
    definition: 'to a fairly high degree',
    synonyms: ['fairly', 'rather'],
    antonyms: ['hardly', 'barely'],
  },
  {
    word: 'pronunciation',
    definition: 'the way a word is spoken',
    synonyms: ['speech', 'accent'],
    antonyms: ['mispronunciation', 'silence'],
  },
  {
    word: 'enormity',
    definition: 'hugeness or great seriousness',
    synonyms: ['vastness', 'seriousness'],
    antonyms: ['smallness', 'triviality'],
  },
  {
    word: 'calamity',
    definition: 'a terrible event',
    synonyms: ['disaster', 'catastrophe'],
    antonyms: ['blessing', 'success'],
  },
  {
    word: 'reminiscent',
    definition: 'reminding you of something',
    synonyms: ['evocative', 'suggestive'],
    antonyms: ['forgetful', 'unlike'],
  },
  {
    word: 'bruise',
    definition: 'blue-purple mark from a hit',
    synonyms: ['mark', 'injury'],
    antonyms: ['heal', 'cure'],
  },
  {
    word: 'haughty',
    definition: 'looking down on others',
    synonyms: ['proud', 'arrogant'],
    antonyms: ['humble', 'modest'],
  },
  {
    word: 'infer',
    definition: 'figure out from clues',
    synonyms: ['deduce', 'work out'],
    antonyms: ['guess', 'ignore'],
  },
  {
    word: 'eclectic',
    definition: 'choosing from many sources',
    synonyms: ['varied', 'mixed'],
    antonyms: ['narrow', 'uniform'],
  },
  {
    word: 'egotistical',
    definition: 'thinking too highly of yourself',
    synonyms: ['self-centered', 'vain'],
    antonyms: ['selfless', 'modest'],
  },
  {
    word: 'sycophancy',
    definition: 'flattering someone for gain',
    synonyms: ['flattery', 'fawning'],
    antonyms: ['honesty', 'insult'],
  },
  {
    word: 'amend',
    definition: 'change to make better',
    synonyms: ['fix', 'adjust'],
    antonyms: ['worsen', 'damage'],
  },
  {
    word: 'across',
    definition: 'from one side to the other',
    synonyms: ['over', 'through'],
    antonyms: ['—', '—'],
  },
  {
    word: 'methodical',
    definition: 'done in an orderly way',
    synonyms: ['systematic', 'careful'],
    antonyms: ['chaotic', 'random'],
  },
  {
    word: 'grandeur',
    definition: 'great splendour',
    synonyms: ['magnificence', 'glory'],
    antonyms: ['humbleness', 'plainness'],
  },
  {
    word: 'debrief',
    definition: 'ask questions after a job',
    synonyms: ['question', 'interview'],
    antonyms: ['brief', 'instruct'],
  },
  {
    word: 'bland',
    definition: 'dull and without flavour',
    synonyms: ['plain', 'boring'],
    antonyms: ['tasty', 'exciting'],
  },
  {
    word: 'perceive',
    definition: 'notice or understand',
    synonyms: ['see', 'sense'],
    antonyms: ['miss', 'ignore'],
  },
  {
    word: 'harbour',
    definition: 'hold a thought or shelter boats',
    synonyms: ['keep', 'port'],
    antonyms: ['release', 'expose'],
  },
  {
    word: 'detrimental',
    definition: 'harmful',
    synonyms: ['damaging', 'bad'],
    antonyms: ['beneficial', 'helpful'],
  },
  {
    word: 'amiable',
    definition: 'friendly and pleasant',
    synonyms: ['friendly', 'kind'],
    antonyms: ['unfriendly', 'hostile'],
  },
  {
    word: 'heresy',
    definition: 'belief against common religion',
    synonyms: ['unorthodoxy', 'blasphemy'],
    antonyms: ['orthodoxy', 'belief'],
  },
  {
    word: 'doyen',
    definition: 'most respected older person',
    synonyms: ['senior', 'veteran'],
    antonyms: ['novice', 'newcomer'],
  },
  {
    word: 'demotion',
    definition: 'moving to a lower rank',
    synonyms: ['downgrade', 'reduction'],
    antonyms: ['promotion', 'advance'],
  },
  {
    word: 'potent',
    definition: 'very powerful',
    synonyms: ['strong', 'powerful'],
    antonyms: ['weak', 'feeble'],
  },
  {
    word: 'antiquated',
    definition: 'old-fashioned',
    synonyms: ['outdated', 'old'],
    antonyms: ['modern', 'new'],
  },
  {
    word: 'tweak',
    definition: 'adjust slightly',
    synonyms: ['adjust', 'modify'],
    antonyms: ['damage', 'ruin'],
  },
  {
    word: 'revive',
    definition: 'bring back to life',
    synonyms: ['restore', 'renew'],
    antonyms: ['kill', 'extinguish'],
  },
  {
    word: 'dim',
    definition: 'not bright',
    synonyms: ['faint', 'dull'],
    antonyms: ['bright', 'shiny'],
  },
  {
    word: 'resonant',
    definition: 'deep and echoing',
    synonyms: ['echoing', 'ringing'],
    antonyms: ['flat', 'quiet'],
  },
  {
    word: 'tautology',
    definition: 'saying the same thing twice',
    synonyms: ['repetition', 'redundancy'],
    antonyms: ['brevity', 'conciseness'],
  },
  {
    word: 'replete',
    definition: 'completely full',
    synonyms: ['full', 'stuffed'],
    antonyms: ['empty', 'lacking'],
  },
  {
    word: 'unworthy',
    definition: 'not deserving',
    synonyms: ['undeserving', 'inferior'],
    antonyms: ['worthy', 'deserving'],
  },
  {
    word: 'superiority',
    definition: 'state of being better',
    synonyms: ['dominance', 'advantage'],
    antonyms: ['inferiority', 'weakness'],
  },
  {
    word: 'unrequited',
    definition: 'not returned (about love)',
    synonyms: ['unreturned', 'one-sided'],
    antonyms: ['mutual', 'shared'],
  },
  {
    word: 'immutable',
    definition: 'unchangeable',
    synonyms: ['unchanging', 'fixed'],
    antonyms: ['changeable', 'flexible'],
  },
  {
    word: 'vehicle',
    definition: 'something that carries people or goods',
    synonyms: ['car', 'transport'],
    antonyms: ['—', '—'],
  },
  {
    word: 'dumb',
    definition: 'unable to speak; foolish',
    synonyms: ['silent', 'stupid'],
    antonyms: ['talkative', 'smart'],
  },
  {
    word: 'wholly',
    definition: 'completely',
    synonyms: ['entirely', 'totally'],
    antonyms: ['partly', 'partially'],
  },
  {
    word: 'diatribe',
    definition: 'long angry speech',
    synonyms: ['rant', 'tirade'],
    antonyms: ['praise', 'eulogy'],
  },
  {
    word: 'permit',
    definition: 'allow',
    synonyms: ['allow', 'let'],
    antonyms: ['forbid', 'ban'],
  },
  {
    word: 'prompt',
    definition: 'quick; to remind',
    synonyms: ['quick', 'cue'],
    antonyms: ['slow', 'delay'],
  },
  {
    word: 'effusion',
    definition: 'outpouring of feelings or liquid',
    synonyms: ['outburst', 'rush'],
    antonyms: ['reserve', 'control'],
  },
  {
    word: 'ablest',
    definition: 'most able',
    synonyms: ['best', 'strongest'],
    antonyms: ['weakest', 'poorest'],
  },
  {
    word: 'neat',
    definition: 'tidy and orderly',
    synonyms: ['tidy', 'clean'],
    antonyms: ['messy', 'untidy'],
  },
  {
    word: 'between',
    definition: 'in the space that separates',
    synonyms: ['amid', 'among'],
    antonyms: ['outside', 'beyond'],
  },
  {
    word: 'retract',
    definition: 'take back a statement',
    synonyms: ['withdraw', 'recall'],
    antonyms: ['confirm', 'repeat'],
  },
  {
    word: 'reprieve',
    definition: 'temporary escape from trouble',
    synonyms: ['delay', 'pardon'],
    antonyms: ['punishment', 'sentence'],
  },
  {
    word: 'allay',
    definition: 'to calm or lessen',
    synonyms: ['ease', 'soothe'],
    antonyms: ['aggravate', 'intensify'],
  },
  {
    word: 'cacophony',
    definition: 'loud, harsh mixture of sounds',
    synonyms: ['din', 'racket'],
    antonyms: ['harmony', 'silence'],
  },
  {
    word: 'embrace',
    definition: 'hug or accept gladly',
    synonyms: ['hug', 'accept'],
    antonyms: ['reject', 'refuse'],
  },
  {
    word: 'intercede',
    definition: 'step in to help settle a dispute',
    synonyms: ['mediate', 'intervene'],
    antonyms: ['provoke', 'ignore'],
  },
  {
    word: 'provisional',
    definition: 'temporary',
    synonyms: ['temporary', 'tentative'],
    antonyms: ['permanent', 'final'],
  },
  {
    word: 'insurgent',
    definition: 'rebel against authority',
    synonyms: ['rebel', 'revolutionary'],
    antonyms: ['loyalist', 'supporter'],
  },
  {
    word: 'melee',
    definition: 'confused noisy fight',
    synonyms: ['brawl', 'scrap'],
    antonyms: ['peace', 'order'],
  },
  {
    word: 'exterior',
    definition: 'outside part',
    synonyms: ['outside', 'surface'],
    antonyms: ['interior', 'inside'],
  },
  {
    word: 'community',
    definition: 'group living in one place',
    synonyms: ['society', 'group'],
    antonyms: ['individual', 'isolation'],
  },
  {
    word: 'apathy',
    definition: 'lack of interest or feeling',
    synonyms: ['indifference', 'unconcern'],
    antonyms: ['interest', 'enthusiasm'],
  },
  {
    word: 'extended',
    definition: 'made longer or larger',
    synonyms: ['lengthened', 'long'],
    antonyms: ['short', 'reduced'],
  },
  {
    word: 'infamy',
    definition: 'very bad reputation',
    synonyms: ['notoriety', 'dishonour'],
    antonyms: ['fame', 'honour'],
  },
  {
    word: 'extremely',
    definition: 'very',
    synonyms: ['very', 'highly'],
    antonyms: ['slightly', 'barely'],
  },
  {
    word: 'profligate',
    definition: 'spending wastefully',
    synonyms: ['wasteful', 'extravagant'],
    antonyms: ['thrifty', 'frugal'],
  },
  {
    word: 'turbulence',
    definition: 'violent movement or trouble',
    synonyms: ['disturbance', 'chaos'],
    antonyms: ['calm', 'stillness'],
  },
  {
    word: 'lament',
    definition: 'express sorrow',
    synonyms: ['mourn', 'grieve'],
    antonyms: ['celebrate', 'cheer'],
  },
  {
    word: 'enthusiasm',
    definition: 'eager enjoyment',
    synonyms: ['eagerness', 'zeal'],
    antonyms: ['apathy', 'boredom'],
  },
  {
    word: 'nuisance',
    definition: 'something annoying',
    synonyms: ['annoyance', 'pest'],
    antonyms: ['pleasure', 'help'],
  },
  {
    word: 'benign',
    definition: 'kind or harmless',
    synonyms: ['kind', 'harmless'],
    antonyms: ['harmful', 'malignant'],
  },
  {
    word: 'voracious',
    definition: 'eating or wanting lots',
    synonyms: ['greedy', 'hungry'],
    antonyms: ['satisfied', 'full'],
  },
  {
    word: 'nostalgia',
    definition: 'wish for the past',
    synonyms: ['homesickness', 'longing'],
    antonyms: ['contentment', 'indifference'],
  },
  {
    word: 'wicked',
    definition: 'very evil or bad',
    synonyms: ['evil', 'vile'],
    antonyms: ['good', 'kind'],
  },
  {
    word: 'broad',
    definition: 'wide',
    synonyms: ['wide', 'expansive'],
    antonyms: ['narrow', 'thin'],
  },
  {
    word: 'impudent',
    definition: 'rude and bold',
    synonyms: ['cheeky', 'insolent'],
    antonyms: ['polite', 'respectful'],
  },
  {
    word: 'admirable',
    definition: 'deserving respect',
    synonyms: ['praiseworthy', 'worthy'],
    antonyms: ['shameful', 'bad'],
  },
  {
    word: 'antagonistic',
    definition: 'showing hostility',
    synonyms: ['hostile', 'opposed'],
    antonyms: ['friendly', 'supportive'],
  },
  {
    word: 'seclusion',
    definition: 'state of being alone',
    synonyms: ['isolation', 'privacy'],
    antonyms: ['company', 'public'],
  },
  {
    word: 'resonates',
    definition: 'produces strong feeling or echo',
    synonyms: ['echoes', 'strikes'],
    antonyms: ['dulls', 'muffles'],
  },
  {
    word: 'sincerely',
    definition: 'truly and honestly',
    synonyms: ['truly', 'genuinely'],
    antonyms: ['falsely', 'dishonestly'],
  },
  {
    word: 'sublime',
    definition: 'wonderful and inspiring',
    synonyms: ['glorious', 'magnificent'],
    antonyms: ['awful', 'ordinary'],
  },
  {
    word: 'protract',
    definition: 'lengthen in time',
    synonyms: ['extend', 'lengthen'],
    antonyms: ['shorten', 'cut'],
  },
  {
    word: 'description',
    definition: 'spoken or written details',
    synonyms: ['explanation', 'account'],
    antonyms: ['silence', 'name'],
  },
  {
    word: 'bellicose',
    definition: 'warlike',
    synonyms: ['aggressive', 'hostile'],
    antonyms: ['peaceful', 'friendly'],
  },
  {
    word: 'wholesome',
    definition: 'good for health or morals',
    synonyms: ['healthy', 'pure'],
    antonyms: ['unhealthy', 'harmful'],
  },
  {
    word: 'sleek',
    definition: 'smooth and shiny',
    synonyms: ['smooth', 'glossy'],
    antonyms: ['rough', 'dull'],
  },
  {
    word: 'chaos',
    definition: 'complete disorder',
    synonyms: ['disorder', 'confusion'],
    antonyms: ['order', 'calm'],
  },
  {
    word: 'receptive',
    definition: 'willing to listen',
    synonyms: ['open', 'welcoming'],
    antonyms: ['resistant', 'closed'],
  },
  {
    word: 'subterfuge',
    definition: 'secret trick to hide purpose',
    synonyms: ['deception', 'trick'],
    antonyms: ['honesty', 'truth'],
  },
  {
    word: 'mediocre',
    definition: 'only average',
    synonyms: ['average', 'ordinary'],
    antonyms: ['excellent', 'outstanding'],
  },
  {
    word: 'prestige',
    definition: 'high status',
    synonyms: ['respect', 'reputation'],
    antonyms: ['disgrace', 'lowliness'],
  },
  {
    word: 'steadfast',
    definition: 'firm and loyal',
    synonyms: ['loyal', 'steady'],
    antonyms: ['fickle', 'wavering'],
  },
  {
    word: 'offend',
    definition: 'hurt feelings or break a rule',
    synonyms: ['insult', 'upset'],
    antonyms: ['please', 'delight'],
  },
  {
    word: 'elect',
    definition: 'choose by vote',
    synonyms: ['choose', 'pick'],
    antonyms: ['reject', 'dismiss'],
  },
  {
    word: 'crucial',
    definition: 'very important',
    synonyms: ['vital', 'essential'],
    antonyms: ['minor', 'trivial'],
  },
  {
    word: 'nullify',
    definition: 'make something have no effect',
    synonyms: ['cancel', 'void'],
    antonyms: ['confirm', 'validate'],
  },
  {
    word: 'surreptitious',
    definition: 'done secretly',
    synonyms: ['secret', 'sneaky'],
    antonyms: ['open', 'honest'],
  },
  {
    word: 'sycophant',
    definition: 'person who flatters for gain',
    synonyms: ['flatterer', 'toady'],
    antonyms: ['critic', 'opponent'],
  },
  {
    word: 'caulking',
    definition: 'material that seals gaps',
    synonyms: ['sealant', 'filler'],
    antonyms: ['gap', 'leak'],
  },
  {
    word: 'awry',
    definition: 'out of proper position',
    synonyms: ['askew', 'wrong'],
    antonyms: ['straight', 'aligned'],
  },
  {
    word: 'nauseous',
    definition: 'feeling sick',
    synonyms: ['sick', 'queasy'],
    antonyms: ['well', 'healthy'],
  },
  {
    word: 'metaphor',
    definition: 'comparison saying one thing is another',
    synonyms: ['figure', 'image'],
    antonyms: ['literal', 'fact'],
  },
  {
    word: 'pomposity',
    definition: 'self-important behaviour',
    synonyms: ['arrogance', 'vanity'],
    antonyms: ['humility', 'modesty'],
  },
  {
    word: 'entirely',
    definition: 'completely',
    synonyms: ['totally', 'wholly'],
    antonyms: ['partly', 'somewhat'],
  },
  {
    word: 'hoes',
    definition: 'garden tools for weeding',
    synonyms: ['spades', 'rakes'],
    antonyms: ['—', '—'],
  },
  {
    word: 'passé',
    definition: 'out of date',
    synonyms: ['old-fashioned', 'dated'],
    antonyms: ['modern', 'current'],
  },
  {
    word: 'loathsome',
    definition: 'very disgusting',
    synonyms: ['repulsive', 'hateful'],
    antonyms: ['delightful', 'pleasant'],
  },
  {
    word: 'cajole',
    definition: 'persuade with flattery',
    synonyms: ['coax', 'persuade'],
    antonyms: ['deter', 'discourage'],
  },
  {
    word: 'suspect',
    definition: 'think someone may be guilty',
    synonyms: ['doubt', 'suppose'],
    antonyms: ['trust', 'know'],
  },
  {
    word: 'average',
    definition: 'usual amount or middle value',
    synonyms: ['normal', 'standard'],
    antonyms: ['exceptional', 'extreme'],
  },
  {
    word: 'lethargic',
    definition: 'without energy',
    synonyms: ['sluggish', 'lazy'],
    antonyms: ['energetic', 'lively'],
  },
  {
    word: 'repugnant',
    definition: 'very disgusting',
    synonyms: ['revolting', 'horrid'],
    antonyms: ['pleasant', 'agreeable'],
  },
  {
    word: 'incisive',
    definition: 'clear and sharp',
    synonyms: ['sharp', 'keen'],
    antonyms: ['vague', 'dull'],
  },
  {
    word: 'stretched',
    definition: 'pulled tight',
    synonyms: ['tight', 'extended'],
    antonyms: ['slack', 'loose'],
  },
  {
    word: 'contentious',
    definition: 'likely to cause argument',
    synonyms: ['argumentative', 'quarrelsome'],
    antonyms: ['peaceful', 'agreeable'],
  },
  {
    word: 'choreographer',
    definition: 'person who plans dance moves',
    synonyms: ['dance writer', 'director'],
    antonyms: ['dancer', 'performer'],
  },
  {
    word: 'erect',
    definition: 'build upright',
    synonyms: ['build', 'raise'],
    antonyms: ['demolish', 'flatten'],
  },
  {
    word: 'deject',
    definition: 'make sad',
    synonyms: ['depress', 'sadden'],
    antonyms: ['cheer', 'encourage'],
  },
  {
    word: 'malice',
    definition: 'wish to harm others',
    synonyms: ['spite', 'hatred'],
    antonyms: ['kindness', 'goodwill'],
  },
  {
    word: 'tempestuous',
    definition: 'wild and stormy',
    synonyms: ['stormy', 'turbulent'],
    antonyms: ['calm', 'peaceful'],
  },
  {
    word: 'accolade',
    definition: 'high praise',
    synonyms: ['award', 'honour'],
    antonyms: ['criticism', 'scorn'],
  },
  {
    word: 'appease',
    definition: 'calm someone by giving what they want',
    synonyms: ['pacify', 'soothe'],
    antonyms: ['anger', 'upset'],
  },
  {
    word: 'rigid',
    definition: 'stiff and unbending',
    synonyms: ['stiff', 'firm'],
    antonyms: ['flexible', 'soft'],
  },
  {
    word: 'incense',
    definition: 'make very angry',
    synonyms: ['enrage', 'anger'],
    antonyms: ['calm', 'soothe'],
  },
  {
    word: 'expository',
    definition: 'intended to explain',
    synonyms: ['explanatory', 'informative'],
    antonyms: ['mysterious', 'poetic'],
  },
  {
    word: 'acquiescence',
    definition: 'agreeing without protest',
    synonyms: ['consent', 'compliance'],
    antonyms: ['refusal', 'defiance'],
  },
  {
    word: 'onerous',
    definition: 'very hard to do',
    synonyms: ['burdensome', 'difficult'],
    antonyms: ['easy', 'light'],
  },
  {
    word: 'scrutinise',
    definition: 'look at closely',
    synonyms: ['inspect', 'examine'],
    antonyms: ['skim', 'ignore'],
  },
  {
    word: 'curt',
    definition: 'rudely brief',
    synonyms: ['sharp', 'short'],
    antonyms: ['polite', 'wordy'],
  },
  {
    word: 'contempt',
    definition: 'strong dislike',
    synonyms: ['scorn', 'disdain'],
    antonyms: ['respect', 'admiration'],
  },
  {
    word: 'muted',
    definition: 'quiet or soft',
    synonyms: ['soft', 'subdued'],
    antonyms: ['loud', 'bright'],
  },
  {
    word: 'witty',
    definition: 'cleverly funny',
    synonyms: ['clever', 'humorous'],
    antonyms: ['dull', 'serious'],
  },
  {
    word: 'immoral',
    definition: 'not following accepted rules of right',
    synonyms: ['wrong', 'wicked'],
    antonyms: ['moral', 'good'],
  },
  {
    word: 'narrative',
    definition: 'a story',
    synonyms: ['story', 'tale'],
    antonyms: ['fact', 'statement'],
  },
  {
    word: 'eminent',
    definition: 'famous and respected',
    synonyms: ['famous', 'notable'],
    antonyms: ['unknown', 'ordinary'],
  },
  {
    word: 'subside',
    definition: 'become less strong',
    synonyms: ['ease', 'diminish'],
    antonyms: ['rise', 'increase'],
  },
  {
    word: 'retain',
    definition: 'keep',
    synonyms: ['keep', 'hold'],
    antonyms: ['lose', 'release'],
  },
  {
    word: 'irreproachable',
    definition: 'cannot be criticised',
    synonyms: ['faultless', 'blameless'],
    antonyms: ['guilty', 'flawed'],
  },
  {
    word: 'shrewd',
    definition: 'good at judging situations',
    synonyms: ['clever', 'astute'],
    antonyms: ['naïve', 'foolish'],
  },
  {
    word: 'disparity',
    definition: 'great difference',
    synonyms: ['inequality', 'gap'],
    antonyms: ['equality', 'similarity'],
  },
  {
    word: 'hollow',
    definition: 'empty inside',
    synonyms: ['empty', 'cavity'],
    antonyms: ['solid', 'filled'],
  },
  {
    word: 'grave',
    definition: 'serious; burial place',
    synonyms: ['serious', 'tomb'],
    antonyms: ['light', 'trivial'],
  },
  {
    word: 'trifle',
    definition: 'something of little value',
    synonyms: ['small thing', 'triviality'],
    antonyms: ['importance', 'treasure'],
  },
  {
    word: 'symbolism',
    definition: 'use of symbols to mean ideas',
    synonyms: ['representation', 'signs'],
    antonyms: ['literalness', 'reality'],
  },
  {
    word: 'hedonist',
    definition: 'person who seeks pleasure',
    synonyms: ['pleasure-lover', 'sensualist'],
    antonyms: ['ascetic', 'puritan'],
  },
  {
    word: 'palindrome',
    definition: 'word that reads same backwards',
    synonyms: ['mirror-word', '—'],
    antonyms: ['—', '—'],
  },
  {
    word: 'repulsive',
    definition: 'disgusting',
    synonyms: ['revolting', 'horrid'],
    antonyms: ['attractive', 'pleasant'],
  },
  {
    word: 'sarcasm',
    definition: 'mocking words that mean the opposite',
    synonyms: ['mockery', 'irony'],
    antonyms: ['praise', 'honesty'],
  },
  {
    word: 'hypocritical',
    definition: 'pretending to be better than you are',
    synonyms: ['two-faced', 'false'],
    antonyms: ['sincere', 'honest'],
  },
  {
    word: 'luminary',
    definition: 'famous or bright person',
    synonyms: ['star', 'celebrity'],
    antonyms: ['unknown', 'nobody'],
  },
  {
    word: 'unsurpassed',
    definition: 'better than all others',
    synonyms: ['unequalled', 'best'],
    antonyms: ['ordinary', 'inferior'],
  },
  {
    word: 'inept',
    definition: 'not skilled',
    synonyms: ['clumsy', 'unskilled'],
    antonyms: ['skilled', 'able'],
  },
  {
    word: 'suppress',
    definition: 'put an end to',
    synonyms: ['crush', 'stop'],
    antonyms: ['encourage', 'release'],
  },
  {
    word: 'ultimatum',
    definition: 'final demand',
    synonyms: ['final offer', 'demand'],
    antonyms: ['request', 'plea'],
  },
  {
    word: 'merciless',
    definition: 'showing no pity',
    synonyms: ['cruel', 'pitiless'],
    antonyms: ['kind', 'merciful'],
  },
  {
    word: 'inhabit',
    definition: 'live in a place',
    synonyms: ['live', 'occupy'],
    antonyms: ['leave', 'vacate'],
  },
  {
    word: 'partial',
    definition: 'not complete; biased',
    synonyms: ['unfinished', 'biased'],
    antonyms: ['complete', 'fair'],
  },
  {
    word: 'morose',
    definition: 'gloomy and bad-tempered',
    synonyms: ['sullen', 'glum'],
    antonyms: ['cheerful', 'happy'],
  },
  {
    word: 'tantamount',
    definition: 'equal in effect',
    synonyms: ['equal', 'equivalent'],
    antonyms: ['different', 'opposite'],
  },
  {
    word: 'frugality',
    definition: 'careful with money',
    synonyms: ['thrift', 'economy'],
    antonyms: ['wastefulness', 'spending'],
  },
  {
    word: 'submit',
    definition: 'give in',
    synonyms: ['yield', 'surrender'],
    antonyms: ['resist', 'defy'],
  },
  {
    word: 'swindler',
    definition: 'person who cheats people',
    synonyms: ['cheat', 'con-artist'],
    antonyms: ['honest person', 'helper'],
  },
  {
    word: 'irascible',
    definition: 'easily angered',
    synonyms: ['grumpy', 'hot-tempered'],
    antonyms: ['calm', 'patient'],
  },
  {
    word: 'loquacious',
    definition: 'talking a lot',
    synonyms: ['chatty', 'wordy'],
    antonyms: ['silent', 'quiet'],
  },
  {
    word: 'release',
    definition: 'let go',
    synonyms: ['free', 'liberate'],
    antonyms: ['hold', 'capture'],
  },
  {
    word: 'odour',
    definition: 'smell',
    synonyms: ['smell', 'scent'],
    antonyms: ['fragrance', 'aroma'],
  },
  {
    word: 'restraint',
    definition: 'holding back',
    synonyms: ['control', 'limit'],
    antonyms: ['freedom', 'licence'],
  },
  {
    word: 'ignominy',
    definition: 'public shame',
    synonyms: ['shame', 'disgrace'],
    antonyms: ['honour', 'glory'],
  },
  {
    word: 'challenging',
    definition: 'difficult in a good way',
    synonyms: ['difficult', 'testing'],
    antonyms: ['easy', 'simple'],
  },
  {
    word: 'dishevelled',
    definition: 'untidy in appearance',
    synonyms: ['messy', 'scruffy'],
    antonyms: ['tidy', 'neat'],
  },
  {
    word: 'interfere',
    definition: 'get in the way',
    synonyms: ['meddle', 'intrude'],
    antonyms: ['assist', 'help'],
  },
  {
    word: 'scurrilous',
    definition: 'using nasty language',
    synonyms: ['abusive', 'vitriolic'],
    antonyms: ['polite', 'respectful'],
  },
  {
    word: 'pliant',
    definition: 'easily bent or influenced',
    synonyms: ['flexible', 'yielding'],
    antonyms: ['rigid', 'stubborn'],
  },
  {
    word: 'austerity',
    definition: 'plainness and saving money',
    synonyms: ['simplicity', 'frugality'],
    antonyms: ['luxury', 'extravagance'],
  },
  {
    word: 'virtuous',
    definition: 'morally good',
    synonyms: ['good', 'righteous'],
    antonyms: ['wicked', 'bad'],
  },
  {
    word: 'relinquish',
    definition: 'give up something',
    synonyms: ['surrender', 'yield'],
    antonyms: ['keep', 'retain'],
  },
  {
    word: 'granular',
    definition: 'made of small grains',
    synonyms: ['grainy', 'sandy'],
    antonyms: ['smooth', 'fine'],
  },
  {
    word: 'flora',
    definition: 'plants of a region',
    synonyms: ['plants', 'vegetation'],
    antonyms: ['fauna', 'animals'],
  },
  {
    word: 'suggest',
    definition: 'put an idea forward',
    synonyms: ['propose', 'advise'],
    antonyms: ['withhold', 'demand'],
  },
  {
    word: 'discrepancy',
    definition: 'difference that should match',
    synonyms: ['difference', 'inconsistency'],
    antonyms: ['agreement', 'match'],
  },
  {
    word: 'meander',
    definition: 'wander without real direction',
    synonyms: ['wander', 'ramble'],
    antonyms: ['march', 'direct'],
  },
  {
    word: 'idiosyncrasy',
    definition: 'odd personal habit',
    synonyms: ['quirk', 'peculiarity'],
    antonyms: ['normality', 'usualness'],
  },
  {
    word: 'orthodontist',
    definition: 'dentist who straightens teeth',
    synonyms: ['brace-doctor', 'tooth-specialist'],
    antonyms: ['—', '—'],
  },
  {
    word: 'forthright',
    definition: 'direct and honest',
    synonyms: ['direct', 'straight'],
    antonyms: ['evasive', 'shy'],
  },
  {
    word: 'preclude',
    definition: 'prevent something from happening',
    synonyms: ['prevent', 'stop'],
    antonyms: ['allow', 'permit'],
  },
  {
    word: 'joie',
    definition: "French for joy (as in 'joie de vivre')",
    synonyms: ['joy', 'delight'],
    antonyms: ['sorrow', 'misery'],
  },
  {
    word: 'hinder',
    definition: 'make it hard for someone',
    synonyms: ['hamper', 'block'],
    antonyms: ['help', 'aid'],
  },
  {
    word: 'swallow',
    definition: 'make food pass down throat',
    synonyms: ['gulp', 'ingest'],
    antonyms: ['spit', 'vomit'],
  },
  {
    word: 'partisan',
    definition: 'strong supporter of one side',
    synonyms: ['supporter', 'advocate'],
    antonyms: ['critic', 'opponent'],
  },
  {
    word: 'ambles',
    definition: 'walks in a relaxed way',
    synonyms: ['strolls', 'saunters'],
    antonyms: ['rushes', 'hurries'],
  },
  {
    word: 'ineptitude',
    definition: 'lack of skill',
    synonyms: ['clumsiness', 'awkwardness'],
    antonyms: ['skill', 'ability'],
  },
  {
    word: 'congenial',
    definition: 'pleasant because similar',
    synonyms: ['friendly', 'agreeable'],
    antonyms: ['unfriendly', 'hostile'],
  },
  {
    word: 'admission',
    definition: 'entry or confession',
    synonyms: ['entry', 'confession'],
    antonyms: ['denial', 'exclusion'],
  },
  {
    word: 'judicious',
    definition: 'showing good judgement',
    synonyms: ['wise', 'sensible'],
    antonyms: ['foolish', 'rash'],
  },
  {
    word: 'gracious',
    definition: 'polite and kind',
    synonyms: ['courteous', 'kind'],
    antonyms: ['rude', 'impolite'],
  },
  {
    word: 'stern',
    definition: 'strict and serious',
    synonyms: ['strict', 'severe'],
    antonyms: ['lenient', 'gentle'],
  },
  {
    word: 'defy',
    definition: 'refuse to obey',
    synonyms: ['resist', 'disobey'],
    antonyms: ['obey', 'submit'],
  },
  {
    word: 'defame',
    definition: "hurt someone's good name",
    synonyms: ['slander', 'smear'],
    antonyms: ['praise', 'honour'],
  },
  {
    word: 'score',
    definition: 'points won',
    synonyms: ['points', 'tally'],
    antonyms: ['loss', 'zero'],
  },
  {
    word: 'signature',
    definition: 'your written name',
    synonyms: ['autograph', 'sign'],
    antonyms: ['—', '—'],
  },
  {
    word: 'sermon',
    definition: 'religious speech',
    synonyms: ['homily', 'talk'],
    antonyms: ['silence', '—'],
  },
  {
    word: 'fatigue',
    definition: 'great tiredness',
    synonyms: ['tiredness', 'weariness'],
    antonyms: ['energy', 'vitality'],
  },
  {
    word: 'anecdote',
    definition: 'short amusing story',
    synonyms: ['story', 'tale'],
    antonyms: ['novel', 'silence'],
  },
  {
    word: 'insignificant',
    definition: 'not important',
    synonyms: ['trivial', 'minor'],
    antonyms: ['important', 'major'],
  },
  {
    word: 'pacifist',
    definition: 'person who refuses violence',
    synonyms: ['peace-lover', 'non-fighter'],
    antonyms: ['warrior', 'fighter'],
  },
  {
    word: 'quell',
    definition: 'put an end to',
    synonyms: ['suppress', 'stop'],
    antonyms: ['encourage', 'foment'],
  },
  {
    word: 'quiet',
    definition: 'making little noise',
    synonyms: ['silent', 'still'],
    antonyms: ['loud', 'noisy'],
  },
  {
    word: 'ordained',
    definition: 'officially made a priest; ordered',
    synonyms: ['appointed', 'decreed'],
    antonyms: ['dismissed', 'forbidden'],
  },
  {
    word: 'imminent',
    definition: 'about to happen very soon',
    synonyms: ['near', 'upcoming'],
    antonyms: ['distant', 'remote'],
  },
  {
    word: 'audacious',
    definition: 'bold and daring',
    synonyms: ['bold', 'daring'],
    antonyms: ['timid', 'cowardly'],
  },
  {
    word: 'privilege',
    definition: 'special right or benefit',
    synonyms: ['benefit', 'advantage'],
    antonyms: ['disadvantage', 'penalty'],
  },
  {
    word: 'unkempt',
    definition: 'untidy and messy',
    synonyms: ['scruffy', 'messy'],
    antonyms: ['tidy', 'neat'],
  },
  {
    word: 'idol',
    definition: 'person greatly admired',
    synonyms: ['hero', 'star'],
    antonyms: ['nobody', 'villain'],
  },
  {
    word: 'renounce',
    definition: 'give up formally',
    synonyms: ['abandon', 'reject'],
    antonyms: ['claim', 'embrace'],
  },
  {
    word: 'heroic',
    definition: 'very brave',
    synonyms: ['brave', 'courageous'],
    antonyms: ['cowardly', 'fearful'],
  },
  {
    word: 'lunar',
    definition: 'relating to the moon',
    synonyms: ['moon', 'selenic'],
    antonyms: ['solar', 'sun'],
  },
  {
    word: 'composure',
    definition: 'calm self-control',
    synonyms: ['calm', 'poise'],
    antonyms: ['panic', 'agitation'],
  },
  {
    word: 'disclose',
    definition: 'make known',
    synonyms: ['reveal', 'uncover'],
    antonyms: ['hide', 'conceal'],
  },
  {
    word: 'obstinate',
    definition: 'stubborn',
    synonyms: ['stubborn', 'headstrong'],
    antonyms: ['flexible', 'yielding'],
  },
  {
    word: 'paradigm',
    definition: 'model or example',
    synonyms: ['model', 'pattern'],
    antonyms: ['exception', 'misfit'],
  },
  {
    word: 'chastised',
    definition: 'punished or scolded',
    synonyms: ['scolded', 'punished'],
    antonyms: ['praised', 'rewarded'],
  },
  {
    word: 'industrious',
    definition: 'hard-working',
    synonyms: ['hard-working', 'diligent'],
    antonyms: ['lazy', 'idle'],
  },
  {
    word: 'boisterous',
    definition: 'noisy and energetic',
    synonyms: ['rowdy', 'lively'],
    antonyms: ['quiet', 'calm'],
  },
  {
    word: 'unforgiving',
    definition: 'not willing to forgive',
    synonyms: ['harsh', 'relentless'],
    antonyms: ['forgiving', 'lenient'],
  },
  {
    word: 'adherent',
    definition: 'supporter of an idea',
    synonyms: ['follower', 'supporter'],
    antonyms: ['opponent', 'critic'],
  },
  {
    word: 'evident',
    definition: 'easy to see',
    synonyms: ['clear', 'obvious'],
    antonyms: ['unclear', 'hidden'],
  },
  {
    word: 'exonerate',
    definition: 'prove someone not guilty',
    synonyms: ['absolve', 'clear'],
    antonyms: ['blame', 'accuse'],
  },
];
