export const wordBankPart6 = [
  {
    word: 'antipathy',
    definition: 'a strong feeling of dislike',
    synonyms: ['hatred', 'aversion'],
    antonyms: ['fondness', 'affection'],
  },
  {
    word: 'queue',
    definition: 'a line of people waiting',
    synonyms: ['line', 'row'],
    antonyms: ['crowd', 'cluster'],
  },
  {
    word: 'retort',
    definition: 'a quick, clever reply',
    synonyms: ['reply', 'answer'],
    antonyms: ['silence', 'agreement'],
  },
  {
    word: 'litotes',
    definition: 'saying the opposite to soften a point',
    synonyms: ['understatement', 'double-negative'],
    antonyms: ['hyperbole', 'exaggeration'],
  },
  {
    word: 'rhetorical',
    definition: 'asked to make a point, not for an answer',
    synonyms: ['oratorical', 'expressive'],
    antonyms: ['literal', 'direct'],
  },
  {
    word: 'reinvigorate',
    definition: 'to give new energy to',
    synonyms: ['refresh', 'revive'],
    antonyms: ['weaken', 'drain'],
  },
  {
    word: 'objection',
    definition: 'an expression of dislike or opposition',
    synonyms: ['protest', 'complaint'],
    antonyms: ['approval', 'support'],
  },
  {
    word: 'malleable',
    definition: 'easy to bend or shape',
    synonyms: ['flexible', 'pliable'],
    antonyms: ['rigid', 'stiff'],
  },
  {
    word: 'constant',
    definition: 'happening all the time',
    synonyms: ['continuous', 'steady'],
    antonyms: ['occasional', 'irregular'],
  },
  {
    word: 'fanaticism',
    definition: 'extreme and unreasonable enthusiasm',
    synonyms: ['zeal', 'obsession'],
    antonyms: ['moderation', 'apathy'],
  },
  {
    word: 'voluminous',
    definition: 'very large or taking up much space',
    synonyms: ['bulky', 'huge'],
    antonyms: ['small', 'compact'],
  },
  {
    word: 'twilight',
    definition: 'soft light just after sunset',
    synonyms: ['dusk', 'sunset'],
    antonyms: ['dawn', 'daylight'],
  },
  {
    word: 'refute',
    definition: 'to prove something wrong',
    synonyms: ['disprove', 'counter'],
    antonyms: ['prove', 'confirm'],
  },
  {
    word: 'temperate',
    definition: 'mild and not extreme',
    synonyms: ['mild', 'moderate'],
    antonyms: ['harsh', 'extreme'],
  },
  {
    word: 'intention',
    definition: 'a plan or purpose',
    synonyms: ['aim', 'goal'],
    antonyms: ['accident', 'chance'],
  },
  {
    word: 'profit',
    definition: 'money gained after costs',
    synonyms: ['gain', 'earnings'],
    antonyms: ['loss', 'debt'],
  },
  {
    word: 'completely',
    definition: 'totally; with nothing missing',
    synonyms: ['entirely', 'wholly'],
    antonyms: ['partly', 'partially'],
  },
  {
    word: 'convert',
    definition: 'to change into a different form',
    synonyms: ['change', 'transform'],
    antonyms: ['keep', 'preserve'],
  },
  {
    word: 'ubiquitous',
    definition: 'found everywhere',
    synonyms: ['everywhere', 'common'],
    antonyms: ['rare', 'scarce'],
  },
  {
    word: 'innocuous',
    definition: 'harmless',
    synonyms: ['harmless', 'safe'],
    antonyms: ['dangerous', 'harmful'],
  },
  {
    word: 'remorse',
    definition: 'deep regret for wrong-doing',
    synonyms: ['regret', 'guilt'],
    antonyms: ['pride', 'shamelessness'],
  },
  {
    word: 'omen',
    definition: 'a sign of something that will happen',
    synonyms: ['sign', 'portent'],
    antonyms: ['surprise', 'chance'],
  },
  {
    word: 'inaccurate',
    definition: 'not correct',
    synonyms: ['wrong', 'incorrect'],
    antonyms: ['accurate', 'exact'],
  },
  {
    word: 'abrasive',
    definition: 'rough and able to wear away',
    synonyms: ['rough', 'harsh'],
    antonyms: ['smooth', 'gentle'],
  },
  {
    word: 'comrade',
    definition: 'a friend, especially in difficult times',
    synonyms: ['companion', 'ally'],
    antonyms: ['foe', 'enemy'],
  },
  {
    word: 'gregarious',
    definition: 'enjoying the company of others',
    synonyms: ['sociable', 'friendly'],
    antonyms: ['shy', 'reserved'],
  },
  {
    word: 'adhere',
    definition: 'stick firmly to something',
    synonyms: ['stick', 'cling'],
    antonyms: ['detach', 'separate'],
  },
  {
    word: 'deplore',
    definition: 'to feel strong disapproval of',
    synonyms: ['condemn', 'lament'],
    antonyms: ['praise', 'approve'],
  },
  {
    word: 'induce',
    definition: 'to persuade or cause',
    synonyms: ['persuade', 'cause'],
    antonyms: ['deter', 'prevent'],
  },
  {
    word: 'levity',
    definition: 'light-hearted humour',
    synonyms: ['fun', 'gaiety'],
    antonyms: ['seriousness', 'gravity'],
  },
  {
    word: 'government',
    definition: 'people who rule a country',
    synonyms: ['state', 'authority'],
    antonyms: ['anarchy', 'chaos'],
  },
  {
    word: 'reflective',
    definition: 'thinking deeply',
    synonyms: ['thoughtful', 'pensive'],
    antonyms: ['careless', 'heedless'],
  },
  {
    word: 'trifling',
    definition: 'small and unimportant',
    synonyms: ['minor', 'petty'],
    antonyms: ['serious', 'important'],
  },
  {
    word: 'coarse',
    definition: 'rough to the touch or rude in manner',
    synonyms: ['rough', 'rude'],
    antonyms: ['smooth', 'polite'],
  },
  {
    word: 'guile',
    definition: 'clever but dishonest behaviour',
    synonyms: ['cunning', 'trickery'],
    antonyms: ['honesty', 'sincerity'],
  },
  {
    word: 'dilapidated',
    definition: 'old and falling apart',
    synonyms: ['run-down', 'ramshackle'],
    antonyms: ['new', 'renovated'],
  },
  {
    word: 'belittle',
    definition: 'make someone seem unimportant',
    synonyms: ['mock', 'downgrade'],
    antonyms: ['praise', 'esteem'],
  },
  {
    word: 'deceit',
    definition: 'dishonest behaviour',
    synonyms: ['trickery', 'fraud'],
    antonyms: ['honesty', 'truth'],
  },
  {
    word: 'galvanise',
    definition: 'to shock into action',
    synonyms: ['motivate', 'spur'],
    antonyms: ['dissuade', 'discourage'],
  },
  {
    word: 'exciting',
    definition: 'causing great enthusiasm',
    synonyms: ['thrilling', 'fun'],
    antonyms: ['boring', 'dull'],
  },
  {
    word: 'hone',
    definition: 'sharpen or improve a skill',
    synonyms: ['sharpen', 'improve'],
    antonyms: ['dull', 'weaken'],
  },
  {
    word: 'deprecate',
    definition: 'to criticise or express disapproval',
    synonyms: ['criticise', 'disapprove'],
    antonyms: ['praise', 'support'],
  },
  {
    word: 'devour',
    definition: 'eat quickly and greedily',
    synonyms: ['gobble', 'wolf'],
    antonyms: ['nibble', 'savour'],
  },
  {
    word: 'maximum',
    definition: 'the greatest amount possible',
    synonyms: ['highest', 'top'],
    antonyms: ['minimum', 'least'],
  },
  {
    word: 'derisive',
    definition: 'showing ridicule or scorn',
    synonyms: ['mocking', 'scornful'],
    antonyms: ['respectful', 'kind'],
  },
  {
    word: 'libel',
    definition: 'written statement that harms reputation',
    synonyms: ['defamation', 'slander'],
    antonyms: ['praise', 'compliment'],
  },
  {
    word: 'reiterate',
    definition: 'to say again',
    synonyms: ['repeat', 'restate'],
    antonyms: ['withdraw', 'retract'],
  },
  {
    word: 'justification',
    definition: 'a reason that shows something is right',
    synonyms: ['reason', 'excuse'],
    antonyms: ['blame', 'condemnation'],
  },
  {
    word: 'assistance',
    definition: 'help',
    synonyms: ['help', 'aid'],
    antonyms: ['hindrance', 'obstruction'],
  },
  {
    word: 'stoic',
    definition: 'showing no emotion even in pain',
    synonyms: ['unemotional', 'calm'],
    antonyms: ['emotional', 'expressive'],
  },
  {
    word: 'florid',
    definition: 'brightly coloured or fancy',
    synonyms: ['flowery', 'ornate'],
    antonyms: ['plain', 'simple'],
  },
  {
    word: 'advance',
    definition: 'move forward',
    synonyms: ['progress', 'proceed'],
    antonyms: ['retreat', 'recede'],
  },
  {
    word: 'acronym',
    definition: 'a word made from initial letters',
    synonyms: ['initialism', 'short form'],
    antonyms: ['—', '—'],
  },
  {
    word: 'becoming',
    definition: 'suitable and attractive',
    synonyms: ['flattering', 'fitting'],
    antonyms: ['unbecoming', 'unflattering'],
  },
  {
    word: 'authoritarian',
    definition: 'demanding strict obedience',
    synonyms: ['dictatorial', 'strict'],
    antonyms: ['democratic', 'lenient'],
  },
  {
    word: 'recluse',
    definition: 'person who lives alone and avoids others',
    synonyms: ['hermit', 'loner'],
    antonyms: ['socialite', 'extrovert'],
  },
  {
    word: 'oscillate',
    definition: 'to swing back and forth',
    synonyms: ['swing', 'waver'],
    antonyms: ['steady', 'stabilise'],
  },
  {
    word: 'thrust',
    definition: 'a strong push',
    synonyms: ['push', 'shove'],
    antonyms: ['pull', 'drag'],
  },
  {
    word: 'fallacious',
    definition: 'based on a false idea',
    synonyms: ['false', 'misleading'],
    antonyms: ['true', 'valid'],
  },
  {
    word: 'marred',
    definition: 'damaged and spoiled',
    synonyms: ['damaged', 'spoiled'],
    antonyms: ['perfect', 'flawless'],
  },
  {
    word: 'contract',
    definition: 'a written agreement; to shrink',
    synonyms: ['agreement', 'shrink'],
    antonyms: ['expand', 'enlarge'],
  },
  {
    word: 'philanthropist',
    definition: 'person who gives money to help others',
    synonyms: ['donor', 'benefactor'],
    antonyms: ['miser', 'scrooge'],
  },
  {
    word: 'profession',
    definition: 'a job requiring special training',
    synonyms: ['occupation', 'career'],
    antonyms: ['hobby', 'pastime'],
  },
  {
    word: 'tedious',
    definition: 'very boring',
    synonyms: ['boring', 'dull'],
    antonyms: ['exciting', 'interesting'],
  },
  {
    word: 'menacing',
    definition: 'threatening danger',
    synonyms: ['threatening', 'dangerous'],
    antonyms: ['safe', 'harmless'],
  },
  {
    word: 'severity',
    definition: 'harshness or seriousness',
    synonyms: ['harshness', 'strictness'],
    antonyms: ['gentleness', 'leniency'],
  },
  {
    word: 'dismay',
    definition: 'sudden worry and sadness',
    synonyms: ['shock', 'alarm'],
    antonyms: ['calm', 'confidence'],
  },
  {
    word: 'hardy',
    definition: 'strong and able to survive',
    synonyms: ['tough', 'robust'],
    antonyms: ['delicate', 'fragile'],
  },
  {
    word: 'contemplate',
    definition: 'to think about for a long time',
    synonyms: ['consider', 'ponder'],
    antonyms: ['ignore', 'dismiss'],
  },
  {
    word: 'askance',
    definition: 'with a look of suspicion',
    synonyms: ['sceptically', 'doubtfully'],
    antonyms: ['openly', 'trustingly'],
  },
  {
    word: 'fund',
    definition: 'a supply of money for a purpose',
    synonyms: ['money', 'capital'],
    antonyms: ['debt', 'shortage'],
  },
  {
    word: 'euphonious',
    definition: 'pleasant-sounding',
    synonyms: ['melodious', 'harmonious'],
    antonyms: ['harsh', 'discordant'],
  },
  {
    word: 'acquainted',
    definition: 'familiar with',
    synonyms: ['familiar', 'aware'],
    antonyms: ['ignorant', 'unfamiliar'],
  },
  {
    word: 'hinge',
    definition: 'joint that lets a door swing',
    synonyms: ['pivot', 'axis'],
    antonyms: ['—', '—'],
  },
  {
    word: 'secure',
    definition: 'safe and protected',
    synonyms: ['safe', 'protected'],
    antonyms: ['unsafe', 'vulnerable'],
  },
  {
    word: 'ebullient',
    definition: 'full of cheerful energy',
    synonyms: ['bubbly', 'lively'],
    antonyms: ['depressed', 'gloomy'],
  },
  {
    word: 'rebuttal',
    definition: 'statement that disagrees with evidence',
    synonyms: ['counter-argument', 'reply'],
    antonyms: ['agreement', 'acceptance'],
  },
  {
    word: 'deploy',
    definition: 'move into position for action',
    synonyms: ['position', 'use'],
    antonyms: ['withdraw', 'recall'],
  },
  {
    word: 'complicity',
    definition: 'involvement in wrongdoing',
    synonyms: ['collusion', 'participation'],
    antonyms: ['innocence', 'ignorance'],
  },
  {
    word: 'patronising',
    definition: 'treating others as less clever',
    synonyms: ['condescending', 'snobbish'],
    antonyms: ['respectful', 'humble'],
  },
  {
    word: 'stubborn',
    definition: 'unwilling to change mind',
    synonyms: ['obstinate', 'determined'],
    antonyms: ['flexible', 'yielding'],
  },
  {
    word: 'kowtow',
    definition: 'to bow down or act very submissively',
    synonyms: ['grovel', 'bow'],
    antonyms: ['resist', 'defy'],
  },
  {
    word: 'scenic',
    definition: 'having beautiful natural views',
    synonyms: ['picturesque', 'pretty'],
    antonyms: ['ugly', 'dull'],
  },
  {
    word: 'special',
    definition: 'better or different from usual',
    synonyms: ['unique', 'particular'],
    antonyms: ['ordinary', 'common'],
  },
  {
    word: 'gorge',
    definition: 'a deep, narrow valley',
    synonyms: ['canyon', 'ravine'],
    antonyms: ['plain', 'plateau'],
  },
  {
    word: 'mediate',
    definition: 'help two sides reach agreement',
    synonyms: ['negotiate', 'arbitrate'],
    antonyms: ['argue', 'quarrel'],
  },
  {
    word: 'flatulence',
    definition: 'gas in the stomach',
    synonyms: ['wind', 'gas'],
    antonyms: ['—', '—'],
  },
  {
    word: 'illicit',
    definition: 'not allowed by law',
    synonyms: ['illegal', 'unlawful'],
    antonyms: ['legal', 'lawful'],
  },
  {
    word: 'stolid',
    definition: 'showing little emotion',
    synonyms: ['impassive', 'calm'],
    antonyms: ['emotional', 'lively'],
  },
  {
    word: 'equivocal',
    definition: 'having more than one meaning',
    synonyms: ['unclear', 'ambiguous'],
    antonyms: ['clear', 'definite'],
  },
  {
    word: 'dormant',
    definition: 'asleep or inactive',
    synonyms: ['inactive', 'sleeping'],
    antonyms: ['active', 'awake'],
  },
  {
    word: 'lure',
    definition: 'to tempt someone with a reward',
    synonyms: ['tempt', 'attract'],
    antonyms: ['repel', 'deter'],
  },
  {
    word: 'filly',
    definition: 'a young female horse',
    synonyms: ['young mare', 'foal'],
    antonyms: ['stallion', 'colt'],
  },
  {
    word: 'voyeuristic',
    definition: 'enjoying watching others secretly',
    synonyms: ['peeping', 'snooping'],
    antonyms: ['open', 'disinterested'],
  },
  {
    word: 'gasket',
    definition: 'seal that stops leaks between surfaces',
    synonyms: ['seal', 'washer'],
    antonyms: ['gap', 'leak'],
  },
  {
    word: 'vivacious',
    definition: 'full of lively energy',
    synonyms: ['lively', 'spirited'],
    antonyms: ['dull', 'lifeless'],
  },
  {
    word: 'grate',
    definition: 'rub into small pieces',
    synonyms: ['shred', 'grind'],
    antonyms: ['combine', 'mend'],
  },
  {
    word: 'tirade',
    definition: 'a long, angry speech',
    synonyms: ['rant', 'outburst'],
    antonyms: ['praise', 'compliment'],
  },
  {
    word: 'cathartic',
    definition: 'providing emotional release',
    synonyms: ['cleansing', 'purging'],
    antonyms: ['upsetting', 'distressing'],
  },
  {
    word: 'enthralling',
    definition: 'very interesting',
    synonyms: ['captivating', 'fascinating'],
    antonyms: ['boring', 'dull'],
  },
  {
    word: 'sporadic',
    definition: 'happening now and then',
    synonyms: ['occasional', 'irregular'],
    antonyms: ['constant', 'steady'],
  },
  {
    word: 'purpose',
    definition: 'the reason for doing something',
    synonyms: ['goal', 'aim'],
    antonyms: ['meaninglessness', 'chance'],
  },
  {
    word: 'careering',
    definition: 'moving quickly and out of control',
    synonyms: ['hurtling', 'charging'],
    antonyms: ['crawling', 'creeping'],
  },
  {
    word: 'inadvertently',
    definition: 'without meaning to',
    synonyms: ['accidentally', 'unintentionally'],
    antonyms: ['deliberately', 'purposely'],
  },
  {
    word: 'maladroit',
    definition: 'clumsy and awkward',
    synonyms: ['clumsy', 'inept'],
    antonyms: ['skilful', 'adept'],
  },
  {
    word: 'pathetic',
    definition: 'causing pity',
    synonyms: ['sad', 'pitiful'],
    antonyms: ['admirable', 'impressive'],
  },
  {
    word: 'rank',
    definition: 'having a strong unpleasant smell; position',
    synonyms: ['smelly', 'position'],
    antonyms: ['fragrant', 'status-less'],
  },
  {
    word: 'introspective',
    definition: 'examining your own thoughts',
    synonyms: ['self-reflective', 'thoughtful'],
    antonyms: ['outgoing', 'unthinking'],
  },
  {
    word: 'language',
    definition: 'system of spoken or written words',
    synonyms: ['speech', 'tongue'],
    antonyms: ['silence', '—'],
  },
  {
    word: 'episodic',
    definition: 'happening in separate parts',
    synonyms: ['serial', 'periodic'],
    antonyms: ['continuous', 'ongoing'],
  },
  {
    word: 'esteem',
    definition: 'high respect',
    synonyms: ['respect', 'admiration'],
    antonyms: ['disrespect', 'scorn'],
  },
  {
    word: 'composed',
    definition: 'calm and self-controlled',
    synonyms: ['calm', 'collected'],
    antonyms: ['agitated', 'nervous'],
  },
  {
    word: 'gullible',
    definition: 'easily tricked',
    synonyms: ['naïve', 'trusting'],
    antonyms: ['suspicious', 'wary'],
  },
  {
    word: 'capricious',
    definition: 'changing mind suddenly',
    synonyms: ['fickle', 'unpredictable'],
    antonyms: ['steady', 'reliable'],
  },
  {
    word: 'fickle',
    definition: 'often changing feelings',
    synonyms: ['changeable', 'inconstant'],
    antonyms: ['loyal', 'steady'],
  },
  {
    word: 'brevity',
    definition: 'shortness of time or words',
    synonyms: ['shortness', 'conciseness'],
    antonyms: ['lengthiness', 'verbosity'],
  },
  {
    word: 'queer',
    definition: 'strange or unusual',
    synonyms: ['odd', 'weird'],
    antonyms: ['normal', 'ordinary'],
  },
  {
    word: 'lightning',
    definition: 'a flash of electricity in the sky',
    synonyms: ['flash', 'bolt'],
    antonyms: ['—', '—'],
  },
  {
    word: 'consume',
    definition: 'to eat or use up',
    synonyms: ['eat', 'use'],
    antonyms: ['save', 'preserve'],
  },
  {
    word: 'agreeable',
    definition: 'pleasant and easy to like',
    synonyms: ['pleasant', 'nice'],
    antonyms: ['disagreeable', 'unpleasant'],
  },
  {
    word: 'heed',
    definition: 'to pay attention to',
    synonyms: ['notice', 'mind'],
    antonyms: ['ignore', 'disregard'],
  },
  {
    word: 'disparaging',
    definition: 'speaking badly of',
    synonyms: ['belittling', 'critical'],
    antonyms: ['complimentary', 'praising'],
  },
  {
    word: 'connoisseur',
    definition: 'expert judge of good things',
    synonyms: ['expert', 'authority'],
    antonyms: ['amateur', 'novice'],
  },
  {
    word: 'lame',
    definition: 'unable to walk properly; weak excuse',
    synonyms: ['crippled', 'weak'],
    antonyms: ['strong', 'sound'],
  },
  {
    word: 'phenomenon',
    definition: 'an interesting event or fact',
    synonyms: ['event', 'occurrence'],
    antonyms: ['normality', 'non-event'],
  },
  {
    word: 'insufferable',
    definition: 'too annoying to put up with',
    synonyms: ['unbearable', 'intolerable'],
    antonyms: ['bearable', 'tolerable'],
  },
  {
    word: 'breadth',
    definition: 'the width of something',
    synonyms: ['width', 'span'],
    antonyms: ['narrowness', 'thinness'],
  },
  {
    word: 'intractable',
    definition: 'hard to manage or solve',
    synonyms: ['stubborn', 'tough'],
    antonyms: ['manageable', 'easy'],
  },
  {
    word: 'erudite',
    definition: 'showing great knowledge',
    synonyms: ['learned', 'scholarly'],
    antonyms: ['ignorant', 'uneducated'],
  },
  {
    word: 'lofty',
    definition: 'very high or noble',
    synonyms: ['tall', 'grand'],
    antonyms: ['low', 'base'],
  },
  {
    word: 'innate',
    definition: 'present from birth',
    synonyms: ['inborn', 'natural'],
    antonyms: ['acquired', 'learned'],
  },
  {
    word: 'rural',
    definition: 'related to the countryside',
    synonyms: ['country', 'pastoral'],
    antonyms: ['urban', 'city'],
  },
  {
    word: 'thought-provoking',
    definition: 'makes you think deeply',
    synonyms: ['stimulating', 'challenging'],
    antonyms: ['dull', 'boring'],
  },
  {
    word: 'espouse',
    definition: 'to support an idea',
    synonyms: ['support', 'adopt'],
    antonyms: ['reject', 'oppose'],
  },
  {
    word: 'intimate',
    definition: 'close and personal; hint',
    synonyms: ['close', 'hint'],
    antonyms: ['distant', 'public'],
  },
  {
    word: 'roam',
    definition: 'wander around without a plan',
    synonyms: ['wander', 'range'],
    antonyms: ['stay', 'settle'],
  },
  {
    word: 'entendre',
    definition: 'a phrase with two meanings',
    synonyms: ['double meaning', 'pun'],
    antonyms: ['literal', 'clarity'],
  },
  {
    word: 'obnoxious',
    definition: 'very unpleasant',
    synonyms: ['nasty', 'offensive'],
    antonyms: ['pleasant', 'delightful'],
  },
  {
    word: 'horrendous',
    definition: 'extremely unpleasant',
    synonyms: ['terrible', 'awful'],
    antonyms: ['wonderful', 'lovely'],
  },
  {
    word: 'affinity',
    definition: 'a natural liking',
    synonyms: ['liking', 'attraction'],
    antonyms: ['dislike', 'aversion'],
  },
  {
    word: 'magnetic',
    definition: 'having the power to attract',
    synonyms: ['attractive', 'captivating'],
    antonyms: ['repellent', 'repulsive'],
  },
  {
    word: 'era',
    definition: 'a long period of time',
    synonyms: ['age', 'epoch'],
    antonyms: ['moment', 'instant'],
  },
  {
    word: 'abandon',
    definition: 'to leave behind',
    synonyms: ['leave', 'desert'],
    antonyms: ['stay', 'keep'],
  },
  {
    word: 'risqué',
    definition: 'slightly rude or shocking',
    synonyms: ['naughty', 'spicy'],
    antonyms: ['proper', 'innocent'],
  },
  {
    word: 'domestic',
    definition: 'related to the home',
    synonyms: ['household', 'home'],
    antonyms: ['foreign', 'wild'],
  },
  {
    word: 'acerbic',
    definition: 'sharp and bitter in tone',
    synonyms: ['biting', 'sour'],
    antonyms: ['gentle', 'kind'],
  },
  {
    word: 'brooding',
    definition: 'showing deep unhappiness',
    synonyms: ['moody', 'sullen'],
    antonyms: ['cheerful', 'bright'],
  },
  {
    word: 'sympathiser',
    definition: 'person who supports someone else’s cause',
    synonyms: ['supporter', 'ally'],
    antonyms: ['opponent', 'enemy'],
  },
  {
    word: 'ingenious',
    definition: 'clever at inventing',
    synonyms: ['clever', 'inventive'],
    antonyms: ['clumsy', 'unimaginative'],
  },
  {
    word: 'lucrative',
    definition: 'bringing in lots of money',
    synonyms: ['profitable', 'rewarding'],
    antonyms: ['unprofitable', 'costly'],
  },
  {
    word: 'despot',
    definition: 'cruel ruler with absolute power',
    synonyms: ['tyrant', 'dictator'],
    antonyms: ['democrat', 'liberator'],
  },
  {
    word: 'optimist',
    definition: 'person who expects good things',
    synonyms: ['positive thinker', 'idealist'],
    antonyms: ['pessimist', 'gloom-monger'],
  },
  {
    word: 'yearn',
    definition: 'to long for something',
    synonyms: ['long', 'pine'],
    antonyms: ['dislike', 'reject'],
  },
  {
    word: 'humorous',
    definition: 'funny and amusing',
    synonyms: ['funny', 'amusing'],
    antonyms: ['serious', 'grave'],
  },
  {
    word: 'raconteur',
    definition: 'person good at telling stories',
    synonyms: ['storyteller', 'narrator'],
    antonyms: ['listener', 'mute'],
  },
  {
    word: 'ruffian',
    definition: 'violent trouble-maker',
    synonyms: ['thug', 'bully'],
    antonyms: ['gentleman', 'peacemaker'],
  },
  {
    word: 'sedentary',
    definition: 'spending lots of time sitting',
    synonyms: ['inactive', 'sitting'],
    antonyms: ['active', 'energetic'],
  },
  {
    word: 'prominence',
    definition: 'state of being important',
    synonyms: ['importance', 'fame'],
    antonyms: ['obscurity', 'insignificance'],
  },
  {
    word: 'heedless',
    definition: 'not paying attention',
    synonyms: ['careless', 'inattentive'],
    antonyms: ['careful', 'alert'],
  },
  {
    word: 'cryptic',
    definition: 'having hidden meaning',
    synonyms: ['mysterious', 'puzzling'],
    antonyms: ['clear', 'obvious'],
  },
  {
    word: 'meek',
    definition: 'quiet and gentle',
    synonyms: ['gentle', 'mild'],
    antonyms: ['bold', 'aggressive'],
  },
  {
    word: 'esoteric',
    definition: 'understood by only a few',
    synonyms: ['obscure', 'arcane'],
    antonyms: ['common', 'simple'],
  },
  {
    word: 'drone',
    definition: 'low buzzing sound; speak monotonously',
    synonyms: ['buzz', 'hum'],
    antonyms: ['silence', 'shout'],
  },
  {
    word: 'dismantle',
    definition: 'take something apart',
    synonyms: ['take apart', 'disassemble'],
    antonyms: ['assemble', 'build'],
  },
  {
    word: 'banish',
    definition: 'send someone away',
    synonyms: ['exile', 'expel'],
    antonyms: ['welcome', 'invite'],
  },
  {
    word: 'misanthrope',
    definition: 'person who dislikes people',
    synonyms: ['hater', 'loner'],
    antonyms: ['philanthropist', 'friend'],
  },
  {
    word: 'device',
    definition: 'a tool or machine',
    synonyms: ['gadget', 'instrument'],
    antonyms: ['—', '—'],
  },
  {
    word: 'college',
    definition: 'place of higher learning',
    synonyms: ['university', 'school'],
    antonyms: ['—', '—'],
  },
  {
    word: 'sufficient',
    definition: 'enough for the need',
    synonyms: ['enough', 'adequate'],
    antonyms: ['insufficient', 'lacking'],
  },
  {
    word: 'poultry',
    definition: 'birds raised for meat or eggs',
    synonyms: ['chickens', 'fowl'],
    antonyms: ['—', '—'],
  },
  {
    word: 'acrimonious',
    definition: 'full of anger and bad feeling',
    synonyms: ['bitter', 'hostile'],
    antonyms: ['friendly', 'kind'],
  },
  {
    word: 'plummet',
    definition: 'fall straight down quickly',
    synonyms: ['drop', 'fall'],
    antonyms: ['rise', 'soar'],
  },
  {
    word: 'zestful',
    definition: 'full of energetic enjoyment',
    synonyms: ['lively', 'enthusiastic'],
    antonyms: ['dull', 'lifeless'],
  },
  {
    word: 'lustrous',
    definition: 'shiny and bright',
    synonyms: ['shiny', 'glossy'],
    antonyms: ['dull', 'matte'],
  },
  {
    word: 'nauseating',
    definition: 'making you feel sick',
    synonyms: ['sickening', 'disgusting'],
    antonyms: ['pleasant', 'delicious'],
  },
  {
    word: 'virtuoso',
    definition: 'a person very skilled in music',
    synonyms: ['master', 'maestro'],
    antonyms: ['novice', 'beginner'],
  },
  {
    word: 'remnant',
    definition: 'small part left over',
    synonyms: ['leftover', 'remainder'],
    antonyms: ['whole', 'entirety'],
  },
  {
    word: 'convey',
    definition: 'to carry or communicate',
    synonyms: ['carry', 'communicate'],
    antonyms: ['retain', 'withhold'],
  },
  {
    word: 'heartless',
    definition: 'without kindness',
    synonyms: ['cruel', 'cold'],
    antonyms: ['kind', 'gentle'],
  },
  {
    word: 'pleasurable',
    definition: 'giving enjoyment',
    synonyms: ['enjoyable', 'delightful'],
    antonyms: ['unpleasant', 'boring'],
  },
  {
    word: 'miserly',
    definition: 'not willing to spend money',
    synonyms: ['stingy', 'mean'],
    antonyms: ['generous', 'lavish'],
  },
  {
    word: 'augmenting',
    definition: 'making something larger',
    synonyms: ['increasing', 'enlarging'],
    antonyms: ['reducing', 'diminishing'],
  },
  {
    word: 'ridiculous',
    definition: 'very silly',
    synonyms: ['absurd', 'silly'],
    antonyms: ['serious', 'sensible'],
  },
  {
    word: 'flee',
    definition: 'run away quickly',
    synonyms: ['run', 'escape'],
    antonyms: ['stay', 'face'],
  },
  {
    word: 'decline',
    definition: 'to become smaller or weaker',
    synonyms: ['decrease', 'drop'],
    antonyms: ['increase', 'rise'],
  },
  {
    word: 'aberration',
    definition: 'something unusual',
    synonyms: ['oddity', 'anomaly'],
    antonyms: ['normality', 'regularity'],
  },
  {
    word: 'discriminating',
    definition: 'able to see fine differences',
    synonyms: ['selective', 'perceptive'],
    antonyms: ['indiscriminate', 'uncritical'],
  },
  {
    word: 'colloquial',
    definition: 'informal language',
    synonyms: ['informal', 'slang'],
    antonyms: ['formal', 'standard'],
  },
  {
    word: 'repudiate',
    definition: 'to reject something strongly',
    synonyms: ['reject', 'deny'],
    antonyms: ['accept', 'embrace'],
  },
  {
    word: 'acute',
    definition: 'very sharp or severe',
    synonyms: ['sharp', 'severe'],
    antonyms: ['dull', 'mild'],
  },
  {
    word: 'sanctity',
    definition: 'state of being holy',
    synonyms: ['holiness', 'sacredness'],
    antonyms: ['unholiness', 'impurity'],
  },
  {
    word: 'tactile',
    definition: 'related to touch',
    synonyms: ['touchable', 'physical'],
    antonyms: ['intangible', 'abstract'],
  },
  {
    word: 'ephemeral',
    definition: 'lasting a very short time',
    synonyms: ['short-lived', 'brief'],
    antonyms: ['lasting', 'enduring'],
  },
  {
    word: 'whining',
    definition: 'complaining in an annoying way',
    synonyms: ['complaining', 'moaning'],
    antonyms: ['cheerful', 'content'],
  },
  {
    word: 'stereotype',
    definition: 'unfair fixed idea about a group',
    synonyms: ['cliché', 'label'],
    antonyms: ['original', 'individual'],
  },
  {
    word: 'gallant',
    definition: 'brave and polite',
    synonyms: ['brave', 'courteous'],
    antonyms: ['cowardly', 'rude'],
  },
  {
    word: 'proximity',
    definition: 'nearness in space or time',
    synonyms: ['nearness', 'closeness'],
    antonyms: ['distance', 'remoteness'],
  },
  {
    word: 'fulfilled',
    definition: 'satisfied and happy',
    synonyms: ['satisfied', 'content'],
    antonyms: ['unhappy', 'empty'],
  },
  {
    word: 'influential',
    definition: 'having power to change things',
    synonyms: ['powerful', 'important'],
    antonyms: ['weak', 'insignificant'],
  },
  {
    word: 'mysterious',
    definition: 'hard to understand or explain',
    synonyms: ['puzzling', 'strange'],
    antonyms: ['clear', 'obvious'],
  },
];
