export const wordBank = [
  {
    word: 'squalor',
    definition: 'very dirty, poor living conditions',
    synonyms: ['filth', 'misery'],
    antonyms: ['cleanliness', 'luxury'],
  },
  {
    word: 'initiate',
    definition: 'to start something',
    synonyms: ['begin', 'launch'],
    antonyms: ['finish', 'halt'],
  },
  {
    word: 'despised',
    definition: 'strongly hated',
    synonyms: ['loathed', 'detested'],
    antonyms: ['loved', 'admired'],
  },
  {
    word: 'concentrated',
    definition: 'gathered closely together or very strong',
    synonyms: ['focused', 'intense'],
    antonyms: ['diluted', 'scattered'],
  },
  {
    word: 'environment',
    definition: 'the surroundings where something lives',
    synonyms: ['habitat', 'setting'],
    antonyms: ['void', 'nothingness'],
  },
  {
    word: 'integrity',
    definition: 'being honest and having strong morals',
    synonyms: ['honesty', 'uprightness'],
    antonyms: ['dishonesty', 'corruption'],
  },
  {
    word: 'futile',
    definition: 'useless; won’t work',
    synonyms: ['pointless', 'vain'],
    antonyms: ['useful', 'effective'],
  },
  {
    word: 'inane',
    definition: 'silly and pointless',
    synonyms: ['senseless', 'absurd'],
    antonyms: ['wise', 'sensible'],
  },
  {
    word: 'adjacent',
    definition: 'next to',
    synonyms: ['beside', 'neighboring'],
    antonyms: ['distant', 'separate'],
  },
  {
    word: 'divine',
    definition: 'related to a god; wonderful',
    synonyms: ['holy', 'heavenly'],
    antonyms: ['earthly', 'ordinary'],
  },
  {
    word: 'withhold',
    definition: 'to hold back or refuse to give',
    synonyms: ['keep', 'retain'],
    antonyms: ['give', 'release'],
  },
  {
    word: 'hoard',
    definition: 'store up and keep for oneself',
    synonyms: ['stash', 'stockpile'],
    antonyms: ['share', 'spend'],
  },
  {
    word: 'hackneyed',
    definition: 'over-used and unoriginal',
    synonyms: ['stale', 'trite'],
    antonyms: ['fresh', 'novel'],
  },
  {
    word: 'symbol',
    definition: 'a sign that stands for something else',
    synonyms: ['emblem', 'icon'],
    antonyms: ['literal', 'object'],
  },
  {
    word: 'sociable',
    definition: 'enjoying being with others',
    synonyms: ['friendly', 'outgoing'],
    antonyms: ['shy', 'unsociable'],
  },
  {
    word: 'helix',
    definition: 'a spiral shape',
    synonyms: ['coil', 'spiral'],
    antonyms: ['line', 'straight'],
  },
  {
    word: 'cunning',
    definition: 'clever in a sneaky way',
    synonyms: ['sly', 'crafty'],
    antonyms: ['honest', 'naïve'],
  },
  {
    word: 'reproach',
    definition: 'to blame or scold',
    synonyms: ['criticize', 'rebuke'],
    antonyms: ['praise', 'commend'],
  },
  {
    word: 'interested',
    definition: 'wanting to know or do something',
    synonyms: ['curious', 'engaged'],
    antonyms: ['bored', 'indifferent'],
  },
  {
    word: 'slacken',
    definition: 'to slow down or loosen',
    synonyms: ['ease', 'relax'],
    antonyms: ['tighten', 'hasten'],
  },
  {
    word: 'embarrass',
    definition: 'to make someone feel awkward',
    synonyms: ['humiliate', 'shame'],
    antonyms: ['comfort', 'reassure'],
  },
  {
    word: 'monochrome',
    definition: 'using only one colour',
    synonyms: ['single-colour', 'one-tone'],
    antonyms: ['multicolour', 'varied'],
  },
  {
    word: 'recalcitrant',
    definition: 'stubbornly disobedient',
    synonyms: ['unruly', 'defiant'],
    antonyms: ['obedient', 'compliant'],
  },
  {
    word: 'immediate',
    definition: 'happening right now',
    synonyms: ['instant', 'prompt'],
    antonyms: ['delayed', 'future'],
  },
  {
    word: 'contemporary',
    definition: 'belonging to the same time or modern',
    synonyms: ['current', 'modern'],
    antonyms: ['ancient', 'old-fashioned'],
  },
  {
    word: 'pretence',
    definition: 'a false show of something',
    synonyms: ['act', 'sham'],
    antonyms: ['truth', 'reality'],
  },
  {
    word: 'litigation',
    definition: 'taking a dispute to court',
    synonyms: ['lawsuit', 'legal action'],
    antonyms: ['settlement', 'agreement'],
  },
  {
    word: 'fertile',
    definition: 'able to produce many plants or babies',
    synonyms: ['rich', 'productive'],
    antonyms: ['barren', 'infertile'],
  },
  {
    word: 'enumerate',
    definition: 'to list one by one',
    synonyms: ['count', 'itemize'],
    antonyms: ['summarize', 'estimate'],
  },
  {
    word: 'impose',
    definition: 'to force something on others',
    synonyms: ['enforce', 'dictate'],
    antonyms: ['lift', 'remove'],
  },
];
