export const wordBankPart9 = [
  {
    word: 'supercilious',
    definition: 'behaving as though you are better than others',
    synonyms: ['arrogant', 'haughty'],
    antonyms: ['humble', 'modest'],
  },
  {
    word: 'impregnated',
    definition: 'filled or soaked right through',
    synonyms: ['saturated', 'infused'],
    antonyms: ['dry', 'empty'],
  },
  {
    word: 'responsibility',
    definition: 'duty you are expected to take care of',
    synonyms: ['duty', 'obligation'],
    antonyms: ['freedom', 'irresponsibility'],
  },
  {
    word: 'oblivious',
    definition: 'not aware of something',
    synonyms: ['unaware', 'ignorant'],
    antonyms: ['aware', 'alert'],
  },
  {
    word: 'sectarian',
    definition: 'strongly supporting your own group and not others',
    synonyms: ['partisan', 'factional'],
    antonyms: ['tolerant', 'open-minded'],
  },
  {
    word: 'hoof',
    definition: 'hard foot of an animal like a horse',
    synonyms: ['foot', 'cloven'],
    antonyms: ['paw', 'hand'],
  },
  {
    word: 'concur',
    definition: 'agree',
    synonyms: ['agree', 'coincide'],
    antonyms: ['disagree', 'differ'],
  },
  {
    word: 'raucous',
    definition: 'loud and rough',
    synonyms: ['rowdy', 'noisy'],
    antonyms: ['quiet', 'soft'],
  },
  {
    word: 'enrage',
    definition: 'make very angry',
    synonyms: ['anger', 'infuriate'],
    antonyms: ['calm', 'soothe'],
  },
  {
    word: 'consensus',
    definition: 'general agreement',
    synonyms: ['agreement', 'unity'],
    antonyms: ['disagreement', 'discord'],
  },
  {
    word: 'disintegrate',
    definition: 'break into pieces',
    synonyms: ['crumble', 'fall apart'],
    antonyms: ['solidify', 'combine'],
  },
  {
    word: 'imitate',
    definition: 'copy someone or something',
    synonyms: ['copy', 'mimic'],
    antonyms: ['originate', 'invent'],
  },
  {
    word: 'masculinity',
    definition: 'qualities thought typical of men',
    synonyms: ['manliness', 'virility'],
    antonyms: ['femininity', 'girlishness'],
  },
  {
    word: 'lucid',
    definition: 'clear and easy to understand',
    synonyms: ['clear', 'plain'],
    antonyms: ['vague', 'confused'],
  },
  {
    word: 'excellent',
    definition: 'extremely good',
    synonyms: ['outstanding', 'superb'],
    antonyms: ['poor', 'bad'],
  },
  {
    word: 'gauge',
    definition: 'measure exactly',
    synonyms: ['measure', 'judge'],
    antonyms: ['guess', 'ignore'],
  },
  {
    word: 'incorrigible',
    definition: 'unable to be corrected',
    synonyms: ['hopeless', 'unchangeable'],
    antonyms: ['reformable', 'improvable'],
  },
  {
    word: 'sceptical',
    definition: 'doubting that something is true',
    synonyms: ['doubtful', 'questioning'],
    antonyms: ['convinced', 'certain'],
  },
  {
    word: 'expunge',
    definition: 'erase completely',
    synonyms: ['delete', 'wipe'],
    antonyms: ['record', 'retain'],
  },
  {
    word: 'flippant',
    definition: 'not showing a serious attitude',
    synonyms: ['cheeky', 'dismissive'],
    antonyms: ['serious', 'respectful'],
  },
  {
    word: 'sly',
    definition: 'clever in a secret way',
    synonyms: ['cunning', 'sneaky'],
    antonyms: ['open', 'honest'],
  },
  {
    word: 'fleet',
    definition: 'moving very fast',
    synonyms: ['swift', 'rapid'],
    antonyms: ['slow', 'sluggish'],
  },
  {
    word: 'vindicate',
    definition: 'clear someone from blame',
    synonyms: ['justify', 'absolve'],
    antonyms: ['accuse', 'blame'],
  },
  {
    word: 'conscience',
    definition: 'inner sense of right and wrong',
    synonyms: ['morals', 'scruples'],
    antonyms: ['immorality', '—'],
  },
  {
    word: 'flamboyant',
    definition: 'bright and attention-seeking',
    synonyms: ['showy', 'flashy'],
    antonyms: ['plain', 'modest'],
  },
  {
    word: 'traitor',
    definition: 'person who betrays their group',
    synonyms: ['betrayer', 'turncoat'],
    antonyms: ['loyalist', 'patriot'],
  },
  {
    word: 'grata',
    definition: 'accepted or welcome',
    synonyms: ['welcome', 'accepted'],
    antonyms: ['unwelcome', 'rejected'],
  },
  {
    word: 'accustom',
    definition: 'make familiar by use',
    synonyms: ['adapt', 'habituate'],
    antonyms: ['shock', 'unsettle'],
  },
  {
    word: 'rhapsody',
    definition: 'piece of music full of feeling',
    synonyms: ['ecstasy', 'enthusiasm'],
    antonyms: ['dirge', 'dullness'],
  },
  {
    word: 'indiscriminate',
    definition: 'done without careful choice',
    synonyms: ['random', 'haphazard'],
    antonyms: ['selective', 'careful'],
  },
  {
    word: 'cynicism',
    definition: 'belief that people are selfish',
    synonyms: ['distrust', 'scepticism'],
    antonyms: ['trust', 'optimism'],
  },
  {
    word: 'disputatious',
    definition: 'fond of arguing',
    synonyms: ['argumentative', 'contentious'],
    antonyms: ['agreeable', 'peaceful'],
  },
  {
    word: 'venerate',
    definition: 'respect deeply',
    synonyms: ['revere', 'honour'],
    antonyms: ['despise', 'dishonour'],
  },
  {
    word: 'abomination',
    definition: 'something very disgusting',
    synonyms: ['horror', 'atrocity'],
    antonyms: ['delight', 'blessing'],
  },
  {
    word: 'empire',
    definition: 'group of countries ruled by one leader',
    synonyms: ['realm', 'kingdom'],
    antonyms: ['colony', 'province'],
  },
  {
    word: 'paltry',
    definition: 'small and worthless',
    synonyms: ['trivial', 'meagre'],
    antonyms: ['significant', 'substantial'],
  },
  {
    word: 'annihilated',
    definition: 'completely destroyed',
    synonyms: ['wiped out', 'obliterated'],
    antonyms: ['built', 'created'],
  },
  {
    word: 'retrieve',
    definition: 'get something back',
    synonyms: ['recover', 'regain'],
    antonyms: ['lose', 'misplace'],
  },
  {
    word: 'assemble',
    definition: 'gather together',
    synonyms: ['collect', 'gather'],
    antonyms: ['disperse', 'scatter'],
  },
  {
    word: 'abundance',
    definition: 'large quantity',
    synonyms: ['plenty', 'profusion'],
    antonyms: ['scarcity', 'lack'],
  },
  {
    word: 'ambiguous',
    definition: 'having more than one meaning',
    synonyms: ['unclear', 'vague'],
    antonyms: ['clear', 'definite'],
  },
  {
    word: 'infamous',
    definition: 'famous for something bad',
    synonyms: ['notorious', 'disreputable'],
    antonyms: ['famous', 'renowned'],
  },
  {
    word: 'hypothetical',
    definition: 'based on a guess or idea',
    synonyms: ['theoretical', 'supposed'],
    antonyms: ['actual', 'real'],
  },
  {
    word: 'ferocity',
    definition: 'extreme fierceness',
    synonyms: ['savagery', 'violence'],
    antonyms: ['gentleness', 'mildness'],
  },
  {
    word: 'pungent',
    definition: 'having a strong, sharp smell',
    synonyms: ['sharp', 'strong'],
    antonyms: ['bland', 'mild'],
  },
  {
    word: 'callous',
    definition: 'not caring about others’ feelings',
    synonyms: ['heartless', 'insensitive'],
    antonyms: ['kind', 'compassionate'],
  },
  {
    word: 'irreverence',
    definition: 'lack of respect',
    synonyms: ['disrespect', 'insolence'],
    antonyms: ['reverence', 'respect'],
  },
  {
    word: 'stomach',
    definition: 'organ where food is digested',
    synonyms: ['belly', 'tummy'],
    antonyms: ['back', '—'],
  },
  {
    word: 'modus',
    definition: 'way of doing something (as in modus operandi)',
    synonyms: ['method', 'manner'],
    antonyms: ['chance', 'accident'],
  },
  {
    word: 'tapestry',
    definition: 'thick woven picture',
    synonyms: ['wall-hanging', 'carpet'],
    antonyms: ['—', '—'],
  },
  {
    word: 'squabble',
    definition: 'small noisy argument',
    synonyms: ['row', 'spat'],
    antonyms: ['agreement', 'harmony'],
  },
  {
    word: 'convince',
    definition: 'make someone believe',
    synonyms: ['persuade', 'assure'],
    antonyms: ['deter', 'doubt'],
  },
  {
    word: 'probably',
    definition: 'very likely',
    synonyms: ['likely', 'presumably'],
    antonyms: ['unlikely', 'doubtfully'],
  },
  {
    word: 'amount',
    definition: 'quantity of something',
    synonyms: ['quantity', 'sum'],
    antonyms: ['part', 'lack'],
  },
  {
    word: 'credence',
    definition: 'belief that something is true',
    synonyms: ['belief', 'faith'],
    antonyms: ['doubt', 'denial'],
  },
  {
    word: 'pseudonym',
    definition: 'false name an author uses',
    synonyms: ['pen-name', 'alias'],
    antonyms: ['real name', '—'],
  },
  {
    word: 'cherished',
    definition: 'greatly loved',
    synonyms: ['valued', 'treasured'],
    antonyms: ['neglected', 'hated'],
  },
  {
    word: 'ransack',
    definition: 'search through and steal',
    synonyms: ['loot', 'plunder'],
    antonyms: ['guard', 'protect'],
  },
  {
    word: 'contrast',
    definition: 'clear difference',
    synonyms: ['difference', 'distinction'],
    antonyms: ['similarity', 'likeness'],
  },
  {
    word: 'bemoan',
    definition: 'complain sadly about',
    synonyms: ['lament', 'bewail'],
    antonyms: ['praise', 'celebrate'],
  },
  {
    word: 'extraneous',
    definition: 'not relevant',
    synonyms: ['irrelevant', 'unrelated'],
    antonyms: ['relevant', 'essential'],
  },
  {
    word: 'brusque',
    definition: 'very brief and rude',
    synonyms: ['curt', 'abrupt'],
    antonyms: ['polite', 'courteous'],
  },
  {
    word: 'ascendancy',
    definition: 'controlling influence',
    synonyms: ['dominance', 'power'],
    antonyms: ['subordination', 'weakness'],
  },
  {
    word: 'despondent',
    definition: 'very unhappy and without hope',
    synonyms: ['downcast', 'depressed'],
    antonyms: ['hopeful', 'cheerful'],
  },
  {
    word: 'nonchalant',
    definition: 'calm and not worried',
    synonyms: ['casual', 'unconcerned'],
    antonyms: ['anxious', 'concerned'],
  },
  {
    word: 'fervour',
    definition: 'strong passionate feeling',
    synonyms: ['passion', 'zeal'],
    antonyms: ['apathy', 'indifference'],
  },
  {
    word: 'singular',
    definition: 'remarkable or one of a kind',
    synonyms: ['unique', 'exceptional'],
    antonyms: ['ordinary', 'common'],
  },
  {
    word: 'diction',
    definition: 'choice of words',
    synonyms: ['wording', 'phrasing'],
    antonyms: ['—', '—'],
  },
  {
    word: 'gripe',
    definition: 'small complaint',
    synonyms: ['complain', 'moan'],
    antonyms: ['praise', 'applaud'],
  },
  {
    word: 'physiotherapy',
    definition: 'physical exercises to heal injury',
    synonyms: ['rehab', 'therapy'],
    antonyms: ['harm', 'injury'],
  },
  {
    word: 'whimsical',
    definition: 'playfully strange',
    synonyms: ['quirky', 'fanciful'],
    antonyms: ['serious', 'sensible'],
  },
  {
    word: 'desire',
    definition: 'strong wish',
    synonyms: ['wish', 'longing'],
    antonyms: ['dislike', 'aversion'],
  },
  {
    word: 'emulate',
    definition: 'try to be like',
    synonyms: ['imitate', 'copy'],
    antonyms: ['neglect', 'ignore'],
  },
  {
    word: 'machinate',
    definition: 'scheme or plot',
    synonyms: ['conspire', 'plot'],
    antonyms: ['co-operate', 'obey'],
  },
  {
    word: 'vast',
    definition: 'very large',
    synonyms: ['huge', 'immense'],
    antonyms: ['tiny', 'small'],
  },
  {
    word: 'flattering',
    definition: 'making someone look good',
    synonyms: ['complimentary', 'adoring'],
    antonyms: ['insulting', 'criticising'],
  },
  {
    word: 'occur',
    definition: 'happen',
    synonyms: ['happen', 'take place'],
    antonyms: ['cease', 'stop'],
  },
  {
    word: 'dogmatic',
    definition: 'insisting your ideas are true',
    synonyms: ['opinionated', 'dictatorial'],
    antonyms: ['open-minded', 'flexible'],
  },
  {
    word: 'scrupulous',
    definition: 'very careful to be honest',
    synonyms: ['honest', 'meticulous'],
    antonyms: ['dishonest', 'careless'],
  },
  {
    word: 'prologue',
    definition: 'introductory part of a story',
    synonyms: ['introduction', 'preface'],
    antonyms: ['epilogue', 'ending'],
  },
  {
    word: 'condemn',
    definition: 'say something is wrong',
    synonyms: ['denounce', 'criticise'],
    antonyms: ['praise', 'approve'],
  },
  {
    word: 'rueful',
    definition: 'feeling regret',
    synonyms: ['sorry', 'remorseful'],
    antonyms: ['cheerful', 'remorseless'],
  },
  {
    word: 'present',
    definition: 'give; existing now',
    synonyms: ['give', 'current'],
    antonyms: ['absent', 'past'],
  },
  {
    word: 'coerce',
    definition: 'force someone to act',
    synonyms: ['compel', 'pressure'],
    antonyms: ['persuade', 'allow'],
  },
  {
    word: 'placate',
    definition: 'calm someone who is angry',
    synonyms: ['soothe', 'pacify'],
    antonyms: ['anger', 'provoke'],
  },
  {
    word: 'captivating',
    definition: 'holding attention',
    synonyms: ['fascinating', 'engaging'],
    antonyms: ['boring', 'dull'],
  },
  {
    word: 'frequent',
    definition: 'happening often',
    synonyms: ['regular', 'common'],
    antonyms: ['rare', 'seldom'],
  },
  {
    word: 'grotesque',
    definition: 'distorted and ugly',
    synonyms: ['ugly', 'monstrous'],
    antonyms: ['beautiful', 'pleasing'],
  },
  {
    word: 'melancholic',
    definition: 'sad and thoughtful',
    synonyms: ['sad', 'mournful'],
    antonyms: ['cheerful', 'happy'],
  },
  {
    word: 'enchant',
    definition: 'delight greatly',
    synonyms: ['charm', 'bewitch'],
    antonyms: ['repel', 'bore'],
  },
  {
    word: 'ascetic',
    definition: 'living with very few comforts',
    synonyms: ['self-denying', 'spartan'],
    antonyms: ['luxurious', 'indulgent'],
  },
  {
    word: 'incongruous',
    definition: 'not matching surroundings',
    synonyms: ['out of place', 'odd'],
    antonyms: ['appropriate', 'fitting'],
  },
  {
    word: 'eulogy',
    definition: 'speech praising someone',
    synonyms: ['tribute', 'praise'],
    antonyms: ['attack', 'criticism'],
  },
  {
    word: 'dissent',
    definition: 'disagree with authority',
    synonyms: ['disagree', 'oppose'],
    antonyms: ['agree', 'concur'],
  },
  {
    word: 'plight',
    definition: 'difficult situation',
    synonyms: ['predicament', 'difficulty'],
    antonyms: ['comfort', 'blessing'],
  },
  {
    word: 'androgynous',
    definition: 'having both male and female qualities',
    synonyms: ['unisex', 'gender-neutral'],
    antonyms: ['masculine', 'feminine'],
  },
  {
    word: 'fatal',
    definition: 'causing death',
    synonyms: ['deadly', 'lethal'],
    antonyms: ['harmless', 'safe'],
  },
  {
    word: 'delightful',
    definition: 'very pleasing',
    synonyms: ['lovely', 'charming'],
    antonyms: ['awful', 'disagreeable'],
  },
  {
    word: 'option',
    definition: 'choice you can make',
    synonyms: ['choice', 'alternative'],
    antonyms: ['obligation', 'requirement'],
  },
  {
    word: 'obscure',
    definition: 'hard to see or understand',
    synonyms: ['unclear', 'hidden'],
    antonyms: ['clear', 'obvious'],
  },
  {
    word: 'clemency',
    definition: 'mercy towards someone',
    synonyms: ['mercy', 'leniency'],
    antonyms: ['harshness', 'severity'],
  },
  {
    word: 'vigilant',
    definition: 'keeping careful watch',
    synonyms: ['watchful', 'alert'],
    antonyms: ['careless', 'sleepy'],
  },
  {
    word: 'hostility',
    definition: 'strong dislike or anger',
    synonyms: ['enmity', 'hatred'],
    antonyms: ['friendliness', 'kindness'],
  },
  {
    word: 'articulate',
    definition: 'able to express clearly',
    synonyms: ['eloquent', 'expressive'],
    antonyms: ['mumbling', 'inarticulate'],
  },
  {
    word: 'mariner',
    definition: 'sailor',
    synonyms: ['sailor', 'seafarer'],
    antonyms: ['landlubber', '—'],
  },
  {
    word: 'bicycle',
    definition: 'two-wheeled pedal vehicle',
    synonyms: ['bike', 'cycle'],
    antonyms: ['car', '—'],
  },
  {
    word: 'diabolical',
    definition: 'extremely evil',
    synonyms: ['devilish', 'wicked'],
    antonyms: ['angelic', 'good'],
  },
  {
    word: 'uniform',
    definition: 'same clothing worn by a group',
    synonyms: ['outfit', 'livery'],
    antonyms: ['variety', 'casuals'],
  },
  {
    word: 'ventilation',
    definition: 'movement of fresh air',
    synonyms: ['airflow', 'aeration'],
    antonyms: ['stagnation', 'closure'],
  },
  {
    word: 'inconsequential',
    definition: 'not important',
    synonyms: ['trivial', 'minor'],
    antonyms: ['significant', 'important'],
  },
  {
    word: 'suggestible',
    definition: 'easily influenced',
    synonyms: ['impressionable', 'gullible'],
    antonyms: ['resistant', 'stubborn'],
  },
  {
    word: 'infiltrate',
    definition: 'secretly enter to gain access',
    synonyms: ['penetrate', 'sneak in'],
    antonyms: ['withdraw', 'retreat'],
  },
  {
    word: 'insurmountable',
    definition: 'too great to overcome',
    synonyms: ['impossible', 'unbeatable'],
    antonyms: ['manageable', 'surmountable'],
  },
  {
    word: 'archaic',
    definition: 'very old-fashioned',
    synonyms: ['ancient', 'obsolete'],
    antonyms: ['modern', 'current'],
  },
  {
    word: 'nominal',
    definition: 'existing in name only; very small',
    synonyms: ['token', 'minimal'],
    antonyms: ['actual', 'substantial'],
  },
  {
    word: 'asunder',
    definition: 'into pieces',
    synonyms: ['apart', 'separated'],
    antonyms: ['together', 'united'],
  },
  {
    word: 'pernicious',
    definition: 'very harmful',
    synonyms: ['deadly', 'destructive'],
    antonyms: ['harmless', 'beneficial'],
  },
  {
    word: 'chicanery',
    definition: 'clever trickery',
    synonyms: ['deception', 'fraud'],
    antonyms: ['honesty', 'candour'],
  },
  {
    word: 'transparent',
    definition: 'allowing light through; obvious',
    synonyms: ['clear', 'see-through'],
    antonyms: ['opaque', 'cloudy'],
  },
  {
    word: 'metonymy',
    definition: 'using a related word for something',
    synonyms: ['figurative', 'symbol'],
    antonyms: ['literal', '—'],
  },
  {
    word: 'reverent',
    definition: 'showing deep respect',
    synonyms: ['respectful', 'devout'],
    antonyms: ['irreverent', 'rude'],
  },
  {
    word: 'corroborate',
    definition: 'support with evidence',
    synonyms: ['confirm', 'verify'],
    antonyms: ['deny', 'refute'],
  },
  {
    word: 'preposterous',
    definition: 'completely ridiculous',
    synonyms: ['absurd', 'ludicrous'],
    antonyms: ['reasonable', 'sensible'],
  },
  {
    word: 'stupefy',
    definition: 'shock so much you can’t think',
    synonyms: ['astonish', 'daze'],
    antonyms: ['enlighten', 'clarify'],
  },
  {
    word: 'homonym',
    definition: 'word spelled same but different meaning',
    synonyms: ['same-spelling', '—'],
    antonyms: ['—', '—'],
  },
  {
    word: 'thrive',
    definition: 'grow very well',
    synonyms: ['prosper', 'flourish'],
    antonyms: ['wither', 'decline'],
  },
  {
    word: 'conducive',
    definition: 'helping to make something happen',
    synonyms: ['helpful', 'favourable'],
    antonyms: ['hindering', 'unfavourable'],
  },
  {
    word: 'solitude',
    definition: 'state of being alone',
    synonyms: ['isolation', 'seclusion'],
    antonyms: ['company', 'crowd'],
  },
  {
    word: 'prominent',
    definition: 'easily seen; important',
    synonyms: ['notable', 'outstanding'],
    antonyms: ['obscure', 'insignificant'],
  },
  {
    word: 'successful',
    definition: 'achieving the goal',
    synonyms: ['victorious', 'accomplished'],
    antonyms: ['unsuccessful', 'failed'],
  },
  {
    word: 'misogynist',
    definition: 'person who dislikes women',
    synonyms: ['woman-hater', 'chauvinist'],
    antonyms: ['feminist', 'supporter'],
  },
  {
    word: 'rarity',
    definition: 'something uncommon',
    synonyms: ['scarcity', 'unusualness'],
    antonyms: ['abundance', 'commonness'],
  },
  {
    word: 'veracity',
    definition: 'truthfulness',
    synonyms: ['truth', 'accuracy'],
    antonyms: ['falsehood', 'lying'],
  },
  {
    word: 'petty',
    definition: 'small and unimportant',
    synonyms: ['trivial', 'insignificant'],
    antonyms: ['important', 'major'],
  },
  {
    word: 'prolific',
    definition: 'producing much',
    synonyms: ['productive', 'fruitful'],
    antonyms: ['barren', 'unproductive'],
  },
  {
    word: 'maverick',
    definition: 'person who stands apart',
    synonyms: ['non-conformist', 'individualist'],
    antonyms: ['conformist', 'follower'],
  },
  {
    word: 'rescind',
    definition: 'officially cancel',
    synonyms: ['revoke', 'withdraw'],
    antonyms: ['enact', 'confirm'],
  },
  {
    word: 'refuse',
    definition: 'say no; rubbish material',
    synonyms: ['decline', 'reject'],
    antonyms: ['accept', 'agree'],
  },
  {
    word: 'verge',
    definition: 'edge or border',
    synonyms: ['edge', 'brink'],
    antonyms: ['centre', 'middle'],
  },
  {
    word: 'robust',
    definition: 'strong and healthy',
    synonyms: ['sturdy', 'tough'],
    antonyms: ['weak', 'fragile'],
  },
  {
    word: 'insulting',
    definition: 'rude and offensive',
    synonyms: ['offensive', 'abusive'],
    antonyms: ['respectful', 'polite'],
  },
  {
    word: 'inertia',
    definition: 'state of not moving or changing',
    synonyms: ['stillness', 'idleness'],
    antonyms: ['activity', 'motion'],
  },
  {
    word: 'barbarian',
    definition: 'uncivilised person',
    synonyms: ['savage', 'brute'],
    antonyms: ['civilised', 'gentleman'],
  },
  {
    word: 'evaluation',
    definition: 'careful judgement',
    synonyms: ['assessment', 'appraisal'],
    antonyms: ['guess', 'neglect'],
  },
  {
    word: 'inequity',
    definition: 'lack of fairness',
    synonyms: ['unfairness', 'injustice'],
    antonyms: ['equity', 'justice'],
  },
  {
    word: 'perish',
    definition: 'die in a violent way',
    synonyms: ['die', 'expire'],
    antonyms: ['survive', 'live'],
  },
  {
    word: 'cursory',
    definition: 'done quickly with little attention',
    synonyms: ['brief', 'hasty'],
    antonyms: ['thorough', 'detailed'],
  },
  {
    word: 'vessel',
    definition: 'container or ship',
    synonyms: ['ship', 'container'],
    antonyms: ['void', 'hole'],
  },
  {
    word: 'plume',
    definition: 'large feather or cloud',
    synonyms: ['feather', 'column'],
    antonyms: ['—', '—'],
  },
  {
    word: 'disappointed',
    definition: 'sad because expectations not met',
    synonyms: ['dismayed', 'let-down'],
    antonyms: ['pleased', 'satisfied'],
  },
  {
    word: 'elude',
    definition: 'escape from',
    synonyms: ['evade', 'avoid'],
    antonyms: ['face', 'encounter'],
  },
  {
    word: 'conscientious',
    definition: 'careful and hardworking',
    synonyms: ['diligent', 'thorough'],
    antonyms: ['careless', 'lazy'],
  },
  {
    word: 'repress',
    definition: 'hold down by force',
    synonyms: ['suppress', 'crush'],
    antonyms: ['release', 'free'],
  },
  {
    word: 'cantankerous',
    definition: 'bad-tempered and difficult',
    synonyms: ['grumpy', 'irritable'],
    antonyms: ['good-natured', 'pleasant'],
  },
  {
    word: 'rigorous',
    definition: 'extremely thorough',
    synonyms: ['strict', 'harsh'],
    antonyms: ['lenient', 'gentle'],
  },
  {
    word: 'meagre',
    definition: 'small in amount',
    synonyms: ['scanty', 'poor'],
    antonyms: ['ample', 'plentiful'],
  },
  {
    word: 'ruthless',
    definition: 'showing no mercy',
    synonyms: ['merciless', 'cruel'],
    antonyms: ['kind', 'compassionate'],
  },
  {
    word: 'intangible',
    definition: 'cannot be touched',
    synonyms: ['immaterial', 'abstract'],
    antonyms: ['tangible', 'physical'],
  },
  {
    word: 'commit',
    definition: 'carry out or promise',
    synonyms: ['perform', 'pledge'],
    antonyms: ['avoid', 'withdraw'],
  },
  {
    word: 'loyal',
    definition: 'faithful and true',
    synonyms: ['faithful', 'devoted'],
    antonyms: ['disloyal', 'treacherous'],
  },
  {
    word: 'construe',
    definition: 'interpret meaning',
    synonyms: ['interpret', 'explain'],
    antonyms: ['misunderstand', 'confuse'],
  },
  {
    word: 'prohibit',
    definition: 'stop by law',
    synonyms: ['ban', 'forbid'],
    antonyms: ['permit', 'allow'],
  },
  {
    word: 'lurid',
    definition: 'sensational and shocking',
    synonyms: ['gory', 'gruesome'],
    antonyms: ['restrained', 'dull'],
  },
  {
    word: 'exclaim',
    definition: 'cry out suddenly',
    synonyms: ['shout', 'cry'],
    antonyms: ['mutter', 'whisper'],
  },
  {
    word: 'listlessness',
    definition: 'lack of energy',
    synonyms: ['languor', 'apathy'],
    antonyms: ['energy', 'vitality'],
  },
  {
    word: 'inattentive',
    definition: 'not paying attention',
    synonyms: ['distracted', 'careless'],
    antonyms: ['attentive', 'alert'],
  },
  {
    word: 'dawdle',
    definition: 'waste time moving slowly',
    synonyms: ['linger', 'loiter'],
    antonyms: ['hurry', 'rush'],
  },
  {
    word: 'wasteful',
    definition: 'using more than needed',
    synonyms: ['extravagant', 'profligate'],
    antonyms: ['thrifty', 'economical'],
  },
  {
    word: 'abstract',
    definition: 'existing in thought not physical',
    synonyms: ['theoretical', 'intangible'],
    antonyms: ['concrete', 'physical'],
  },
  {
    word: 'yearned',
    definition: 'longed deeply',
    synonyms: ['longed', 'pined'],
    antonyms: ['disliked', 'spurned'],
  },
  {
    word: 'liberal',
    definition: 'open to new ideas; generous',
    synonyms: ['open-minded', 'generous'],
    antonyms: ['conservative', 'stingy'],
  },
  {
    word: 'rudimentary',
    definition: 'basic and simple',
    synonyms: ['basic', 'elementary'],
    antonyms: ['advanced', 'complex'],
  },
  {
    word: 'unpretentious',
    definition: 'simple and modest',
    synonyms: ['modest', 'plain'],
    antonyms: ['showy', 'pretentious'],
  },
  {
    word: 'belies',
    definition: 'shows to be false',
    synonyms: ['contradicts', 'misrepresents'],
    antonyms: ['proves', 'confirms'],
  },
  {
    word: 'recite',
    definition: 'say aloud from memory',
    synonyms: ['repeat', 'deliver'],
    antonyms: ['forget', 'silence'],
  },
  {
    word: 'prosper',
    definition: 'do well and succeed',
    synonyms: ['flourish', 'thrive'],
    antonyms: ['fail', 'decline'],
  },
  {
    word: 'satisfying',
    definition: 'giving pleasure when achieved',
    synonyms: ['pleasing', 'fulfilling'],
    antonyms: ['frustrating', 'unsatisfying'],
  },
  {
    word: 'bleak',
    definition: 'cold, empty and hopeless',
    synonyms: ['gloomy', 'desolate'],
    antonyms: ['cheerful', 'bright'],
  },
  {
    word: 'sage',
    definition: 'very wise person',
    synonyms: ['wise man', 'philosopher'],
    antonyms: ['fool', 'idiot'],
  },
  {
    word: 'deluded',
    definition: 'believing something untrue',
    synonyms: ['deceived', 'misled'],
    antonyms: ['clear-minded', 'aware'],
  },
  {
    word: 'euphemism',
    definition: 'mild word used instead of harsh',
    synonyms: ['polite term', 'understatement'],
    antonyms: ['dysphemism', 'slur'],
  },
  {
    word: 'imperceptible',
    definition: 'too small to notice',
    synonyms: ['invisible', 'subtle'],
    antonyms: ['obvious', 'noticeable'],
  },
  {
    word: 'complex',
    definition: 'made of many parts',
    synonyms: ['complicated', 'intricate'],
    antonyms: ['simple', 'basic'],
  },
  {
    word: 'pervasive',
    definition: 'spreading everywhere',
    synonyms: ['widespread', 'rampant'],
    antonyms: ['limited', 'localised'],
  },
  {
    word: 'oppose',
    definition: 'act against',
    synonyms: ['resist', 'fight'],
    antonyms: ['support', 'accept'],
  },
  {
    word: 'consideration',
    definition: 'careful thought',
    synonyms: ['thought', 'reflection'],
    antonyms: ['neglect', 'impulsiveness'],
  },
  {
    word: 'breach',
    definition: 'break in rules or wall',
    synonyms: ['violation', 'gap'],
    antonyms: ['observance', 'closure'],
  },
  {
    word: 'correct',
    definition: 'free from error; to fix',
    synonyms: ['right', 'amend'],
    antonyms: ['wrong', 'damage'],
  },
  {
    word: 'plaintiff',
    definition: 'person who brings a lawsuit',
    synonyms: ['complainant', 'claimant'],
    antonyms: ['defendant', 'accused'],
  },
  {
    word: 'aphorism',
    definition: 'short wise saying',
    synonyms: ['proverb', 'maxim'],
    antonyms: ['nonsense', '—'],
  },
  {
    word: 'malicious',
    definition: 'showing desire to harm',
    synonyms: ['spiteful', 'malevolent'],
    antonyms: ['kind', 'benevolent'],
  },
  {
    word: 'censure',
    definition: 'strong official criticism',
    synonyms: ['condemnation', 'rebuke'],
    antonyms: ['praise', 'approval'],
  },
  {
    word: 'anagram',
    definition: 'word made by rearranging letters',
    synonyms: ['word scramble', '—'],
    antonyms: ['—', '—'],
  },
  {
    word: 'ostentatious',
    definition: 'showy and flashy',
    synonyms: ['pretentious', 'flashy'],
    antonyms: ['modest', 'plain'],
  },
  {
    word: 'mere',
    definition: 'no more than',
    synonyms: ['only', 'bare'],
    antonyms: ['significant', 'substantial'],
  },
  {
    word: 'penchant',
    definition: 'strong liking',
    synonyms: ['fondness', 'preference'],
    antonyms: ['dislike', 'aversion'],
  },
  {
    word: 'vernacular',
    definition: 'language spoken by ordinary people',
    synonyms: ['everyday speech', 'dialect'],
    antonyms: ['formal language', 'latin'],
  },
  {
    word: 'implicitly',
    definition: 'without stating directly',
    synonyms: ['tacitly', 'silently'],
    antonyms: ['explicitly', 'openly'],
  },
  {
    word: 'rhetoric',
    definition: 'skill of using language effectively',
    synonyms: ['oratory', 'eloquence'],
    antonyms: ['silence', 'plainness'],
  },
  {
    word: 'ally',
    definition: 'person who supports you',
    synonyms: ['supporter', 'friend'],
    antonyms: ['enemy', 'opponent'],
  },
];
