export const wordBankPart4 = [
  {
    word: 'bipartisan',
    definition: 'supported by two opposing sides',
    synonyms: ['two-party', 'cross-party'],
    antonyms: ['partisan', 'one-sided'],
  },
  {
    word: 'obfuscate',
    definition: 'to make something unclear',
    synonyms: ['confuse', 'blur'],
    antonyms: ['clarify', 'explain'],
  },
  {
    word: 'perturbed',
    definition: 'worried or upset',
    synonyms: ['troubled', 'disturbed'],
    antonyms: ['calm', 'unbothered'],
  },
  {
    word: 'profound',
    definition: 'very deep or important',
    synonyms: ['deep', 'serious'],
    antonyms: ['shallow', 'trivial'],
  },
  {
    word: 'alluring',
    definition: 'very attractive',
    synonyms: ['tempting', 'appealing'],
    antonyms: ['repellent', 'unattractive'],
  },
  {
    word: 'contented',
    definition: 'happy and satisfied',
    synonyms: ['pleased', 'satisfied'],
    antonyms: ['unhappy', 'discontent'],
  },
  {
    word: 'dearth',
    definition: 'a lack of something',
    synonyms: ['scarcity', 'shortage'],
    antonyms: ['abundance', 'plenty'],
  },
  {
    word: 'conciliatory',
    definition: 'meant to make peace',
    synonyms: ['soothing', 'peace-making'],
    antonyms: ['hostile', 'provoking'],
  },
  {
    word: 'reactionary',
    definition: 'strongly against change',
    synonyms: ['conservative', 'backward'],
    antonyms: ['progressive', 'radical'],
  },
  {
    word: 'deceive',
    definition: 'to trick someone',
    synonyms: ['cheat', 'mislead'],
    antonyms: ['be honest', 'reveal'],
  },

  {
    word: 'meddle',
    definition: 'interfere in others’ business',
    synonyms: ['interfere', 'butt in'],
    antonyms: ['mind', 'ignore'],
  },
  {
    word: 'immerse',
    definition: 'put fully into liquid or activity',
    synonyms: ['dip', 'engross'],
    antonyms: ['surface', 'withdraw'],
  },
  {
    word: 'burden',
    definition: 'a heavy load or duty',
    synonyms: ['load', 'weight'],
    antonyms: ['relief', 'lightness'],
  },
  {
    word: 'depravity',
    definition: 'extreme moral wickedness',
    synonyms: ['wickedness', 'corruption'],
    antonyms: ['goodness', 'virtue'],
  },
  {
    word: 'dazzling',
    definition: 'very bright or impressive',
    synonyms: ['brilliant', 'sparkling'],
    antonyms: ['dull', 'drab'],
  },
  {
    word: 'autonomous',
    definition: 'self-governing; independent',
    synonyms: ['independent', 'self-ruled'],
    antonyms: ['dependent', 'controlled'],
  },
  {
    word: 'depot',
    definition: 'a place for storing goods or vehicles',
    synonyms: ['warehouse', 'station'],
    antonyms: ['open-road', 'void'],
  },
  {
    word: 'polarity',
    definition: 'state of having two opposite sides',
    synonyms: ['opposition', 'contrast'],
    antonyms: ['unity', 'similarity'],
  },
  {
    word: 'foundation',
    definition: 'base on which something stands',
    synonyms: ['base', 'footing'],
    antonyms: ['top', 'peak'],
  },
  {
    word: 'limb',
    definition: 'an arm, leg, or large tree branch',
    synonyms: ['arm', 'branch'],
    antonyms: ['trunk', 'body'],
  },

  {
    word: 'enmity',
    definition: 'strong hatred',
    synonyms: ['hatred', 'hostility'],
    antonyms: ['friendship', 'amity'],
  },
  {
    word: 'believe',
    definition: 'accept as true',
    synonyms: ['trust', 'accept'],
    antonyms: ['doubt', 'disbelieve'],
  },
  {
    word: 'docile',
    definition: 'easy to teach or control',
    synonyms: ['obedient', 'gentle'],
    antonyms: ['wild', 'stubborn'],
  },
  {
    word: 'omit',
    definition: 'leave something out',
    synonyms: ['skip', 'exclude'],
    antonyms: ['include', 'insert'],
  },
  {
    word: 'profusion',
    definition: 'large amount',
    synonyms: ['abundance', 'plenty'],
    antonyms: ['scarcity', 'paucity'],
  },
  {
    word: 'aberrant',
    definition: 'not normal',
    synonyms: ['abnormal', 'odd'],
    antonyms: ['normal', 'usual'],
  },
  {
    word: 'committee',
    definition: 'group that makes decisions',
    synonyms: ['panel', 'board'],
    antonyms: ['individual', 'loner'],
  },
  {
    word: 'candidate',
    definition: 'person trying for a job or prize',
    synonyms: ['applicant', 'contender'],
    antonyms: ['employer', 'judge'],
  },
  {
    word: 'revile',
    definition: 'speak about with hate',
    synonyms: ['insult', 'curse'],
    antonyms: ['praise', 'commend'],
  },
  {
    word: 'despise',
    definition: 'feel deep dislike for',
    synonyms: ['hate', 'loathe'],
    antonyms: ['adore', 'admire'],
  },

  {
    word: 'address',
    definition: 'to speak to; a place where you live',
    synonyms: ['speak to', 'talk to'],
    antonyms: ['ignore', 'avoid'],
  },
  {
    word: 'peril',
    definition: 'serious danger',
    synonyms: ['danger', 'risk'],
    antonyms: ['safety', 'security'],
  },
  {
    word: 'surly',
    definition: 'bad-tempered and rude',
    synonyms: ['grumpy', 'cross'],
    antonyms: ['cheerful', 'polite'],
  },
  {
    word: 'mitigate',
    definition: 'make less bad',
    synonyms: ['ease', 'lessen'],
    antonyms: ['worsen', 'aggravate'],
  },
  {
    word: 'minimum',
    definition: 'the least amount',
    synonyms: ['least', 'smallest'],
    antonyms: ['maximum', 'most'],
  },
  {
    word: 'union',
    definition: 'joining together',
    synonyms: ['joining', 'unity'],
    antonyms: ['separation', 'split'],
  },
  {
    word: 'monotonous',
    definition: 'boring because unchanging',
    synonyms: ['dull', 'repetitive'],
    antonyms: ['varied', 'lively'],
  },
  {
    word: 'equivocate',
    definition: 'speak in a way that hides the truth',
    synonyms: ['hedge', 'beat around'],
    antonyms: ['state plainly', 'clarify'],
  },
  {
    word: 'amateur',
    definition: 'doing something for fun, not as a job',
    synonyms: ['non-professional', 'beginner'],
    antonyms: ['professional', 'expert'],
  },
  {
    word: 'termination',
    definition: 'the act of ending something',
    synonyms: ['end', 'finish'],
    antonyms: ['start', 'beginning'],
  },

  {
    word: 'contend',
    definition: 'fight or argue',
    synonyms: ['compete', 'argue'],
    antonyms: ['yield', 'agree'],
  },
  {
    word: 'condescension',
    definition: 'speaking as if you are better',
    synonyms: ['patronising', 'snobbery'],
    antonyms: ['respect', 'humility'],
  },
  {
    word: 'tenacity',
    definition: 'staying power',
    synonyms: ['determination', 'grit'],
    antonyms: ['weakness', 'giving up'],
  },
  {
    word: 'stupor',
    definition: 'state of near-unconsciousness',
    synonyms: ['daze', 'trance'],
    antonyms: ['alertness', 'wakefulness'],
  },
  {
    word: 'certitude',
    definition: 'complete certainty',
    synonyms: ['certainty', 'surety'],
    antonyms: ['doubt', 'uncertainty'],
  },
  {
    word: 'cemetery',
    definition: 'place where people are buried',
    synonyms: ['graveyard', 'churchyard'],
    antonyms: ['—', '—'],
  },
  {
    word: 'deluge',
    definition: 'great flood',
    synonyms: ['flood', 'torrent'],
    antonyms: ['drought', 'dryness'],
  },
  {
    word: 'plagiarize',
    definition: 'copy someone’s work as your own',
    synonyms: ['copy', 'steal'],
    antonyms: ['originate', 'create'],
  },
  {
    word: 'facilitate',
    definition: 'make easier',
    synonyms: ['help', 'ease'],
    antonyms: ['hinder', 'impede'],
  },
  {
    word: 'hierarchy',
    definition: 'system of levels of power',
    synonyms: ['ranking', 'order'],
    antonyms: ['equality', 'flatness'],
  },

  {
    word: 'genre',
    definition: 'type or category',
    synonyms: ['type', 'category'],
    antonyms: ['mixture', 'variety'],
  },
  {
    word: 'vacant',
    definition: 'empty; not occupied',
    synonyms: ['empty', 'unfilled'],
    antonyms: ['occupied', 'full'],
  },
  {
    word: 'impel',
    definition: 'drive someone to act',
    synonyms: ['urge', 'push'],
    antonyms: ['deter', 'stop'],
  },
  {
    word: 'fragrant',
    definition: 'having a pleasant smell',
    synonyms: ['scented', 'perfumed'],
    antonyms: ['smelly', 'odorous'],
  },
  {
    word: 'hubris',
    definition: 'too much pride',
    synonyms: ['arrogance', 'pride'],
    antonyms: ['humility', 'modesty'],
  },
  {
    word: 'legacy',
    definition: 'something left behind after death',
    synonyms: ['inheritance', 'heritage'],
    antonyms: ['debt', 'loss'],
  },
  {
    word: 'desolate',
    definition: 'empty and lonely',
    synonyms: ['bleak', 'barren'],
    antonyms: ['lively', 'populated'],
  },
  {
    word: 'wretch',
    definition: 'an unfortunate or miserable person',
    synonyms: ['poor soul', 'unhappy one'],
    antonyms: ['lucky one', 'winner'],
  },
  {
    word: 'glutton',
    definition: 'person who eats too much',
    synonyms: ['overeater', 'gorge'],
    antonyms: ['moderate eater', 'picker'],
  },
  {
    word: 'devious',
    definition: 'sneaky and dishonest',
    synonyms: ['sly', 'tricky'],
    antonyms: ['honest', 'straight'],
  },

  {
    word: 'precipitate',
    definition: 'cause something to happen quickly',
    synonyms: ['trigger', 'spark'],
    antonyms: ['delay', 'slow'],
  },
  {
    word: 'panache',
    definition: 'stylish confidence',
    synonyms: ['flair', 'style'],
    antonyms: ['clumsiness', 'awkwardness'],
  },
  {
    word: 'intuitive',
    definition: 'understood without reasoning',
    synonyms: ['instinctive', 'natural'],
    antonyms: ['learned', 'logical'],
  },
  {
    word: 'meant',
    definition: 'intended',
    synonyms: ['intended', 'planned'],
    antonyms: ['accidental', 'chance'],
  },
  {
    word: 'rogue',
    definition: 'dishonest or wild person',
    synonyms: ['rascal', 'villain'],
    antonyms: ['hero', 'gentleman'],
  },
  {
    word: 'soldier',
    definition: 'member of an army',
    synonyms: ['troop', 'fighter'],
    antonyms: ['civilian', 'non-combatant'],
  },
  {
    word: 'verbose',
    definition: 'using too many words',
    synonyms: ['wordy', 'long-winded'],
    antonyms: ['brief', 'concise'],
  },
  {
    word: 'restore',
    definition: 'bring back to former state',
    synonyms: ['repair', 'renew'],
    antonyms: ['damage', 'ruin'],
  },
  {
    word: 'astounding',
    definition: 'very surprising',
    synonyms: ['amazing', 'stunning'],
    antonyms: ['ordinary', 'dull'],
  },
  {
    word: 'surpass',
    definition: 'do better than',
    synonyms: ['exceed', 'outdo'],
    antonyms: ['fall short', 'fail'],
  },

  {
    word: 'implicate',
    definition: 'show someone is involved',
    synonyms: ['involve', 'link'],
    antonyms: ['clear', 'absolve'],
  },
  {
    word: 'impede',
    definition: 'slow down or block',
    synonyms: ['hinder', 'block'],
    antonyms: ['help', 'assist'],
  },
  {
    word: 'prelude',
    definition: 'an introduction',
    synonyms: ['intro', 'opening'],
    antonyms: ['finale', 'conclusion'],
  },
  {
    word: 'abundant',
    definition: 'present in large amounts',
    synonyms: ['plentiful', 'ample'],
    antonyms: ['scarce', 'few'],
  },
  {
    word: 'inherent',
    definition: 'built-in and natural',
    synonyms: ['innate', 'natural'],
    antonyms: ['acquired', 'learned'],
  },
  {
    word: 'reside',
    definition: 'live somewhere',
    synonyms: ['live', 'dwell'],
    antonyms: ['leave', 'depart'],
  },
  {
    word: 'foresight',
    definition: 'ability to plan ahead',
    synonyms: ['vision', 'planning'],
    antonyms: ['short-sightedness', 'impulsiveness'],
  },
  {
    word: 'ramification',
    definition: 'result or consequence',
    synonyms: ['consequence', 'outcome'],
    antonyms: ['cause', 'source'],
  },
  {
    word: 'beautiful',
    definition: 'very pleasing to look at',
    synonyms: ['pretty', 'lovely'],
    antonyms: ['ugly', 'plain'],
  },
  {
    word: 'slander',
    definition: 'false spoken attack on reputation',
    synonyms: ['defamation', 'libel'],
    antonyms: ['praise', 'defence'],
  },

  {
    word: 'braggart',
    definition: 'someone who boasts a lot',
    synonyms: ['boaster', 'show-off'],
    antonyms: ['modest person', 'humble'],
  },
  {
    word: 'inaudible',
    definition: 'impossible to hear',
    synonyms: ['silent', 'mute'],
    antonyms: ['loud', 'audible'],
  },
  {
    word: 'soothing',
    definition: 'making calm',
    synonyms: ['calming', 'comforting'],
    antonyms: ['irritating', 'agitating'],
  },
  {
    word: 'bane',
    definition: 'something that causes ruin',
    synonyms: ['curse', 'plague'],
    antonyms: ['blessing', 'boon'],
  },
  {
    word: 'modest',
    definition: 'not boasting; moderate',
    synonyms: ['humble', 'simple'],
    antonyms: ['proud', 'flashy'],
  },
  {
    word: 'uniformity',
    definition: 'state of being the same',
    synonyms: ['sameness', 'consistency'],
    antonyms: ['variety', 'diversity'],
  },
  {
    word: 'zealot',
    definition: 'person with extreme enthusiasm',
    synonyms: ['fanatic', 'extremist'],
    antonyms: ['moderate', 'sceptic'],
  },
  {
    word: 'habitable',
    definition: 'good enough to live in',
    synonyms: ['livable', 'fit'],
    antonyms: ['uninhabitable', 'unfit'],
  },
  {
    word: 'merchant',
    definition: 'person who buys and sells goods',
    synonyms: ['trader', 'seller'],
    antonyms: ['customer', 'buyer'],
  },
  {
    word: 'reprove',
    definition: 'criticise gently',
    synonyms: ['scold', 'rebuke'],
    antonyms: ['praise', 'commend'],
  },

  {
    word: 'pew',
    definition: 'bench seat in a church',
    synonyms: ['bench', 'seat'],
    antonyms: ['—', '—'],
  },
  {
    word: 'amply',
    definition: 'more than enough',
    synonyms: ['plentifully', 'richly'],
    antonyms: ['scarcely', 'barely'],
  },
  {
    word: 'assiduous',
    definition: 'working very hard',
    synonyms: ['diligent', 'hard-working'],
    antonyms: ['lazy', 'idle'],
  },
  {
    word: 'candid',
    definition: 'honest and open',
    synonyms: ['frank', 'open'],
    antonyms: ['secretive', 'guarded'],
  },
  {
    word: 'feign',
    definition: 'pretend to feel',
    synonyms: ['pretend', 'fake'],
    antonyms: ['be genuine', 'show'],
  },
  {
    word: 'abode',
    definition: 'home; place where someone lives',
    synonyms: ['home', 'house'],
    antonyms: ['office', 'workplace'],
  },
  {
    word: 'illuminate',
    definition: 'light up; explain clearly',
    synonyms: ['light', 'clarify'],
    antonyms: ['darken', 'confuse'],
  },
  {
    word: 'supplicate',
    definition: 'ask for humbly',
    synonyms: ['beg', 'plead'],
    antonyms: ['command', 'demand'],
  },
  {
    word: 'vile',
    definition: 'extremely nasty',
    synonyms: ['horrible', 'foul'],
    antonyms: ['pleasant', 'delightful'],
  },
  {
    word: 'threadbare',
    definition: 'worn and thin',
    synonyms: ['worn-out', 'shabby'],
    antonyms: ['new', 'fresh'],
  },

  {
    word: 'demote',
    definition: 'move to a lower rank',
    synonyms: ['downgrade', 'reduce'],
    antonyms: ['promote', 'advance'],
  },
  {
    word: 'obsequious',
    definition: 'too eager to please',
    synonyms: ['servile', 'fawning'],
    antonyms: ['assertive', 'independent'],
  },
  {
    word: 'disperse',
    definition: 'scatter in different directions',
    synonyms: ['scatter', 'spread'],
    antonyms: ['gather', 'collect'],
  },
  {
    word: 'endure',
    definition: 'keep going through hardship',
    synonyms: ['bear', 'persist'],
    antonyms: ['quit', 'surrender'],
  },
  {
    word: 'dissonance',
    definition: 'lack of harmony',
    synonyms: ['discord', 'clash'],
    antonyms: ['harmony', 'agreement'],
  },
  {
    word: 'injustice',
    definition: 'lack of fairness',
    synonyms: ['unfairness', 'wrong'],
    antonyms: ['justice', 'fairness'],
  },
  {
    word: 'apprise',
    definition: 'inform someone',
    synonyms: ['inform', 'tell'],
    antonyms: ['hide', 'conceal'],
  },
  {
    word: 'interior',
    definition: 'inside part',
    synonyms: ['inside', 'inner'],
    antonyms: ['exterior', 'outside'],
  },
  {
    word: 'custom',
    definition: 'usual practice',
    synonyms: ['tradition', 'habit'],
    antonyms: ['innovation', 'change'],
  },
  {
    word: 'serene',
    definition: 'calm and peaceful',
    synonyms: ['calm', 'tranquil'],
    antonyms: ['chaotic', 'noisy'],
  },

  {
    word: 'operandi',
    definition: 'manner of working (as in modus operandi)',
    synonyms: ['method', 'way'],
    antonyms: ['accident', 'chance'],
  },
  {
    word: 'contrite',
    definition: 'feeling sorry for wrongdoing',
    synonyms: ['sorry', 'remorseful'],
    antonyms: ['unrepentant', 'shameless'],
  },
  {
    word: 'combat',
    definition: 'fight or battle',
    synonyms: ['fight', 'battle'],
    antonyms: ['peace', 'truce'],
  },
  {
    word: 'extinction',
    definition: 'dying out completely',
    synonyms: ['die-out', 'disappearance'],
    antonyms: ['survival', 'existence'],
  },
  {
    word: 'foster',
    definition: 'help something grow',
    synonyms: ['encourage', 'nurture'],
    antonyms: ['hinder', 'neglect'],
  },
  {
    word: 'semantics',
    definition: 'study of word meanings',
    synonyms: ['meaning', 'definitions'],
    antonyms: ['—', '—'],
  },
  {
    word: 'appearance',
    definition: 'the way someone or something looks',
    synonyms: ['look', 'image'],
    antonyms: ['reality', 'substance'],
  },
  {
    word: 'dispassionate',
    definition: 'not influenced by emotion',
    synonyms: ['calm', 'neutral'],
    antonyms: ['biased', 'emotional'],
  },
  {
    word: 'disinclination',
    definition: 'not wanting to do something',
    synonyms: ['unwillingness', 'aversion'],
    antonyms: ['eagerness', 'enthusiasm'],
  },
  {
    word: 'significant',
    definition: 'important or meaningful',
    synonyms: ['important', 'major'],
    antonyms: ['minor', 'trivial'],
  },

  {
    word: 'foe',
    definition: 'enemy',
    synonyms: ['enemy', 'opponent'],
    antonyms: ['friend', 'ally'],
  },
  {
    word: 'sanctuary',
    definition: 'safe place',
    synonyms: ['refuge', 'haven'],
    antonyms: ['danger', 'peril'],
  },
  {
    word: 'spendthrift',
    definition: 'person who wastes money',
    synonyms: ['waster', 'big-spender'],
    antonyms: ['saver', 'thrifty'],
  },
  {
    word: 'exhaustive',
    definition: 'leaving nothing out',
    synonyms: ['complete', 'thorough'],
    antonyms: ['partial', 'incomplete'],
  },
  {
    word: 'distress',
    definition: 'great pain or worry',
    synonyms: ['anguish', 'suffering'],
    antonyms: ['comfort', 'relief'],
  },
  {
    word: 'abstruse',
    definition: 'hard to understand',
    synonyms: ['complex', 'obscure'],
    antonyms: ['clear', 'simple'],
  },
  {
    word: 'genial',
    definition: 'friendly and cheerful',
    synonyms: ['friendly', 'cheerful'],
    antonyms: ['cold', 'unfriendly'],
  },
  {
    word: 'exemplify',
    definition: 'show an example of',
    synonyms: ['illustrate', 'show'],
    antonyms: ['obscure', 'hide'],
  },
  {
    word: 'reveal',
    definition: 'make known',
    synonyms: ['show', 'uncover'],
    antonyms: ['hide', 'conceal'],
  },
  {
    word: 'succinct',
    definition: 'expressed in few words',
    synonyms: ['brief', 'concise'],
    antonyms: ['wordy', 'verbose'],
  },

  {
    word: 'hybrid',
    definition: 'mix of two different things',
    synonyms: ['mix', 'blend'],
    antonyms: ['pure', 'single'],
  },
  {
    word: 'sophisticated',
    definition: 'complex or worldly',
    synonyms: ['cultured', 'complex'],
    antonyms: ['simple', 'naïve'],
  },
  {
    word: 'wary',
    definition: 'careful about danger',
    synonyms: ['cautious', 'alert'],
    antonyms: ['reckless', 'trusting'],
  },
  {
    word: 'hiatus',
    definition: 'a break or gap',
    synonyms: ['pause', 'gap'],
    antonyms: ['continuation', 'flow'],
  },
  {
    word: 'sanction',
    definition: 'official approval or penalty',
    synonyms: ['approval', 'penalty'],
    antonyms: ['ban', 'forbid'],
  },
  {
    word: 'dubious',
    definition: 'doubtful or suspicious',
    synonyms: ['doubtful', 'questionable'],
    antonyms: ['certain', 'clear'],
  },
  {
    word: 'painstaking',
    definition: 'showing great care',
    synonyms: ['careful', 'meticulous'],
    antonyms: ['careless', 'sloppy'],
  },
  {
    word: 'pact',
    definition: 'formal agreement',
    synonyms: ['agreement', 'deal'],
    antonyms: ['conflict', 'dispute'],
  },
  {
    word: 'furtive',
    definition: 'done secretly',
    synonyms: ['secret', 'sly'],
    antonyms: ['open', 'obvious'],
  },
  {
    word: 'ebb',
    definition: 'move back or lessen',
    synonyms: ['recede', 'diminish'],
    antonyms: ['flow', 'increase'],
  },

  {
    word: 'endorse',
    definition: 'publicly support',
    synonyms: ['support', 'approve'],
    antonyms: ['oppose', 'reject'],
  },
  {
    word: 'contest',
    definition: 'competition or to dispute',
    synonyms: ['competition', 'challenge'],
    antonyms: ['agreement', 'accept'],
  },
  {
    word: 'clement',
    definition: 'mild and kind',
    synonyms: ['gentle', 'lenient'],
    antonyms: ['harsh', 'severe'],
  },
  {
    word: 'vicarious',
    definition: 'experienced through someone else',
    synonyms: ['indirect', 'second-hand'],
    antonyms: ['direct', 'first-hand'],
  },
  {
    word: 'indulge',
    definition: 'give in to desire',
    synonyms: ['treat', 'spoil'],
    antonyms: ['deny', 'restrain'],
  },
  {
    word: 'sagacious',
    definition: 'wise and sensible',
    synonyms: ['wise', 'shrewd'],
    antonyms: ['foolish', 'silly'],
  },
  {
    word: 'homograph',
    definition: 'word spelled same but different meaning',
    synonyms: ['same-spelling', '—'],
    antonyms: ['homophone', '—'],
  },
  {
    word: 'library',
    definition: 'place with books to borrow',
    synonyms: ['book room', 'archive'],
    antonyms: ['—', '—'],
  },
  {
    word: 'object',
    definition: 'thing you can see or touch; to disagree',
    synonyms: ['item', 'thing'],
    antonyms: ['nothing', 'approve'],
  },
  {
    word: 'ambition',
    definition: 'strong desire to succeed',
    synonyms: ['drive', 'aspiration'],
    antonyms: ['apathy', 'indifference'],
  },

  {
    word: 'eponym',
    definition: 'name of a person used for something else',
    synonyms: ['namesake', 'title'],
    antonyms: ['—', '—'],
  },
  {
    word: 'din',
    definition: 'loud continuous noise',
    synonyms: ['noise', 'clamour'],
    antonyms: ['silence', 'hush'],
  },
  {
    word: 'criterion',
    definition: 'standard used to judge something',
    synonyms: ['standard', 'measure'],
    antonyms: ['guess', 'speculation'],
  },
  {
    word: 'copious',
    definition: 'in large amounts',
    synonyms: ['plentiful', 'abundant'],
    antonyms: ['scarce', 'few'],
  },
  {
    word: 'demolished',
    definition: 'pulled down or destroyed',
    synonyms: ['destroyed', 'wrecked'],
    antonyms: ['built', 'constructed'],
  },
  {
    word: 'obdurate',
    definition: 'stubbornly refusing to change',
    synonyms: ['stubborn', 'unyielding'],
    antonyms: ['flexible', 'soft'],
  },
  {
    word: 'dispute',
    definition: 'argument or disagreement',
    synonyms: ['argument', 'row'],
    antonyms: ['agreement', 'accord'],
  },
  {
    word: 'altitude',
    definition: 'height above sea level',
    synonyms: ['height', 'elevation'],
    antonyms: ['depth', 'lowland'],
  },
  {
    word: 'untoward',
    definition: 'unexpected and inappropriate',
    synonyms: ['improper', 'unfortunate'],
    antonyms: ['proper', 'fitting'],
  },
  {
    word: 'conscious',
    definition: 'aware and awake',
    synonyms: ['aware', 'awake'],
    antonyms: ['unconscious', 'asleep'],
  },

  {
    word: 'conceited',
    definition: 'too proud of oneself',
    synonyms: ['proud', 'vain'],
    antonyms: ['modest', 'humble'],
  },
  {
    word: 'tractable',
    definition: 'easy to control',
    synonyms: ['manageable', 'obedient'],
    antonyms: ['unruly', 'stubborn'],
  },
  {
    word: 'distant',
    definition: 'far away; unfriendly',
    synonyms: ['far', 'remote'],
    antonyms: ['near', 'close'],
  },
  {
    word: 'precocious',
    definition: 'advanced for one’s age',
    synonyms: ['advanced', 'gifted'],
    antonyms: ['slow', 'backward'],
  },
  {
    word: 'fluctuate',
    definition: 'keep changing',
    synonyms: ['vary', 'waver'],
    antonyms: ['stabilise', 'remain'],
  },
  {
    word: 'business',
    definition: 'work of buying and selling',
    synonyms: ['trade', 'commerce'],
    antonyms: ['leisure', 'fun'],
  },
  {
    word: 'repentant',
    definition: 'sorry for wrongdoing',
    synonyms: ['sorry', 'contrite'],
    antonyms: ['unrepentant', 'shameless'],
  },
  {
    word: 'strenuous',
    definition: 'needing great effort',
    synonyms: ['hard', 'arduous'],
    antonyms: ['easy', 'light'],
  },
  {
    word: 'heeding',
    definition: 'paying attention to',
    synonyms: ['listening', 'noticing'],
    antonyms: ['ignoring', 'disregarding'],
  },
  {
    word: 'rigueur',
    definition: "strictness (as in 'de rigueur')",
    synonyms: ['fashionable', 'required'],
    antonyms: ['optional', 'unfashionable'],
  },

  {
    word: 'eloquence',
    definition: 'skill in fluent speaking',
    synonyms: ['fluency', 'articulacy'],
    antonyms: ['awkwardness', 'inarticulacy'],
  },
  {
    word: 'voyeurism',
    definition: 'watching others secretly',
    synonyms: ['peeping', 'spying'],
    antonyms: ['openness', 'disinterest'],
  },
  {
    word: 'dispel',
    definition: 'drive away',
    synonyms: ['banish', 'scatter'],
    antonyms: ['gather', 'collect'],
  },
  {
    word: 'succumb',
    definition: 'give in to something',
    synonyms: ['yield', 'give in'],
    antonyms: ['resist', 'withstand'],
  },
  {
    word: 'vivre',
    definition: "life (as in 'joie de vivre')",
    synonyms: ['life', 'living'],
    antonyms: ['death', 'misery'],
  },
  {
    word: 'caution',
    definition: 'care taken to avoid danger',
    synonyms: ['care', 'prudence'],
    antonyms: ['recklessness', 'risk'],
  },
  {
    word: 'oblige',
    definition: 'do a favour for',
    synonyms: ['help', 'accommodate'],
    antonyms: ['refuse', 'deny'],
  },
  {
    word: 'problematic',
    definition: 'causing problems',
    synonyms: ['tricky', 'difficult'],
    antonyms: ['easy', 'simple'],
  },
  {
    word: 'anguish',
    definition: 'severe pain or sorrow',
    synonyms: ['agony', 'torment'],
    antonyms: ['joy', 'comfort'],
  },
  {
    word: 'attached',
    definition: 'joined or emotionally close',
    synonyms: ['joined', 'fond'],
    antonyms: ['detached', 'separate'],
  },

  {
    word: 'darn',
    definition: 'mend a hole in cloth',
    synonyms: ['mend', 'repair'],
    antonyms: ['tear', 'rip'],
  },
  {
    word: 'antidote',
    definition: 'medicine that reverses poison',
    synonyms: ['cure', 'remedy'],
    antonyms: ['poison', 'toxin'],
  },
  {
    word: 'redundant',
    definition: 'no longer needed',
    synonyms: ['unnecessary', 'spare'],
    antonyms: ['necessary', 'essential'],
  },
  {
    word: 'stimulating',
    definition: 'interesting and exciting',
    synonyms: ['exciting', 'inspiring'],
    antonyms: ['boring', 'dull'],
  },
  {
    word: 'prevalent',
    definition: 'widely existing',
    synonyms: ['widespread', 'common'],
    antonyms: ['rare', 'uncommon'],
  },
  {
    word: 'affable',
    definition: 'friendly and easy to talk to',
    synonyms: ['friendly', 'pleasant'],
    antonyms: ['rude', 'unfriendly'],
  },
  {
    word: 'courageous',
    definition: 'brave',
    synonyms: ['brave', 'bold'],
    antonyms: ['cowardly', 'fearful'],
  },
  {
    word: 'abominable',
    definition: 'very bad and nasty',
    synonyms: ['horrible', 'terrible'],
    antonyms: ['wonderful', 'delightful'],
  },
  {
    word: 'rare',
    definition: 'not common',
    synonyms: ['uncommon', 'scarce'],
    antonyms: ['common', 'frequent'],
  },
  {
    word: 'orator',
    definition: 'skilled public speaker',
    synonyms: ['speaker', 'lecturer'],
    antonyms: ['listener', 'mute'],
  },

  {
    word: 'grandiose',
    definition: 'grand in an exaggerated way',
    synonyms: ['pretentious', 'flashy'],
    antonyms: ['simple', 'modest'],
  },
  {
    word: 'available',
    definition: 'ready for use',
    synonyms: ['ready', 'free'],
    antonyms: ['unavailable', 'busy'],
  },
  {
    word: 'arbitrary',
    definition: 'based on random choice',
    synonyms: ['random', 'chance'],
    antonyms: ['planned', 'reasoned'],
  },
  {
    word: 'fiasco',
    definition: 'complete failure',
    synonyms: ['disaster', 'flop'],
    antonyms: ['success', 'triumph'],
  },
  {
    word: 'exquisite',
    definition: 'extremely beautiful',
    synonyms: ['beautiful', 'delicate'],
    antonyms: ['ugly', 'crude'],
  },
  {
    word: 'meanders',
    definition: 'moves in a winding way',
    synonyms: ['wanders', 'twists'],
    antonyms: ['goes straight', 'directs'],
  },
  {
    word: 'gratifying',
    definition: 'pleasing and satisfying',
    synonyms: ['satisfying', 'rewarding'],
    antonyms: ['disappointing', 'frustrating'],
  },
  {
    word: 'self-righteous',
    definition: 'believing you are always right',
    synonyms: ['smug', 'pious'],
    antonyms: ['humble', 'modest'],
  },
  {
    word: 'terse',
    definition: 'using very few words',
    synonyms: ['brief', 'concise'],
    antonyms: ['wordy', 'verbose'],
  },
  {
    word: 'abate',
    definition: 'become less strong',
    synonyms: ['lessen', 'ease'],
    antonyms: ['increase', 'intensify'],
  },
];
