export const wordBankPart8 = [
  {
    word: 'vindictive',
    definition: 'wanting to get revenge',
    synonyms: ['revengeful', 'spiteful'],
    antonyms: ['forgiving', 'kind'],
  },
  {
    word: 'insinuate',
    definition: 'hint something bad slyly',
    synonyms: ['imply', 'suggest'],
    antonyms: ['state', 'declare'],
  },
  {
    word: 'contemptuous',
    definition: 'showing deep dislike',
    synonyms: ['scornful', 'disdainful'],
    antonyms: ['respectful', 'admiring'],
  },
  {
    word: 'devote',
    definition: 'give time or effort to',
    synonyms: ['dedicate', 'commit'],
    antonyms: ['neglect', 'ignore'],
  },
  {
    word: 'extol',
    definition: 'praise highly',
    synonyms: ['praise', 'laud'],
    antonyms: ['criticise', 'blame'],
  },
  {
    word: 'communicate',
    definition: 'share information',
    synonyms: ['convey', 'tell'],
    antonyms: ['withhold', 'hide'],
  },
  {
    word: 'negate',
    definition: 'make something have no effect',
    synonyms: ['cancel', 'nullify'],
    antonyms: ['confirm', 'validate'],
  },
  {
    word: 'restaurant',
    definition: 'place where you buy meals',
    synonyms: ['eatery', 'café'],
    antonyms: ['kitchen', 'home'],
  },
  {
    word: 'chauvinist',
    definition: 'person with extreme loyalty to own group',
    synonyms: ['bigot', 'jingoist'],
    antonyms: ['egalitarian', 'fair-minded'],
  },
  {
    word: 'jewel',
    definition: 'precious stone',
    synonyms: ['gem', 'stone'],
    antonyms: ['pebble', 'rock'],
  },
  {
    word: 'pivotal',
    definition: 'very important',
    synonyms: ['crucial', 'key'],
    antonyms: ['minor', 'trivial'],
  },
  {
    word: 'instigate',
    definition: 'start something, often trouble',
    synonyms: ['provoke', 'spark'],
    antonyms: ['halt', 'prevent'],
  },
  {
    word: 'taxing',
    definition: 'very tiring',
    synonyms: ['demanding', 'arduous'],
    antonyms: ['easy', 'light'],
  },
  {
    word: 'lean',
    definition: 'thin; bend sideways',
    synonyms: ['slim', 'tilt'],
    antonyms: ['fat', 'upright'],
  },
  {
    word: 'boastful',
    definition: 'talking too proudly',
    synonyms: ['bragging', 'conceited'],
    antonyms: ['modest', 'humble'],
  },
  {
    word: 'stance',
    definition: 'the way you stand; an opinion',
    synonyms: ['position', 'view'],
    antonyms: ['movement', 'indecision'],
  },
  {
    word: 'leisure',
    definition: 'free time',
    synonyms: ['relaxation', 'rest'],
    antonyms: ['work', 'labour'],
  },
  {
    word: 'intricate',
    definition: 'full of fine detail',
    synonyms: ['complex', 'elaborate'],
    antonyms: ['simple', 'plain'],
  },
  {
    word: 'conspicuous',
    definition: 'easy to notice',
    synonyms: ['noticeable', 'obvious'],
    antonyms: ['hidden', 'inconspicuous'],
  },
  {
    word: 'petulant',
    definition: 'easily annoyed like a child',
    synonyms: ['irritable', 'sulky'],
    antonyms: ['cheerful', 'pleasant'],
  },

  {
    word: 'lassitude',
    definition: 'lack of energy',
    synonyms: ['tiredness', 'fatigue'],
    antonyms: ['vigour', 'energy'],
  },
  {
    word: 'disparage',
    definition: 'speak badly of',
    synonyms: ['belittle', 'mock'],
    antonyms: ['praise', 'commend'],
  },
  {
    word: 'intrinsic',
    definition: 'belonging naturally',
    synonyms: ['innate', 'inherent'],
    antonyms: ['extrinsic', 'external'],
  },
  {
    word: 'profess',
    definition: 'declare openly',
    synonyms: ['state', 'claim'],
    antonyms: ['deny', 'hide'],
  },
  {
    word: 'emphasis',
    definition: 'special importance',
    synonyms: ['stress', 'importance'],
    antonyms: ['insignificance', 'triviality'],
  },
  {
    word: 'unanimous',
    definition: 'all in agreement',
    synonyms: ['agreed', 'united'],
    antonyms: ['divided', 'split'],
  },
  {
    word: 'exacting',
    definition: 'demanding great effort',
    synonyms: ['strict', 'tough'],
    antonyms: ['lenient', 'easy'],
  },
  {
    word: 'shallow',
    definition: 'not deep',
    synonyms: ['surface', 'superficial'],
    antonyms: ['deep', 'profound'],
  },
  {
    word: 'croak',
    definition: 'deep rough sound of a frog',
    synonyms: ['ribbit', 'caw'],
    antonyms: ['chirp', 'silence'],
  },
  {
    word: 'integral',
    definition: 'necessary to make whole',
    synonyms: ['essential', 'vital'],
    antonyms: ['optional', 'extra'],
  },

  {
    word: 'coercion',
    definition: 'forcing someone to act',
    synonyms: ['pressure', 'compulsion'],
    antonyms: ['persuasion', 'option'],
  },
  {
    word: 'perplexed',
    definition: 'very puzzled',
    synonyms: ['confused', 'baffled'],
    antonyms: ['clear', 'certain'],
  },
  {
    word: 'cynic',
    definition: 'person who doubts good motives',
    synonyms: ['sceptic', 'doubter'],
    antonyms: ['optimist', 'believer'],
  },
  {
    word: 'apprehension',
    definition: 'nervous fear',
    synonyms: ['anxiety', 'dread'],
    antonyms: ['confidence', 'calm'],
  },
  {
    word: 'stout',
    definition: 'strong and thick; plump',
    synonyms: ['solid', 'stocky'],
    antonyms: ['slim', 'weak'],
  },
  {
    word: 'inaugural',
    definition: 'first in a series',
    synonyms: ['opening', 'initial'],
    antonyms: ['final', 'closing'],
  },
  {
    word: 'existence',
    definition: 'state of being alive',
    synonyms: ['being', 'life'],
    antonyms: ['non-existence', 'absence'],
  },
  {
    word: 'obtuse',
    definition: 'slow to understand',
    synonyms: ['dull', 'blunt'],
    antonyms: ['sharp', 'clever'],
  },
  {
    word: 'decisive',
    definition: 'able to decide quickly',
    synonyms: ['determined', 'firm'],
    antonyms: ['hesitant', 'indecisive'],
  },
  {
    word: 'excitement',
    definition: 'great eagerness',
    synonyms: ['thrill', 'enthusiasm'],
    antonyms: ['boredom', 'calm'],
  },

  {
    word: 'fracas',
    definition: 'noisy fight',
    synonyms: ['brawl', 'melee'],
    antonyms: ['peace', 'calm'],
  },
  {
    word: 'discursive',
    definition: 'moving from topic to topic',
    synonyms: ['rambling', 'wandering'],
    antonyms: ['focused', 'concise'],
  },
  {
    word: 'inert',
    definition: 'not moving',
    synonyms: ['still', 'inactive'],
    antonyms: ['active', 'lively'],
  },
  {
    word: 'frail',
    definition: 'weak and delicate',
    synonyms: ['weak', 'fragile'],
    antonyms: ['strong', 'robust'],
  },
  {
    word: 'emanate',
    definition: 'come out from',
    synonyms: ['radiate', 'flow'],
    antonyms: ['absorb', 'withdraw'],
  },
  {
    word: 'stress',
    definition: 'pressure or worry',
    synonyms: ['strain', 'tension'],
    antonyms: ['relaxation', 'ease'],
  },
  {
    word: 'angst',
    definition: 'strong anxious feeling',
    synonyms: ['anxiety', 'worry'],
    antonyms: ['peace', 'serenity'],
  },
  {
    word: 'recant',
    definition: 'take back a belief',
    synonyms: ['withdraw', 'retract'],
    antonyms: ['confirm', 'repeat'],
  },
  {
    word: 'gentility',
    definition: 'polite manners',
    synonyms: ['refinement', 'courtesy'],
    antonyms: ['rudeness', 'vulgarity'],
  },
  {
    word: 'epiphany',
    definition: 'sudden realisation',
    synonyms: ['revelation', 'insight'],
    antonyms: ['confusion', 'ignorance'],
  },

  {
    word: 'unprecedented',
    definition: 'never happened before',
    synonyms: ['unique', 'novel'],
    antonyms: ['usual', 'common'],
  },
  {
    word: 'malevolent',
    definition: 'wishing harm',
    synonyms: ['spiteful', 'evil'],
    antonyms: ['benevolent', 'kind'],
  },
  {
    word: 'morbid',
    definition: 'interested in death and gloom',
    synonyms: ['gloomy', 'gruesome'],
    antonyms: ['cheerful', 'healthy'],
  },
  {
    word: 'grieve',
    definition: 'feel deep sorrow',
    synonyms: ['mourn', 'lament'],
    antonyms: ['rejoice', 'celebrate'],
  },
  {
    word: 'ambivalence',
    definition: 'mixed feelings',
    synonyms: ['uncertainty', 'doubt'],
    antonyms: ['certainty', 'clarity'],
  },
  {
    word: 'avowed',
    definition: 'openly declared',
    synonyms: ['stated', 'admitted'],
    antonyms: ['secret', 'hidden'],
  },
  {
    word: 'diminution',
    definition: 'reduction in size',
    synonyms: ['decrease', 'lessening'],
    antonyms: ['increase', 'growth'],
  },
  {
    word: 'forbid',
    definition: 'order not to do',
    synonyms: ['ban', 'prohibit'],
    antonyms: ['allow', 'permit'],
  },
  {
    word: 'collaborate',
    definition: 'work together',
    synonyms: ['co-operate', 'team up'],
    antonyms: ['oppose', 'hinder'],
  },
  {
    word: 'lieu',
    definition: 'place or stead',
    synonyms: ['instead', 'substitute'],
    antonyms: ['lack', 'absence'],
  },

  {
    word: 'influence',
    definition: 'power to affect',
    synonyms: ['sway', 'impact'],
    antonyms: ['weakness', 'impotence'],
  },
  {
    word: 'hoax',
    definition: 'trick made to fool',
    synonyms: ['prank', 'fraud'],
    antonyms: ['truth', 'reality'],
  },
  {
    word: 'figurative',
    definition: 'not literal; symbolic',
    synonyms: ['metaphorical', 'symbolic'],
    antonyms: ['literal', 'plain'],
  },
  {
    word: 'genealogy',
    definition: 'study of family history',
    synonyms: ['family tree', 'ancestry'],
    antonyms: ['descendants', 'progeny'],
  },
  {
    word: 'flawed',
    definition: 'having mistakes',
    synonyms: ['faulty', 'imperfect'],
    antonyms: ['perfect', 'sound'],
  },
  {
    word: 'mnemonic',
    definition: 'memory aid',
    synonyms: ['memory help', 'prompt'],
    antonyms: ['forgetter', '—'],
  },
  {
    word: 'cordial',
    definition: 'warm and friendly',
    synonyms: ['friendly', 'warm'],
    antonyms: ['cold', 'hostile'],
  },
  {
    word: 'incite',
    definition: 'stir up action',
    synonyms: ['provoke', 'urge'],
    antonyms: ['deter', 'calm'],
  },
  {
    word: 'reap',
    definition: 'gather a crop or result',
    synonyms: ['harvest', 'collect'],
    antonyms: ['sow', 'plant'],
  },
  {
    word: 'detractors',
    definition: 'people who criticise',
    synonyms: ['critics', 'naysayers'],
    antonyms: ['supporters', 'fans'],
  },

  {
    word: 'arrogance',
    definition: 'thinking you are better',
    synonyms: ['pride', 'conceit'],
    antonyms: ['humility', 'meekness'],
  },
  {
    word: 'enterprise',
    definition: 'bold business or project',
    synonyms: ['initiative', 'venture'],
    antonyms: ['idleness', 'inactivity'],
  },
  {
    word: 'front',
    definition: 'leading position; face of something',
    synonyms: ['fore', 'surface'],
    antonyms: ['back', 'rear'],
  },
  {
    word: 'simile',
    definition: 'comparison using like or as',
    synonyms: ['comparison', 'image'],
    antonyms: ['literal statement', '—'],
  },
  {
    word: 'bemused',
    definition: 'puzzled and confused',
    synonyms: ['confused', 'bewildered'],
    antonyms: ['clear-headed', 'alert'],
  },
  {
    word: 'porous',
    definition: 'full of tiny holes',
    synonyms: ['permeable', 'spongy'],
    antonyms: ['solid', 'impermeable'],
  },
  {
    word: 'absorbed',
    definition: 'deeply interested',
    synonyms: ['engrossed', 'immersed'],
    antonyms: ['bored', 'distracted'],
  },
  {
    word: 'prejudice',
    definition: 'unfair dislike',
    synonyms: ['bias', 'bigotry'],
    antonyms: ['fairness', 'impartiality'],
  },
  {
    word: 'unorthodox',
    definition: 'not following usual ideas',
    synonyms: ['unusual', 'original'],
    antonyms: ['orthodox', 'traditional'],
  },
  {
    word: 'guard',
    definition: 'protect; person who protects',
    synonyms: ['defend', 'watch'],
    antonyms: ['neglect', 'expose'],
  },

  {
    word: 'callow',
    definition: 'young and inexperienced',
    synonyms: ['immature', 'green'],
    antonyms: ['mature', 'experienced'],
  },
  {
    word: 'faux',
    definition: 'made to look real but isn’t',
    synonyms: ['fake', 'false'],
    antonyms: ['genuine', 'real'],
  },
  {
    word: 'impervious',
    definition: 'not letting things through',
    synonyms: ['watertight', 'sealed'],
    antonyms: ['porous', 'leaky'],
  },
  {
    word: 'augment',
    definition: 'make larger',
    synonyms: ['increase', 'enlarge'],
    antonyms: ['reduce', 'diminish'],
  },
  {
    word: 'repent',
    definition: 'feel sorry for wrongs',
    synonyms: ['regret', 'atone'],
    antonyms: ['celebrate', 'persist'],
  },
  {
    word: 'pretentious',
    definition: 'trying to impress, but over-the-top',
    synonyms: ['showy', 'flashy'],
    antonyms: ['modest', 'simple'],
  },
  {
    word: 'alert',
    definition: 'watchful and awake',
    synonyms: ['attentive', 'awake'],
    antonyms: ['sleepy', 'unaware'],
  },
  {
    word: 'reluctant',
    definition: 'not wanting to do something',
    synonyms: ['unwilling', 'hesitant'],
    antonyms: ['eager', 'keen'],
  },
  {
    word: 'frivolous',
    definition: 'not serious or useful',
    synonyms: ['silly', 'trivial'],
    antonyms: ['serious', 'important'],
  },
  {
    word: 'intrepid',
    definition: 'very brave',
    synonyms: ['fearless', 'bold'],
    antonyms: ['cowardly', 'timid'],
  },

  {
    word: 'bolster',
    definition: 'support or strengthen',
    synonyms: ['support', 'boost'],
    antonyms: ['weaken', 'undermine'],
  },
  {
    word: 'conventional',
    definition: 'usual and normal',
    synonyms: ['traditional', 'standard'],
    antonyms: ['unusual', 'radical'],
  },
  {
    word: 'taut',
    definition: 'stretched tight',
    synonyms: ['tight', 'tense'],
    antonyms: ['slack', 'loose'],
  },
  {
    word: 'system',
    definition: 'set of connected parts',
    synonyms: ['structure', 'network'],
    antonyms: ['chaos', 'disorder'],
  },
  {
    word: 'nobility',
    definition: 'high moral qualities; royal class',
    synonyms: ['honour', 'aristocracy'],
    antonyms: ['baseness', 'commoners'],
  },
  {
    word: 'beam',
    definition: 'long piece of wood; smile widely',
    synonyms: ['girder', 'grin'],
    antonyms: ['frown', 'glower'],
  },
  {
    word: 'contrived',
    definition: 'unnatural and forced',
    synonyms: ['artificial', 'forced'],
    antonyms: ['natural', 'genuine'],
  },
  {
    word: 'taint',
    definition: 'spoil with something bad',
    synonyms: ['contaminate', 'stain'],
    antonyms: ['purify', 'cleanse'],
  },
  {
    word: 'insert',
    definition: 'put into',
    synonyms: ['put in', 'add'],
    antonyms: ['remove', 'extract'],
  },
  {
    word: 'parliament',
    definition: 'law-making body',
    synonyms: ['legislature', 'assembly'],
    antonyms: ['dictatorship', 'autocracy'],
  },

  {
    word: 'banal',
    definition: 'boring because common',
    synonyms: ['trite', 'dull'],
    antonyms: ['original', 'fresh'],
  },
  {
    word: 'haste',
    definition: 'great speed',
    synonyms: ['rush', 'speed'],
    antonyms: ['slowness', 'delay'],
  },
  {
    word: 'embellish',
    definition: 'add decoration',
    synonyms: ['decorate', 'ornament'],
    antonyms: ['simplify', 'strip'],
  },
  {
    word: 'margin',
    definition: 'edge or extra amount',
    synonyms: ['edge', 'border'],
    antonyms: ['centre', 'core'],
  },
  {
    word: 'nouveau-riche',
    definition: 'newly rich people',
    synonyms: ['upstart', 'parvenu'],
    antonyms: ['old-money', 'aristocrat'],
  },
  {
    word: 'superior',
    definition: 'better in quality',
    synonyms: ['better', 'higher'],
    antonyms: ['inferior', 'worse'],
  },
  {
    word: 'really',
    definition: 'in fact; very',
    synonyms: ['actually', 'truly'],
    antonyms: ['supposedly', 'barely'],
  },
  {
    word: 'vigour',
    definition: 'physical strength and energy',
    synonyms: ['energy', 'force'],
    antonyms: ['weakness', 'fatigue'],
  },
  {
    word: 'mercurial',
    definition: 'changing mood quickly',
    synonyms: ['fickle', 'volatile'],
    antonyms: ['stable', 'steady'],
  },
  {
    word: 'confine',
    definition: 'keep within limits',
    synonyms: ['limit', 'restrict'],
    antonyms: ['free', 'release'],
  },

  {
    word: 'evanescent',
    definition: 'lasting a short time',
    synonyms: ['brief', 'fleeting'],
    antonyms: ['lasting', 'enduring'],
  },
  {
    word: 'celestial',
    definition: 'related to the sky',
    synonyms: ['heavenly', 'astral'],
    antonyms: ['terrestrial', 'earthly'],
  },
  {
    word: 'magnanimous',
    definition: 'kind to someone you defeated',
    synonyms: ['generous', 'big-hearted'],
    antonyms: ['mean', 'petty'],
  },
  {
    word: 'dale',
    definition: 'a valley',
    synonyms: ['valley', 'vale'],
    antonyms: ['hill', 'mount'],
  },
  {
    word: 'apprehensive',
    definition: 'worried about future',
    synonyms: ['nervous', 'anxious'],
    antonyms: ['confident', 'calm'],
  },
  {
    word: 'rowdy',
    definition: 'noisy and rough',
    synonyms: ['boisterous', 'loud'],
    antonyms: ['quiet', 'calm'],
  },
  {
    word: 'jargon',
    definition: 'special words of a group',
    synonyms: ['terminology', 'lingo'],
    antonyms: ['plain-speech', 'standard'],
  },
  {
    word: 'parable',
    definition: 'short story teaching a lesson',
    synonyms: ['fable', 'allegory'],
    antonyms: ['fact', 'report'],
  },
  {
    word: 'scrutinize',
    definition: 'look at very closely',
    synonyms: ['inspect', 'examine'],
    antonyms: ['skim', 'glance'],
  },
  {
    word: 'delude',
    definition: 'fool someone',
    synonyms: ['deceive', 'mislead'],
    antonyms: ['enlighten', 'inform'],
  },

  {
    word: 'vain',
    definition: 'too proud of looks',
    synonyms: ['conceited', 'proud'],
    antonyms: ['modest', 'humble'],
  },
  {
    word: 'provocative',
    definition: 'causing anger or interest',
    synonyms: ['stimulating', 'annoying'],
    antonyms: ['soothing', 'boring'],
  },
  {
    word: 'abhorrent',
    definition: 'very disgusting',
    synonyms: ['hateful', 'repugnant'],
    antonyms: ['pleasant', 'agreeable'],
  },
  {
    word: 'absolute',
    definition: 'total and complete',
    synonyms: ['total', 'utter'],
    antonyms: ['partial', 'limited'],
  },
  {
    word: 'impeccable',
    definition: 'perfect and without fault',
    synonyms: ['perfect', 'flawless'],
    antonyms: ['flawed', 'imperfect'],
  },
  {
    word: 'adjourn',
    definition: 'break a meeting for later',
    synonyms: ['suspend', 'postpone'],
    antonyms: ['continue', 'convene'],
  },
  {
    word: 'tries',
    definition: 'attempts',
    synonyms: ['attempts', 'efforts'],
    antonyms: ['neglects', 'ignores'],
  },
  {
    word: 'especially',
    definition: 'more than usual',
    synonyms: ['particularly', 'mainly'],
    antonyms: ['rarely', 'hardly'],
  },
  {
    word: 'alleviate',
    definition: 'make pain less',
    synonyms: ['ease', 'relieve'],
    antonyms: ['worsen', 'aggravate'],
  },
  {
    word: 'arid',
    definition: 'dry and without rain',
    synonyms: ['dry', 'parched'],
    antonyms: ['humid', 'wet'],
  },

  {
    word: 'mock',
    definition: 'make fun of',
    synonyms: ['ridicule', 'tease'],
    antonyms: ['praise', 'compliment'],
  },
  {
    word: 'trivial',
    definition: 'not important',
    synonyms: ['minor', 'insignificant'],
    antonyms: ['major', 'important'],
  },
  {
    word: 'predator',
    definition: 'animal that hunts others',
    synonyms: ['hunter', 'carnivore'],
    antonyms: ['prey', 'herbivore'],
  },
  {
    word: 'aesthetic',
    definition: 'to do with beauty',
    synonyms: ['artistic', 'beautiful'],
    antonyms: ['ugly', 'unattractive'],
  },
  {
    word: 'jocular',
    definition: 'joking and playful',
    synonyms: ['funny', 'humorous'],
    antonyms: ['serious', 'solemn'],
  },
  {
    word: 'squander',
    definition: 'spend wastefully',
    synonyms: ['waste', 'throw away'],
    antonyms: ['save', 'conserve'],
  },
  {
    word: 'vixen',
    definition: 'female fox; angry woman',
    synonyms: ['she-fox', 'shrew'],
    antonyms: ['dog-fox', 'gentlewoman'],
  },
  {
    word: 'sluggish',
    definition: 'moving slowly',
    synonyms: ['slow', 'lethargic'],
    antonyms: ['quick', 'lively'],
  },
  {
    word: 'emerge',
    definition: 'come into view',
    synonyms: ['appear', 'arise'],
    antonyms: ['disappear', 'vanish'],
  },
  {
    word: 'dictionary',
    definition: 'book of word meanings',
    synonyms: ['lexicon', 'wordbook'],
    antonyms: ['—', '—'],
  },

  {
    word: 'perjury',
    definition: 'lying in court',
    synonyms: ['false oath', 'lying'],
    antonyms: ['truth', 'honesty'],
  },
  {
    word: 'resolve',
    definition: 'decide firmly',
    synonyms: ['determine', 'settle'],
    antonyms: ['hesitate', 'dither'],
  },
  {
    word: 'entire',
    definition: 'whole',
    synonyms: ['whole', 'complete'],
    antonyms: ['partial', 'part'],
  },
  {
    word: 'craving',
    definition: 'strong desire',
    synonyms: ['longing', 'urge'],
    antonyms: ['dislike', 'aversion'],
  },
  {
    word: 'omnivore',
    definition: 'animal that eats plants and meat',
    synonyms: ['all-eater', '—'],
    antonyms: ['herbivore', 'carnivore'],
  },
  {
    word: 'trepidation',
    definition: 'fear about what may happen',
    synonyms: ['fear', 'dread'],
    antonyms: ['confidence', 'assurance'],
  },
  {
    word: 'foolhardy',
    definition: 'brave in a silly way',
    synonyms: ['reckless', 'rash'],
    antonyms: ['careful', 'cautious'],
  },
  {
    word: 'depict',
    definition: 'show in a picture or words',
    synonyms: ['portray', 'illustrate'],
    antonyms: ['conceal', 'hide'],
  },
  {
    word: 'galvanize',
    definition: 'shock into action',
    synonyms: ['motivate', 'spur'],
    antonyms: ['deter', 'discourage'],
  },
  {
    word: 'shrine',
    definition: 'holy place',
    synonyms: ['sanctuary', 'altar'],
    antonyms: ['—', '—'],
  },

  {
    word: 'bickering',
    definition: 'small arguing',
    synonyms: ['squabbling', 'quarrelling'],
    antonyms: ['agreeing', 'peace'],
  },
  {
    word: 'prosperous',
    definition: 'rich and successful',
    synonyms: ['wealthy', 'thriving'],
    antonyms: ['poor', 'struggling'],
  },
  {
    word: 'venerable',
    definition: 'deserving deep respect',
    synonyms: ['respected', 'esteemed'],
    antonyms: ['disrespected', 'dishonoured'],
  },
  {
    word: 'rancour',
    definition: 'bitter hate',
    synonyms: ['resentment', 'grudge'],
    antonyms: ['friendliness', 'goodwill'],
  },
  {
    word: 'querulous',
    definition: 'complaining a lot',
    synonyms: ['grumbling', 'moaning'],
    antonyms: ['cheerful', 'agreeable'],
  },
  {
    word: 'incumbent',
    definition: 'currently holding a position',
    synonyms: ['holder', 'occupant'],
    antonyms: ['challenger', 'newcomer'],
  },
  {
    word: 'distressing',
    definition: 'causing worry and pain',
    synonyms: ['upsetting', 'painful'],
    antonyms: ['comforting', 'pleasant'],
  },
  {
    word: 'meditative',
    definition: 'deeply thoughtful',
    synonyms: ['thoughtful', 'reflective'],
    antonyms: ['careless', 'heedless'],
  },
  {
    word: 'oblong',
    definition: 'long rectangle shape',
    synonyms: ['rectangular', 'elongated'],
    antonyms: ['square', 'round'],
  },
  {
    word: 'illusory',
    definition: 'not real, only seeming',
    synonyms: ['imaginary', 'false'],
    antonyms: ['real', 'genuine'],
  },

  {
    word: 'proclaim',
    definition: 'announce publicly',
    synonyms: ['declare', 'announce'],
    antonyms: ['hide', 'conceal'],
  },
  {
    word: 'opulence',
    definition: 'great wealth and luxury',
    synonyms: ['luxury', 'richness'],
    antonyms: ['poverty', 'simplicity'],
  },
  {
    word: 'complacent',
    definition: 'too satisfied with yourself',
    synonyms: ['smug', 'self-satisfied'],
    antonyms: ['concerned', 'motivated'],
  },
  {
    word: 'incessant',
    definition: 'never stopping',
    synonyms: ['constant', 'endless'],
    antonyms: ['occasional', 'intermittent'],
  },
  {
    word: 'parallel',
    definition: 'side by side and never meeting',
    synonyms: ['aligned', 'matching'],
    antonyms: ['crossing', 'divergent'],
  },
  {
    word: 'momentous',
    definition: 'very important',
    synonyms: ['significant', 'historic'],
    antonyms: ['insignificant', 'trivial'],
  },
  {
    word: 'ratify',
    definition: 'formally approve',
    synonyms: ['approve', 'confirm'],
    antonyms: ['reject', 'void'],
  },
  {
    word: 'reprimand',
    definition: 'official scolding',
    synonyms: ['scold', 'rebuke'],
    antonyms: ['praise', 'commend'],
  },
  {
    word: 'parsimony',
    definition: 'extreme stinginess',
    synonyms: ['meanness', 'miserliness'],
    antonyms: ['generosity', 'lavishness'],
  },
  {
    word: 'resilience',
    definition: 'ability to recover quickly',
    synonyms: ['toughness', 'bounce-back'],
    antonyms: ['fragility', 'weakness'],
  },

  {
    word: 'incentive',
    definition: 'something that motivates',
    synonyms: ['motivation', 'stimulus'],
    antonyms: ['deterrent', 'discouragement'],
  },
  {
    word: 'destitute',
    definition: 'extremely poor',
    synonyms: ['poverty-stricken', 'needy'],
    antonyms: ['wealthy', 'rich'],
  },
  {
    word: 'origin',
    definition: 'where something begins',
    synonyms: ['source', 'beginning'],
    antonyms: ['end', 'result'],
  },
  {
    word: 'commemorate',
    definition: 'honour the memory of',
    synonyms: ['celebrate', 'remember'],
    antonyms: ['forget', 'ignore'],
  },
  {
    word: 'charred',
    definition: 'burnt and blackened',
    synonyms: ['scorched', 'burned'],
    antonyms: ['fresh', 'unburnt'],
  },
  {
    word: 'absence',
    definition: 'state of being away',
    synonyms: ['lack', 'non-attendance'],
    antonyms: ['presence', 'attendance'],
  },
  {
    word: 'vapour',
    definition: 'gas made from liquid',
    synonyms: ['steam', 'mist'],
    antonyms: ['liquid', 'solid'],
  },
  {
    word: 'decorum',
    definition: 'proper behaviour',
    synonyms: ['politeness', 'etiquette'],
    antonyms: ['rudeness', 'impropriety'],
  },
  {
    word: 'programme',
    definition: 'planned set of events',
    synonyms: ['schedule', 'plan'],
    antonyms: ['improvisation', 'chaos'],
  },
  {
    word: 'inhabitants',
    definition: 'people living in a place',
    synonyms: ['residents', 'dwellers'],
    antonyms: ['visitors', 'tourists'],
  },

  {
    word: 'corrosive',
    definition: 'able to eat away material',
    synonyms: ['caustic', 'erosive'],
    antonyms: ['neutral', 'benign'],
  },
  {
    word: 'cache',
    definition: 'hidden store of things',
    synonyms: ['hoard', 'store'],
    antonyms: ['exposure', 'display'],
  },
  {
    word: 'biased',
    definition: 'unfairly favouring one side',
    synonyms: ['prejudiced', 'partial'],
    antonyms: ['fair', 'impartial'],
  },
  {
    word: 'subservient',
    definition: 'too eager to obey',
    synonyms: ['servile', 'obedient'],
    antonyms: ['dominant', 'assertive'],
  },
  {
    word: 'disinterested',
    definition: 'not taking sides',
    synonyms: ['impartial', 'neutral'],
    antonyms: ['biased', 'partial'],
  },
  {
    word: 'stanza',
    definition: 'group of poem lines',
    synonyms: ['verse', 'section'],
    antonyms: ['prose', 'sentence'],
  },
  {
    word: 'symmetry',
    definition: 'same on both sides',
    synonyms: ['balance', 'evenness'],
    antonyms: ['asymmetry', 'imbalance'],
  },
  {
    word: 'mournful',
    definition: 'full of sadness',
    synonyms: ['sorrowful', 'sad'],
    antonyms: ['cheerful', 'joyful'],
  },
  {
    word: 'provincial',
    definition: 'from countryside; narrow-minded',
    synonyms: ['rural', 'parochial'],
    antonyms: ['urban', 'cosmopolitan'],
  },
  {
    word: 'prodigy',
    definition: 'child with amazing talent',
    synonyms: ['genius', 'wonder'],
    antonyms: ['dullard', 'ordinary'],
  },

  {
    word: 'flourish',
    definition: 'grow well; fancy wave',
    synonyms: ['thrive', 'prosper'],
    antonyms: ['wilt', 'decline'],
  },
  {
    word: 'shoulder',
    definition: 'carry on shoulders; part of body',
    synonyms: ['carry', 'upper arm'],
    antonyms: ['drop', 'disown'],
  },
  {
    word: 'accuse',
    definition: 'say someone did wrong',
    synonyms: ['blame', 'charge'],
    antonyms: ['defend', 'exonerate'],
  },
  {
    word: 'rapacious',
    definition: 'greedy and grasping',
    synonyms: ['greedy', 'predatory'],
    antonyms: ['generous', 'selfless'],
  },
  {
    word: 'liberty',
    definition: 'freedom',
    synonyms: ['freedom', 'independence'],
    antonyms: ['slavery', 'bondage'],
  },
  {
    word: 'engrossed',
    definition: 'totally absorbed',
    synonyms: ['absorbed', 'busy'],
    antonyms: ['bored', 'distracted'],
  },
  {
    word: 'harmonious',
    definition: 'in agreement; musical',
    synonyms: ['agreeable', 'melodious'],
    antonyms: ['discordant', 'harsh'],
  },
  {
    word: 'reel',
    definition: 'spin around; fishing spool',
    synonyms: ['spin', 'whirl'],
    antonyms: ['steady', 'still'],
  },
  {
    word: 'exaggerate',
    definition: 'make something seem bigger',
    synonyms: ['overstate', 'inflate'],
    antonyms: ['understate', 'minimise'],
  },
  {
    word: 'consistency',
    definition: 'staying the same',
    synonyms: ['uniformity', 'regularity'],
    antonyms: ['variation', 'inconsistency'],
  },
];
